### ISSUE TITLE
EMI: Transition effects in the set kab are too dark

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#1045]
![residualvm 2014-08-18 15-37-50-09](https://cloud.githubusercontent.com/assets/757718/3951354/cb8812cc-26d4-11e4-8bb8-ed54049b3328.png)

Tested on 1a07a2329.

**Comment by chkr-private** [comment]
Fixed in master by a2e1c64d3629d3ba3b2aac31070416e461f69f1e.
