### ISSUE TITLE
EMI: Cannonball is drawn on the ground before the cannon is fired in kab

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#1046]
In the set kab, the cannonball is visible on the ground even before Casaba fires the cannon.

![residualvm 2014-08-18 15-41-38-00](https://cloud.githubusercontent.com/assets/757718/3951379/61a03f3c-26d5-11e4-94ea-7874e1bbd6ff.png)

**Comment by monkeymadness** [comment]
Cannonball still sits on the ground prior to the shot. New cannonball replaces the graphics glitch.

![twocannonballs](https://cloud.githubusercontent.com/assets/10478990/5693231/64115bf2-98d1-11e4-91b3-cb6efc18c87b.jpg)


Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374

**Comment by chkr-private** [comment]
Fixed by merging pull request #1192.
