### ISSUE TITLE
EMI: Wrong footstep sounds on the Jambalaya beach

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#1047]
When walking on the beach on Jambalaya island, it sounds like Guybrush is walking on wood. In the original the wood footsteps are only heard when walking on the pier.

Tested on 1a07a2329.

**Comment by monkeymadness** [comment]
Still an issue.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374
