### ISSUE TITLE
EMI: Animation snaps to wrong frame when jumping out of the bank window

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#1048]
Although Guybrush is already on the ground, the animation will snap briefly into a mid-air position.

![residualvm 2014-08-18 15-56-20-02](https://cloud.githubusercontent.com/assets/757718/3951478/3bf6eec8-26d7-11e4-8b47-2ba6a366eaef.png)

Tested on 1a07a2329.

**Comment by monkeymadness** [comment]
Still an issue.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374

**Comment by chkr-private** [comment]
Fixed by commit d8ef15acc2d131815c8a0c06d000ecc1efe11ad3.
