### ISSUE TITLE
EMI: Transparency issue with the overturned brazier when using TinyGL renderer

### ISSUE THREAD

**Issue by eriktorbjorn** [residualvm/residualvm#1051]
When using the TinyGL renderer, the graphics from the overturned brazier at the beginning of the game is obscuring Guybrush's feet. I assume this is some kind of transparency issue. (It's not the only glitch in the screenshot, but it's the most noticeable one to me.)

![mi4-tinygl-transparency](https://cloud.githubusercontent.com/assets/601765/3958019/3fa80c02-271b-11e4-8474-fbf1c0accd33.png)

**Comment by vpelletier** [comment]
I can't reproduce this bug as of b51d7a02b41787a4cbcb54219ba5edaf8bc7af00 .

**Comment by Botje** [comment]
Cannot reproduce with a 2020 daily build either.
