### ISSUE TITLE
EMI: Guybrush rotates weirdly when talking to the catapult operator

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1055]
Just after Guybrush has tinkered with the catapult controls, his lower body just rotates to match against the operator. Then again when he's changed sides of the screen (after the explosion). Finally, when the operator leaves, he fixates his head at the ground while rotating to match Elaine's position.

**Comment by monkeymadness** [comment]
I seemed to have this issue when positioning Guybrush in a weird direction. He either turns his head to a funky angle or rotates weirdly. Did this happen in the original game?

**Comment by andrews05** [comment]
I've found most characters seem to pivot on the spot rather than stepping/jumping to turn around. E.g. when talking to the dart players and they have to turn around to face you.
