### ISSUE TITLE
EMI: When throwing the duck through Pegnose's window, it is visible through the wall.

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1065]
Exactly what it says in the title.

**Comment by monkeymadness** [comment]
I believe this is fixed with the current version.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0git52010ff
