### ISSUE TITLE
EMI: Ozzie is invisible when close to his chair.

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1066]
This is after putting termites on his cane.
![efmi005](https://cloud.githubusercontent.com/assets/543402/3969841/cf3dbee4-27c4-11e4-80b2-6d6c548e5d4c.png)
![ozzie](https://cloud.githubusercontent.com/assets/543402/3969857/edd7ce26-27c4-11e4-986b-d510f044c63c.png)

**Comment by monkeymadness** [comment]
I think this is fixed with the current version.
