### ISSUE TITLE
EMI: Just before the video of placing the nose on Pegnose, there is quite a lot of flicker

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1067]
Once you give the heirlooms and screw to Cannard, he will try to place the nose on Pegnose, that triggers a lot of flicker between fully white and the outside set, before the movie starts.

Savegame with the heirlooms and screw in place:

![efmi006](https://cloud.githubusercontent.com/assets/543402/3970025/289a9f56-27c6-11e4-89be-2e1477b5664c.png)

**Comment by monkeymadness** [comment]
I think this is fixed with the current version.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0git52010ff
