### ISSUE TITLE
EMI: WARNING: Lua: call expression not a function! spams the log once the ship is back on Melee Island

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1068]
After the video of placing the nose on peg nose, as Guybrush is talking to his crew on the docks of Melee Island, the log is spammed with a ton of WARNING: Lua: call expression not a function!

**Comment by monkeymadness** [comment]
![log](https://cloud.githubusercontent.com/assets/10478990/7602648/5f822b98-f8e4-11e4-832d-fb3a1e55f01c.jpg)
