### ISSUE TITLE
MYST3: Tie menu language to text language?

### ISSUE THREAD

**Issue by andrews05** [residualvm/residualvm#1084]
I always thought it very strange how in the multilingual editions of Myst 3 the menu was split out of the .m3t file into a new .m3u file that had to be chosen at install time rather than run time. I think it would be nice if the game first looked for an .m3u file matching the chosen text language, before falling back to "language.m3u" and then the exe's language.

The reason I say this is I'm working on a ResidualVM-based installer program for Myst 3 on OS X and it would be great if I could do a "full" multilingual install of the game where they can switch language in the preferences at any time and I don't have to ask them which menu language they want to install.

**Comment by bgK** [comment]
This restriction has now been lifted.
