### ISSUE TITLE
EMI: Lever of the stove in LUA bar misplaced

### ISSUE THREAD

**Issue by chkr-private** [residualvm/residualvm#1092]
How to reproduce:
- jump 200
- get paintbrush from Meathook
- enter LUA bar
- jam propulsion mechanism
- enter kitchen

The lever of the stove is misplaced. The brass monkeys hands don't touch the lever, it is placed a little bit to the left. The movement of the lever is OK though.

**Comment by monkeymadness** [comment]
Here is a picture of the problem.

![lever](https://cloud.githubusercontent.com/assets/10478990/7602295/ffea061e-f8df-11e4-86f8-d2a71a5f8859.jpg)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0git52010ff
