### ISSUE TITLE
GRIM: Manny gets put into wrong animation state after giving glottis the vip ticket

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#1131]
In year 2, after you get the vip ticket from Charlie, give it to glottis and hit period to skip the dialog. Sometimes manny gets into an odd state where he isn't animated and rotates from a point behind himself. After leaving the set the issue resolves itself.

Save before it happens (doesn't always happen though):
![grim02 gsv](https://cloud.githubusercontent.com/assets/240865/5554525/dc57697c-8c14-11e4-86a6-00288b383e60.png)

Save after it happens:
![grim012 gsv](https://cloud.githubusercontent.com/assets/240865/5554524/d736de14-8c14-11e4-9651-73ea9f4b3064.png)

**Comment by eblanca** [comment]
Still existing in recent residualvm.

ResidualVM 0.4.0git (Jul  4 2018 20:27:13)
Features compiled in: Vorbis MP3 ALSA RGB zLib Theora FreeType2 JPEG PNG
