### ISSUE TITLE
GRIM: Staying in manny's inventory in the high rollers lounge kitchen when the waiter is in the pantry is different than in grim

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#1135]
Go to the high rollers lounge kitchen. Let the waiter walk into the pantry. Open the inventory. Wait. Close the inventory. The waiter will have teleported to the side of the pantry.

![screenshot 2014-12-26 08 47 33](https://cloud.githubusercontent.com/assets/240865/5558415/d5f74ea4-8cdb-11e4-8cde-b5d7e009e6ca.png)

In original grim, the waiters lines are said over the inventory, and he is gone when the inventory is closed.

The waiter must be walking around, so you can't just jump to the set.

Save: ![grim03 gsv](https://cloud.githubusercontent.com/assets/240865/5554550/108882d4-8c16-11e4-99b4-2e9ad23334a2.png)

**Comment by eblanca** [comment]
Still happens in recent residualvm.

ResidualVM 0.4.0git (Jul  4 2018 20:27:13)
Features compiled in: Vorbis MP3 ALSA RGB zLib Theora FreeType2 JPEG PNG
