### ISSUE TITLE
outdated LUA license

### ISSUE THREAD

**Issue by onlyjob** [residualvm/residualvm#1145]
`COPYING.LUA` as well as `engines/grim/lua/lua.h` mention old LUA license however according to http://www.lua.org/license.html LUA (including all previous releases) was re-licensed under the terms of the MIT license (also known as "Expat").

Please update licensing information for `engines/grim/lua/*` and extend scope of the `COPYING.MIT`. Thanks.

**Comment by aquadran** [comment]
"Check the source distribution for the exact license text for each version before Lua 5.0. Nevertheless, if you wish to use those old versions, you may hereby assume that they have all been re-licensed under the MIT license as described above." that doesn't mean they are re-licensed to MIT, that mean you can use under that license, but that is not obligatory.
However using MIT license will simplify things. we will look into.

**Comment by onlyjob** [comment]
Sorry for being pedantic but since MIT license is more permissive it looks like one might not be able to enforce limitations of the old license any more hence it is more accurate to say "re-licensed" under new terms than "dual licensed under LUA or MIT license" even though both are correct, technically speaking.

Indeed using just MIT will be simpler. Thanks.

**Comment by somaen** [comment]
This isn't necessarily THAT simple, as any changes to the LUA code that we might have done doesn't automatically follow onto the upstream license change, without checking up with whoever did the changes and getting an OK to that. (It might have been easier if the change was to more restrictive).

**Comment by aquadran** [comment]
indeed, asking everyone might not be possible now, so better stay at LUA license

**Comment by aquadran** [comment]
we decided to keep as it is.
