### ISSUE TITLE
GRIM: ResidualVM crashing when loading SaveGame

### ISSUE THREAD

**Issue by BobOmber** [residualvm/residualvm#1148]
Playing Grim Fandango on ResidualVM wih Grim Mouse 0.7 mod, game crashed short after entering Domino's room (early start of the game), when I tried to change the automatic message of his computer. Clicked one option but the first one was selected, after it I tried to click the option I wanted but the game crashed.
Now game crashes when trying to load the savegame, with both the modded ResidualVM and the genuine ResidualVM 0.2.0.

Whole console log on ResidualVM 0.2.0:

User picked target ’grim-win’ (gameid ’grim’)...
Looking for a plugin supporting this gameid... Grim Engine
Starting ’Grim Fandango’
INFO: OpenGL Vendor: NVIDIA Corporation
INFO: OpenGL Renderer: GeForce 495/PCIe/SSE2
INFO: OpenGL Version: 3.3.9
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
WARNING: Lua_v1::SetGamma, implement opcode, level: 0.000000!
GrimEngine::savegameRestore() started.
Assertion failed: obj->value.f, file engines/grim/lua/lrestore.cpp, line 174
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application’s support team for more information.

**Comment by Botje** [comment]
Sorry, we don't support the mouse mod. Saves are also not compatible between ResidualVM 2.0 and the mouse mod.
