### ISSUE TITLE
EMI: Guybrush fades in and out as he jumps up to the bank window

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1151]
Screenshot shows the partial fade. Same fade happened at the Scumm bar steps, which is similar to issue #896.

![jumpingguybrush](https://cloud.githubusercontent.com/assets/10478990/5692861/9df55462-98c3-11e4-98dd-b5b158c722f3.jpg)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374

Save File:
![efmi002](https://cloud.githubusercontent.com/assets/10478990/5693139/3ead5c52-98cd-11e4-9c6f-e56864059681.png)

**Comment by chkr-private** [comment]
Fixed by commit 6d226501b5a96b2f02035f9f4d82d54261eb2749.
