### ISSUE TITLE
EMI: Guybrush rotates at a weird angle when getting on the raft

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1152]
Bug only occurs when getting on the raft.

![ontheraft](https://cloud.githubusercontent.com/assets/10478990/5692920/678207d4-98c5-11e4-927d-dd174ec4376f.jpg)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374

Save File:
![efmi003](https://cloud.githubusercontent.com/assets/10478990/5693142/65464720-98cd-11e4-9a53-6697867f387d.png)

**Comment by somaen** [comment]
ResidualVM version? Nightly?

**Comment by MrLint** [comment]
I can confirm this on the nightly. Do you need a trace? @somaen
