### ISSUE TITLE
EMI: Some of the credits do not do not have the right color tint

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1155]
The credits have usually around half stay a dark grey instead of the right color.

![weirdendcredits](https://cloud.githubusercontent.com/assets/10478990/5692970/29b7faa6-98c7-11e4-9cc5-5d076b2857d4.jpg)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374

**Comment by chkr-private** [comment]
Fixed by commit be771ab4546ac589b81d7291c3156e79cbaf28a2.
