### ISSUE TITLE
the original patch of grim fandango is missing

### ISSUE THREAD

**Issue by therealtimshady** [residualvm/residualvm#1164]
I tried to search for this problem but couldn't find anything

I have transferred all the LAB files into a folder and downloaded the grimup101.exe file from the residual vm website and transferred that into the folder but when I hit the start button residual vm is insistent the patch is not there even though it is. Help?

**Comment by somaen** [comment]
The file should be named gfupd101.exe

Den onsdag 28. januar 2015 skrev therealtimshady <notifications@github.com>
følgende:

**Comment by therealtimshady** [comment]
thanks - remarkable I have just found the problem, with numerous attempts to get the game to work via the cd and applying the update directly not via residualvm I had gfup101 (2).exe,   gfup101 (3).exe etc , for some strange reason is wanted the gfup101.exe and not (2) , even though its the same file.

strange but problem sorted - wish I hadn't spent the £20 on the remastered version as that doesn't work due to opengl
