### ISSUE TITLE
EMI: Graphics issue in Fullscreen

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1165]
In order to recreate the bug you must play the game in fullscreen.
Happens to many characters, but not all.

![shadows](https://cloud.githubusercontent.com/assets/10478990/5990223/f00d8a2a-a963-11e4-9174-2d27329acc55.png)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitc5ccf4d

Save File:
![efmi002](https://cloud.githubusercontent.com/assets/10478990/5990245/48055180-a965-11e4-86da-d7bf68b0548e.png)

**Comment by Botje** [comment]
I can reproduce the problem on my AMD box.
It looks like some characters are drawn with 0 alpha, which makes the underlying black background poke through.
The culprit is the glColor4ub call when drawing actor parts, of course.
Could this be related to a wonky RGB->RGBA conversion?
