### ISSUE TITLE
EMI: Miss Rivers walks through Yannia's chair

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1166]
This occurs during the classroom scene. Miss Rivers disposes of Mungol's gum. On the way back, she walks through the chair. Could be similar to issue #1050, but maybe not because it is another character.

![miss rivers](https://cloud.githubusercontent.com/assets/10478990/5990326/3b158244-a968-11e4-9b58-583c256cee3e.png)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitc5ccf4d

**Comment by MrLint** [comment]
I can confrim this occurs in the SW renderer too, assuming that has any bearing on the issue.
