### ISSUE TITLE
EMI: Guybrush walks on stake at Pegnose House

### ISSUE THREAD

**Issue by monkeymadness** [residualvm/residualvm#1168]
This bug happens in the cutscene.

![walk on stake](https://cloud.githubusercontent.com/assets/10478990/6016226/265b79fa-ab3c-11e4-8e12-b0369a079dc5.png)

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitc5ccf4d

Save File:
![efmi008](https://cloud.githubusercontent.com/assets/10478990/6016229/2c15ffaa-ab3c-11e4-9625-d518257c4655.png)

**Comment by Botje** [comment]
This looks like it's fixed in the current master (fb3bd81).
