### ISSUE TITLE
EMI: PS2 version gets locked into the theme music when trigging credits from bonus menu.

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#1171]
To repeat:
1: Start game, ESC through to wed.
2: F1
3: Options
4: Bonus features
5: Credits
6: ESC

You should now have the credits music rolling, even though you're still not watching the credits, going back into the game seems to retrigger the correct music.

**Comment by Akz-** [comment]
IIRC this happens in the original too, in both the PC and PS2 versions of the game.
