### ISSUE TITLE
Grim Fandango: German Jewel Case Version not  fully recognized

### ISSUE THREAD

**Issue by aoe1** [residualvm/residualvm#1173]
Hi,

Coincidentally I bought an actual physical copy of the game about 10 years ago for EUR 2 that I just unwrapped and installed yesterday. I cursed at the interface multiple times but it was playable to the end.

It is a German 2 CD Version for "Windows 95/98" with the manual on CD, let me know if you need any additional info or cover art for the wiki.

As seems to be usual, the CDs were "protected" by a few "oversize" files like year6mus.lab. I even had to remove this ("incomplete") file since ResidualVM complained about a room beyond the of the purported end of this file.

Also, it (at least the 0.2.1 Version from Jan 24) complained about the following "wrong" checksums:

WARNING: 'vox0003.lab' may be corrupted. MD5: '5bda9a36181c1fea368491b842c11efe'!
WARNING: 'vox0000.lab' may be corrupted. MD5: 'e884221099ba62dacf04a35be8428419'!
WARNING: 'movie03.lab' may be corrupted. MD5: '85a720936044f99ea7c08522606349b8'!
WARNING: 'movie01.lab' may be corrupted. MD5: 'b5a67c98be256eddaf731b39e0ceb8bd'!
WARNING: 'local.lab' may be corrupted. MD5: '27c961c16f9eaf0260781883150e5611'!

After those messages is was playable as expected, congratulations on the great work with the engine!

Cheers,
  Alexander Oelzant

**Comment by Botje** [comment]
Thanks. Can you try adding the game again with a recent daily build? #845 recently added some MD5sums for a German Grim.

**Comment by aoe1** [comment]
Sorry, I couldn't find the i386 daily builds yesterday - now I did :)

Most of the checksums now went through, those two remained:

WARNING: 'movie01.lab' may be corrupted. MD5: 'b5a67c98be256eddaf731b39e0ceb8bd'!
WARNING: 'movie03.lab' may be corrupted. MD5: '85a720936044f99ea7c08522606349b8'!

**Comment by TobiX** [comment]
@aoe1 Those are the "copyprotected" files IIRC... Just use labcopy from residualvm-tools to strip of the junk at the end and they should verify.

**Comment by aquadran** [comment]
We don't support this version
