### ISSUE TITLE
EMI : PC Unrecognized version

### ISSUE THREAD

**Issue by stephanM92** [residualvm/residualvm#1178]
Hi there,
After copying all the MB4 files, and the both TEXTURE and MOVIE folders, Residual VM does not recognize the game.
I have respected the same tree structure:
EMI (with 15 MB4 files)
 |------Movie
 |------Textures
              |-------Mego
              |-------spago

PC version (2 CD ROM)
French version
Issue identical after the installation of MonkeyUpdate_FRA patch
ResidualVM version  0.2.1 (24 JAN 2015)

Thank you

**Comment by Botje** [comment]
Can you try with a new daily build? EMI support was disabled for ResidualVM 0.2 (to be released in 0.3)

**Comment by aquadran** [comment]
as Botje said. EMI is not supported in stable release yet. if you want try unstable builds get from download page from unstable section.

**Comment by stephanM92** [comment]
Thank you for the feedback. I'm gonna try quickly.

**Comment by stephanM92** [comment]
I have downloaded the daily build version and EMI starts correctly.
Thank you again.
