### ISSUE TITLE
GRIM: Scroll arrows when loading game not visible with TinyGL

### ISSUE THREAD

**Issue by eriktorbjorn** [residualvm/residualvm#1181]
Current Git snapshot, English version of the game.

When loading a game (at least if there are enough savegames so that they aren't all visible at once), there are supposed to be triangular arrows indicating that the list continues. These work for me with the OpenGL renderer (unless I enable shaders), but not with the TinyGL renderer.

It looks like the arrows are made up of filled rectangles. It does call drawRectangle(), and the parameters look sensible enough, but for some reason they just don't show up. Maybe the problem is with BlastRect(), rather than drawRectangle()?

**Comment by vpelletier** [comment]
Adding a call to `TinyGL::tglPresentBuffer();` at the end of `GfxTinyGL::drawRectangle` makes the arrows (partly) visible with tinygl. I do not know if it is a proper fix though.

**Comment by vpelletier** [comment]
Adding more TinyGL::tglPresentBuffer calls actually improve the situation. Specifically, calling it before GfxTinyGL::dimRegion and GfxTinyGL::readPixels. But this is likely not a good solution, as they significantly increase CPU usage when using Copal's computer.

**Comment by aquadran** [comment]
current TinyGL has some issues, please don't add hack like this by adding tglPresentBuffer

**Comment by vpelletier** [comment]
I think the problem comes from gfx_tinygl.cpp poking at the framebuffer directly in these 3 methods (and also in dimRegion & irisAroundRegion, but it's out of the scopr of this bug).
