### ISSUE TITLE
EFMI - control settings resets to default on every exit

### ISSUE THREAD

**Issue by Muyfa666** [residualvm/residualvm#1185]
EFMI - control settings resets to default on every exit. That pretty much sums it up I guess. Using the latest nightly.

**Comment by Botje** [comment]
Still happens with latest master (fb3bd81).
Interesting detail: the options menu actually shows the correct setting, but the controls are always character relative.

**Comment by Muyfa666** [comment]
Update; what I mean is that if I set custom keys for controls, they always resets to default mappnings when I restart the game.

**Comment by Muyfa666** [comment]
I just recently found out that this is not a bug. The controls are always default when starting the game. The custom controller settings are loaded along when you load your save game.
