### ISSUE TITLE
EMI: Mac 10.5 ppc crash with Unknown pixelformat

### ISSUE THREAD

**Issue by jacksand99** [residualvm/residualvm#1198]
Configuration:
Tried 0.2.1 compiled in ppc mac and latest nightly build.
Data files from EMI mac version.
Both version crash loading the game with error:
INFO: OpenGL Vendor: ATI Technologies Inc.
INFO: OpenGL Renderer: ATI Radeon 9600 XT OpenGL Engine
INFO: OpenGL Version: 2.0 ATI-1.5.48
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
Unknown pixelformat: Bpp: 4 RBits: 8 GBits: 8 BBits: 8 ABits: 0 RShift: 16 GShift: 8 BShift: 0 AShift: 0!
residualvm(28908,0xf0289000) malloc: **\* error for object 0x30f5720: Non-aligned pointer being freed (2)
**\* set a breakpoint in malloc_error_break to debug

**Comment by vpelletier** [comment]
May be related to #1300 and the fix may be PR #1302 .

**Comment by klusark** [comment]
Closing this as @vpelletier thinks it might have been fixed.
