### ISSUE TITLE
BUILDBOT: Myst3 on Android not being built because of missing libjpeg

### ISSUE THREAD

**Issue by Botje** [residualvm/residualvm#1199]
As reported in [this forum thread](http://forums.residualvm.org/viewtopic.php?f=1&t=222&start=180#p3899), Myst3 on Android fails to build out of the box.
I checked the buildbot output and found out it's due to a missing libjpeg, which causes the configure to skip the myst3 engine.

**Comment by aquadran** [comment]
libjpeg is now detected on Android build
