### ISSUE TITLE
EMI - Italian 1.1 - Continues and Frequently crash during video.....

### ISSUE THREAD

**Issue by DjDiabolik** [residualvm/residualvm#1201]
Sometimes during a video the games goes in crash............ and will back to desktop whit an error say to me to close the ResidulVM.
I have run from Command prompt for post the output of error:

WARNING: props/lc_puppet/lc_puppet.tga!
WARNING: props/lc_puppet/lc_puppet_crest_modified.tga!
WARNING: props/gb_puppet/gb_puppetface.tga!
WARNING: props/gb_puppet/gb_puppetclothes.tga!
WARNING: props/gb_puppet_inv/gb_puppetface.tga!
WARNING: props/gb_puppet_inv/gb_puppetclothes.tga!
GrimEngine::savegameSave() finished.
WARNING: Lua_V2::GetActiveCD: set to CD: 2!
WARNING: Lua_V2::LoadBundle: stub, name: jambalaya!
WARNING: Sound track 'guypla118.wVC' could not be found to stop!
WARNING: Costume::playChore: Could not find chore: eyes_open!
WARNING: Lua_V1::SetOffscreenTextPos: implement opcode!
WARNING: Sound track 'kahpla044.wVC' could not be found to stop!
WARNING: Sound track 'kahpla048.wVC' could not be found to stop!
WARNING: sound: footsteps/fs_divingboard_02.aif already playing, don't start aga
in!!
WARNING: sound: locationbased/pla_scoreCardUp_02.aif already playing, don't star
t again!!
WARNING: sound: locationbased/pla_scoreCardUp_02.aif already playing, don't star
t again!!
WARNING: Sound track 'guypla009.wVC' could not be found to stop!
WARNING: Sound track 'trppla002.wVC' could not be found to stop!
WARNING: Sound track 'guypla011.wVC' could not be found to stop!
WARNING: Sound track 'guypla012.wVC' could not be found to stop!
WARNING: Sound track 'macpla001.wVC' could not be found to stop!
WARNING: Sound track 'guypla013.wVC' could not be found to stop!
WARNING: Sound track 'guypla003.wVC' could not be found to stop!
WARNING: Bad argument to start_script, ignoring!
WARNING: Sound track 'eddpla054.wVC' could not be found to stop!
WARNING: Sound track 'eddpla055.wVC' could not be found to stop!
WARNING: Sound track 'macpla019.wVC' could not be found to stop!
WARNING: Sound track 'macpla020.wVC' could not be found to stop!
WARNING: Sound track 'macpla021.wVC' could not be found to stop!
WARNING: sound: locationbased/pla_scoreCardUp_02.aif already playing, don't star
t again!!
WARNING: Sound track 'eddpla005.wVC' could not be found to stop!
WARNING: Sound track 'macpla022.wVC' could not be found to stop!
WARNING: Sound track 'macpla027.wVC' could not be found to stop!
WARNING: Sound track 'cwdpla003.wVC' could not be found to stop!
WARNING: Lua_V2::DimScreen: dim: 1.000000!
Assertion failed: _str && idx >= 0 && idx < (int)_size, file ./common/str.h, lin
e 186

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

E:\ResidualVM>

It's useless to post the savegames.........because it's now appened ever.... but sometime yes and other can be reproduced and completed whitout problems.
ResidulVM it's completely runned on a:
Windows 7 x64 whit all windows update........and the version it's the today daily snapshot 0.0.3git8e54a01

In sometime.........the speach it's truncated......... often some speach of some caracters it's like be truncated and for understand i need to activate the subtile.
Otherwise this not a important... but try to fix the continue crash during video because the games in this mode need to continues save and it's frustable to playing :(

**Comment by DjDiabolik** [comment]
Another video... another crash!!!

rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
WARNING: EMISound::stateHasLooped called for a different music state than the cu
rrent one!
Assertion failed: _str && idx >= 0 && idx < (int)_size, file ./common/str.h, lin
e 186

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

E:\ResidualVM>

**Comment by Botje** [comment]
Turning off subtitles for the video seems to avoid the crashes. Subtitle-related, then?

**Comment by DjDiabolik** [comment]
According to the mIRC section i need more test......... thanks otherwise......

**Comment by Botje** [comment]
This is possibly fixed by #1640 as well.
