### ISSUE TITLE
EMI: Italian 1.1, speech truncated

### ISSUE THREAD

**Issue by Botje** [residualvm/residualvm#1202]
Character speech is truncated by a bit. Especially noticeable on long lines or slow talkers.

Reported by @DjDiabolik.

**Comment by DjDiabolik** [comment]
Great... if need some test say whitout a problems......

**Comment by Tea23** [comment]
This is happening in the English version, too.

**Comment by mib85** [comment]
I'm having the same issue.
Playing EMI Italian 1.1 on Ubuntu 18.04 x64.
Is there any fix?

**Comment by Botje** [comment]
Can anyone verify if the original exe plays these sounds correctly? If not this is a game data issue.

**Comment by DjDiabolik** [comment]
@Botje if i remember correctly the original .exe of Escape of Monkey Island not correctly works on recently os. But it's need to use some patch....... of the GOG version:
https://www.gog.com/game/escape_from_monkey_island

Problably for the "old" cd release you need to use this:
https://quickandeasysoftware.net/software/escape-from-monkey-island-setup
And this modified launcher:
https://quickandeasysoftware.net/software/emi-launcher

I honestly remember having replayed the GOG version and I don't remember having this truncated audio problem....
