### ISSUE TITLE
Myst III DVD that came with Myst IV limited edition is unrecognized

### ISSUE THREAD

**Issue by dschepler** [residualvm/residualvm#1204]
When I tried scanning the DVD using "Mass Add", I got:

```
The game in '/media/cdrom0' seems to be unknown.
Please, report the following data to the ResidualVM team along with name
of the game you tried to add and its version/language/etc.:
  {"RSRC.m3r", 0, "a2c8ed69800f60bf5667e5c76a88e481", 1223862},

The game in '/media/cdrom0/M3Data' seems to be unknown.
Please, report the following data to the ResidualVM team along with name
of the game you tried to add and its version/language/etc.:
  {"RSRC.m3r", 0, "a2c8ed69800f60bf5667e5c76a88e481", 1223862},
```

I'm not sure of an official name for the version.  Browsing the DVD filesystem, I see folders "Myst III Dutch", "Myst III English", "Myst III French", "Myst III German", "Myst III Italian", "Myst III Spanish".  I bought the Myst IV package with this DVD in the US when it came out.

**Comment by dschepler** [comment]
Sorry, should have maybe dug a bit deeper searching for a version.  The "Read Instructions First" file says:
```
Myst III: Exile (tm)
Version 1.27 for Windows 95 / 98 / ME / XP and Mac OS 8.1 or 9.1 or OS 10.1
July 21, 2003
```

**Comment by bgK** [comment]
Hi,

This error message means ResidualVM can't find M3.exe. Please make sure it is readily available and using the file hierarchy described in ResidualVM's readme.

**Comment by dschepler** [comment]
Ah, I see...  The DVD has a different version of M3.exe in each "Myst III Language" folder.

It might be a while before I can try copying the files to the expected hierarchy - in the meantime I installed the 4-CD version and started playing.

**Comment by aquadran** [comment]
@dschepler hi, are you that one who is listed in the AUTHORS file? :)

sorry for off topic :)

**Comment by dschepler** [comment]
@aquadran Yes. :)

**Comment by bgK** [comment]
I'm closing this. Reopen if needed.
