### ISSUE TITLE
residualvm -v returns nothing

### ISSUE THREAD

**Issue by goodoldgeorge** [residualvm/residualvm#1214]
command line options -v, or -t is simple run the GUI.

OS: Windows 7 x32

Kirben is solved this problem in scummvm
https://sourceforge.net/p/scummvm/bugs/6907/?page=1

**Comment by Botje** [comment]
Thank you for reporting this, it will get pulled in the next time ResidualVM syncs with ScummVM.

**Comment by bgK** [comment]
This is fixed now
