### ISSUE TITLE
[MYST] Assertion in state.cpp

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1218]
I get an assertion starting the game through launcher on two occasions.

With MiniGL Fullscreen:

User picked target 'myst3-win' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
Initializing database from M3.exe (Platform: Windows) (1.2x Windows)
Initializing OpenGL Renderer
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
WARNING: GL_ARB_texture_non_power_of_two is not available.!
assertion "arrayIndex < 64" failed: file "engines/myst3/state.cpp", line 771

and with Software Renderer Window:

User picked target 'myst3-win' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
Initializing database from M3.exe (Platform: Windows) (1.2x Windows)
Initializing Software 3D Renderer
assertion "arrayIndex < 64" failed: file "engines/myst3/state.cpp", line 771

MiniGL window works
Software Renderer Fullscreen works to an extent, as the initial options book is there, but i can't access it due to the mouse pointer being fixed in the four outer corners of the screen jumping only to that positions on moving the mouse, but that's another issue :-)

**Comment by bgK** [comment]
Can you please try again with the current master version? 4c9ae35 fixed a possible memory corruption issue that may be the cause of your troubles.

**Comment by raziel-** [comment]
@bgK 

Yes, fixed in the latest builds, thanks a lot
