### ISSUE TITLE
EMI Windows Version Full Screen No Longer Works?

### ISSUE THREAD

**Issue by Stingm** [residualvm/residualvm#1227]
Full screen no longer works at all. I tried all the different full screen settings and nothing works now. I was using full screen default with no issues. Now the frame shows up off center and nothing ever shows up. I get sound though. Can you fix it please?

**Comment by raziel-** [comment]
Have you tried setting "aspect_ratio" to false?

**Comment by bgK** [comment]
Should be fixed in git master now.
