### ISSUE TITLE
GRIM: Blue Casket dialogue line cut short

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1229]
In the blue casket if you convince Olivia to read a poem both dialogue lines (Manny's and Olivia's) are cut short and the game instantly switches to Olivia doing the reading on stage.

In the save game, simply choose "Oh, come one..."
Manny's line will be cut short after the "come on" and Olivia simply says "Ok" before she gets warped to the stage.

Save game: 
![grim06](https://cloud.githubusercontent.com/assets/799923/12399237/6fecd976-be21-11e5-9cd0-7e3d00a8e8e7.png)

**Comment by raziel-** [comment]
Sorry, missed some vital information:

ResidualVM 0.3.0git (Jan 17 2016 09:05:14)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

Grim Fandango (Windows/English)

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by Napper64** [comment]
This is actually intentional. If you look at the subtitle history, it reads "Ah come on-" to signify Manny is cut off mid sentence. It is the same with the remastered edition of the game

**Comment by raziel-** [comment]
So, i guess i close this then, since this seems to be the way the devs intended it to be.

Thank you for checking @Napper64
