### ISSUE TITLE
EMI: Missing dialog

### ISSUE THREAD

**Issue by andrews05** [residualvm/residualvm#1232]
There are some lines of dialog that aren't available in the PC version of EMI because it seems to be refusing to show the scroll arrows. This can be seen when talking to the catapult operator: At first there is an option to ask him to join your crew, but once you ask him about the numbers a new option about the cactus becomes available and the crew option is dropped off the list. There is another option that is never seen about why he's having such a hard time hitting the house, and similar unavailable options elsewhere in the game.

Would it be possible to force the scroll arrows to be displayed so you can access all the options?

**Comment by Botje** [comment]
Can't you access these options with the arrow keys as a workaround? Getting these arrows to show up consistently has been annoying, to say the least. But we should take a look at it eventually.

**Comment by andrews05** [comment]
No, they can't be accessed with arrow keys either.

**Comment by andrews05** [comment]
I managed to fix it by changing local.m4b/_dialog.lua:20 from "Dialog.scroll_mode = FALSE" to "Dialog.scroll_mode = TRUE". I created a patchr file for this.
[_dialog.lua.patchr.zip](https://github.com/residualvm/residualvm/files/104138/_dialog.lua.patchr.zip)

**Comment by JohnLBergqvist** [comment]
@andrews05 I don't suppose there's a way to re-integrate the patched `_dialog.lua` into the original `local.m4b` file is there?

**Comment by andrews05** [comment]
@JohnLBergqvist see [here](https://forums.residualvm.org/viewtopic.php?f=1&t=713) for patches and more info.
