### ISSUE TITLE
GRIM: Manny lost walking animation (no feet movement)

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1234]
ResidualVM 0.3.0git (Jan 17 2016 09:05:14)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

Edge of the World
Opening the vault
As soon as the door swings open and ego becomes movable again, ego will have stuck feet.
No walking animation, no matter where you go.

Save game will follow (with the bug in place)
If a save game just before the bug is needed, let me know
![grim15 gsv](https://cloud.githubusercontent.com/assets/799923/12696213/ffe1641c-c76c-11e5-94f1-610a6469d86a.png)

Grim Fandango (Windows/English)

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by raziel-** [comment]
Does anyone else have issues in this scene?

I played along and the walking animation returns to normal once Manny picks up the halberd

**Comment by tobiatesan** [comment]
Can reproduce on ResidualVM 0.2.10eb11b9, Debian Jessie, GL renderer.
