### ISSUE TITLE
MYST: Save not working

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1235]
ResidualVM 0.3.0git (Jan 17 2016 09:05:14)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG

Saving is not possible at all.
Clicking on "Save" doesn't do anything, no save state written, nothing on the console
Lack of a save state permits testing the "Load" feature

Myst III Exile (Windows/English)

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by raziel-** [comment]
It seems to work now, but it's very unintuitive.

I can't see that i have to type a name.
I accidently saved from the original menu by clicking on the line underneath the black rectangle (but no cursor appeared), typed "f" three times and clicked on save.
The launcher menu showed me that the game was saved, but it didn't let me load it from the ingame menu.

**Comment by bgK** [comment]
To sum it up, there is no blinking cursor prompting to enter a save name for you?

**Comment by raziel-** [comment]
Pretty much, yes (if there should be one)

Also, there are no letters visible when i type, so i can't see what i'm typing
and, on loading, there is also a blank page on the left side of the book, when there should be entries.

I can click in the blue there and eventually hit one of the save entries where the "underline" of the save entry will become visible, but that is more or less out of pure luck (and still no visible letters or names of the save entries)
