### ISSUE TITLE
The .deb packages residualvm and residualvm-data collide in /usr/share/pixmaps/residualvm.xpm 

### ISSUE THREAD

**Issue by Mondane** [residualvm/residualvm#1240]
On, at least, Ubuntu, I have to install both packages. But after I did this, I keep getting this error message when booting into Ubuntu:

package residualvm-data 0.1.1+dfsg-2ubuntu1 failed to install/upgrade: trying to overwrite '/usr/share/pixmaps/residualvm.xpm', which is also in package residualvm 0.1.1-1

NB This one is copied from https://bugs.launchpad.net/ubuntu/+source/residualvm/+bug/1385483 . I have the error with version 0.2.1.

Is the package incorrect?

**Comment by aquadran** [comment]
we don't have residualvm-data package, you should remove it if you want from ours download page

**Comment by Botje** [comment]
The Debian (and thus Ubuntu) maintainers have opted to split residualvm into a `residualvm` and a `residualvm-data` package. I checked their build rules and file lists and they only ever put the `residualvm.xpm` into the `residualvm-data` package.

By contrast, the packages from residualvm.org contain everything in the package.
If I interpret the bug report correctly, the reporter first installed our 0.1.1 version (which includes `residualvm.xpm`) and then tried to upgrade this to an ubuntu-provided package.

Can you confirm that you are in the same situation? If this happened on a clean install, using only ubuntu packages, something strange happened.

**Comment by Mondane** [comment]
I can't speak for that guy, but what I did was this:

- Download the .deb from http://www.residualvm.org/downloads/
- Install that .deb.

The next time I ran `sudo apt-get update && sudo apt-get upgrade` I got a message about a missing dependancy 'residualvm-data. It gave me the command to install those missing dependancies:

`sudo apt-get install -f`

Now, everytime I start my PC, I get the herefore mentioned error.

What's the best method to continue now and how to avoid this situation from happening to other users?

**Comment by Botje** [comment]
I think you need to pin the package to the installed version (see http://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package)
The following should do the trick, although I'm not near an ubuntu machine where I can test:
```sh
echo "residualvm hold" | sudo dpkg --set-selections
```

**Comment by aquadran** [comment]
ResidualVM deb packages are not related to Debian packages.
