### ISSUE TITLE
GRIM: Grinder gfx shifts to the left when placed back

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1243]
ResidualVM 0.3.0git (Apr 18 2016 12:41:18)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

Let Manny put the grinder back into it's apparatus shifts the grinder graphics a whole lot to the left once it leaves his hands.
[grim22.zip](https://github.com/residualvm/residualvm/files/265787/grim22.zip)

From the savegame just type "U"

Grim Fandango

AmigaOS4 - SDL - PPC - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by aquadran** [comment]
opengl or tinygl? if it's tinygl check 0.2.1.

**Comment by raziel-** [comment]
Sorry, OpenGL
