### ISSUE TITLE
GRIM: Mannys arm reaches out to the ladder and vanishes

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1244]
ResidualVM 0.3.0git (Apr 18 2016 12:41:18)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG

[grim23.zip](https://github.com/residualvm/residualvm/files/265793/grim23.zip)
From the savegame just type "U" to climb down the ladder

On reaching the ground Manny will stretch his arm towards the ladder and it will vanish shortly after (no animation, it gets just erased)

Grim Fandango

AmigaOS4 - SDL - PPC - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by aquadran** [comment]
opengl or tinygl? if it's tinygl check 0.2.1.

**Comment by raziel-** [comment]
Sorry, OpenGL
