### ISSUE TITLE
GRIM: Pidgeon flies through wall in LSA headquarters

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1245]
ResidualVM 0.3.0git (Apr 18 2016 12:41:18)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG

When you send out the messenger pidgeon to the florist, it will start flying a circle from out of it's cage and through the room door.
Alas the circle it's flying is too small leaving the pidgeon to actually fly through the wall left of the door entrance.

[grim24.zip](https://github.com/residualvm/residualvm/files/265798/grim24.zip)
From the savegame just type "U"

Grim Fandango

AmigaOS4 - SDL - PPC - BE
gcc (adtools build 5.3.0) 5.3.0

**Comment by aquadran** [comment]
opengl or tinygl? if it's tinygl check 0.2.1.

**Comment by raziel-** [comment]
Sorry, OpenGL

**Comment by klusark** [comment]
I can reproduce this still.

**Comment by eblanca** [comment]
I can confirm this behaviour.

ResidualVM 0.4.0git (Jul  4 2018 20:27:13)
Features compiled in: Vorbis MP3 ALSA RGB zLib Theora FreeType2 JPEG PNG

Both OpenGL and software renderer used, same result.
