### ISSUE TITLE
MYST3: Speed difference(s) / Bug(s) when using ResidualVM

### ISSUE THREAD

**Issue by CTxCB** [residualvm/residualvm#1246]
In ResidualVM, compared to playing the actual game, the following have a speed increase of roughly 3x: Game-controlled camera motion (Such as focusing on the elevator in J'nanin when activating it from outside), Player-controlled camera motion, Object animations (Such as the Barrel Puzzle in J'nanin), Transitions after clicking on a hotspot.

The version I am using is the DVD Version (Myst III: Exile v1.27), I get that the reason this probably happens is because ResidualVM doesn't need to read from disc when playing it (If it's the full install), but this does seem to ruin immersion and also partially creates the following bug: If the player clicks multiple times, due to the fast scene transition the player in fact moves multiple more unintended moves too.

**Comment by bgK** [comment]
Can you please try again with the lastest git revision?

Commits 6cb71cd52a9fe0b6a8822d0c910296fcf86bbf79 and c7811b2d25d02e6d874ee0d3cb739142da959807 should fix these problems.
