### ISSUE TITLE
MYST3: Game crash in Amateria

### ISSUE THREAD

**Issue by CTxCB** [residualvm/residualvm#1249]
The version I am using is the DVD Version (Myst III: Exile v1.27). When in the Amateria Age doing the vibrating gates puzzle with the ice ball, the game unexplainably quits / crashes when on the track, and the command prompt gives no reason for quitting / crashing.

**Comment by bgK** [comment]
Please attach a savegame with the gates set for the crash.

**Comment by CTxCB** [comment]
Where does "Default" save the gamegames to? Because it's not in the game's save folder.

**Comment by bgK** [comment]
Windows:
%APPDATA%\ResidualVM\Saved Games\

Linux:
~/.residualvm or $XDG_DATA_HOME/residualvm/saves/

OSX:
$HOME/Documents/ResidualVM Savegames/

**Comment by CTxCB** [comment]
[SAVE 1.zip](https://github.com/residualvm/residualvm/files/285256/SAVE.1.zip) - It doesn't seem to happen instantly upon loading the game, but when exploring the track for a while. Sometimes it's fine and other times it'll crash.

**Comment by bgK** [comment]
Thanks for the save. Unfortunately I've not been able to reproduce the crash after a few minutes of walking on the track. It would help if you were able to produce a stacktrace of the crash.

**Comment by dafioram** [comment]
I am able to reproduce a crash in this area. 

Load the save and take 2 steps forward, now start looking to the right, the crash should happen about then. If you click quickly through the 2nd node it may not crash.

Windows 10, opengl or shader, fullscreen or not, widescreen or not. 

[AMACRASH.zip](https://github.com/residualvm/residualvm/files/2082867/AMACRASH.zip)
[log.txt](https://github.com/residualvm/residualvm/files/2082868/log.txt)
