### ISSUE TITLE
EMI: graphics glitch when checking out the pink ship

### ISSUE THREAD

**Issue by DavidGriffith** [residualvm/residualvm#1264]
As the harbor mistress leads Guybrush to the pink ship, its prow is reversed left-to-right and the bowsprit is shifted left.
![screenshot-residualvm opengl renderer with shaders](https://cloud.githubusercontent.com/assets/1289035/16794054/4968cbc2-488a-11e6-8aa6-db8cc76a899e.png)

Debian 8 Linux, 6b266a9179aaac31fb1e9466dd9bbadade2b071f (master)

**Comment by DavidGriffith** [comment]
Here's a save just before this point (zipped)
[efmi001.zip](https://github.com/residualvm/residualvm/files/360853/efmi001.zip)

**Comment by Botje** [comment]
Seems solved on current version.
