### ISSUE TITLE
Feature Request: Support for Quest for Glory V Dragon Fire

### ISSUE THREAD

**Issue by DingoSaar2** [residualvm/residualvm#1276]
[Quest for Glory V: Dragon Fire](https://en.wikipedia.org/wiki/Quest_for_Glory_V:_Dragon_Fire) is unsupported by [ScummVM](http://wiki.scummvm.org/index.php/Quest_for_Glory_series), as it is a 3D adventure. So it should fall under the scope of **ResidualVM**.

Also, a _label_ for eg. **Unsupported Game** could be created. There currently are at least two games not fully supported right now (eg. _Escape from Monkey Island_).

**Comment by bgK** [comment]
Sorry, we don't take requests to add support for games.
