### ISSUE TITLE
MYST3: Wrong Video Playing

### ISSUE THREAD

**Issue by Diskutant** [residualvm/residualvm#1296]
Loading the save you are in Edanna, watching a bird. But the video doesn't fit with the environment. So this might be a wrong video playing

![bildschirmfoto 2016-07-30 um 08 51 51](https://cloud.githubusercontent.com/assets/898220/17268710/e5fb4086-5632-11e6-94f3-4972a98cddfa.png)

[WRONGVIDEO.M3S.zip](https://github.com/residualvm/residualvm/files/391750/WRONGVIDEO.M3S.zip)

**Comment by bgK** [comment]
I agree the video looks a bit out of place, but the original engine displays it as well in that case. It makes sense to show the bird here after it has been freed.
