### ISSUE TITLE
MYST3: Zip Mode brings you to an unreachable place

### ISSUE THREAD

**Issue by Diskutant** [residualvm/residualvm#1297]
In this save state Zip Mode allows you to go to an normally unreachable place.

![bildschirmfoto 2016-07-30 um 08 54 38](https://cloud.githubusercontent.com/assets/898220/17268718/486e6cac-5633-11e6-9f7d-e01d7e33c8f7.png)

[ZIPBUG.M3S.zip](https://github.com/residualvm/residualvm/files/391751/ZIPBUG.M3S.zip)

**Comment by bgK** [comment]
It's a game script bug that was fixed in the DVD version:
https://gist.github.com/bgK/009c96d8893786d360dd96a500943a06

We should look into providing up-to-date scripts with ResidualVM instead of requiring the game executable.

**Comment by bgK** [comment]
This should be fixed now that #1298 has been merged.
