### ISSUE TITLE
EMI-Demo: Game crashes at start with "Unknown pixelformat"

### ISSUE THREAD

**Issue by immi-h** [residualvm/residualvm#1300]
[patch.zip](https://github.com/residualvm/residualvm/files/453844/patch.zip)
When starting EMI-Demo, the game almost immediately goes into the debugging console, saying
"ERROR: Unknown pixelformat: Bpp: 4 RBits: 8 GBits: 8 BBits: 8 ABits: 0 RShift: 16 GShift: 8 BShift: 0 AShift: 0!"

This only happens when under options, the renderer is OpenGL. (No problems with "OpenGL with shaders" or with "software")

With the attached patch, the problem disappears, but I guess that's not what should be done. (Without the patch, bpp is set to 32 on my system.)

If you have difficulties reproducing the error, I can try to find the real problem, but I'd need some help. (For the moment, I don't know where to look.)

**Comment by vpelletier** [comment]
Hello. Would you be on a big-endian macine ?
The error message comes from [grim/gfx_opengl.cpp](https://github.com/residualvm/residualvm/blob/d467980499120a7cd3796e8b5d2e8715f273317d/engines/grim/gfx_opengl.cpp#L1587). The color description in your error shows it's 24bits (32bits with no alpha), but the component shifts are oppposite to the one tested in the first branch of the `if` - so it looks like just lack of big-endian support.

Could you try adding a branch in that `if` like this:
```c++
        } else if (frame->format == Graphics::PixelFormat(4, 8, 8, 8, 0, 16, 8, 0, 0)) {
                format = GL_RGBA;
                dataType = GL_UNSIGNED_INT_8_8_8_8;
```
(note `format` is different from the one in existing 24bits-color branch)

**Comment by immi-h** [comment]
This added `if` indeed solves the problem. Thanks.
I was also puzzled by the component order in the error message. However, endianness doesn't seem to be the reason. I just double checked: My computer really is little endian.

**Comment by vpelletier** [comment]
> However, endianness doesn't seem to be the reason. 

Yes, it looks like I assumed to much: this function receives data from game files (a video).

It's not clear to me why this error message wouldn't be triggered just by requesting a 16bits mode though.

Also, does the video (Aspyr logo video, as per a comment in the source code) have the same color with both patches (your and mine) ? (hopefully it has separate red-ish and blue-ish areas so you can tell)

**Comment by immi-h** [comment]
Oops, you're right. Your patch makes the video have wrong colors.

In the meantime, I also did some experiments: I added a line to `SurfaceSdlGraphicsManager::setupScreen` (in backends/graphics/surfacesdl/surfacesdl-graphics.cpp) outputting the pixel format of _screen. The result is:
Rmask = ff0000, Gmask = ff00, Bmask = ff, Amask = 0

**Comment by immi-h** [comment]
The color transformation with your patch is the following:
red -> green, green -> blue, blue -> black (i.e., what should be red is displayed green, etc)
If I replace GL_RGBA by GL_BGRA, I get another kind of wrong colors:
red -> green, green -> red, blue -> black

**Comment by immi-h** [comment]
Something else I noticed:
I had written before that with "OpenGL with shaders", the bug does not appear. It's true that there's no crash, but I now noticed that the colors are wrong when using that option: red->green, green->red, blue->black
This is independent of whether one adds the new `if`. However colors do become correct with my patch.
(And there's never a problem when one uses software rendering.)

**Comment by vpelletier** [comment]
I got the GL constants wrong.

I'll try to decompose the correction, mostly to self-check my logic:
From the PixelFormat reported in the initial error, in-memory pixel format is:

- unused: bits 31 (MSb) to 24
- R: bits 23 to 16
- G: bits 15 to 8
- B: bits 7 to 0 (LSb)

Which I'll rewrite as: A(MSB)RGB(LSB).

So R is next to A, so `GL_RGBA` (my original proposal) cannot be correct. So `GL_BGRA` (the format already used in the first `if` branch) should be correct (and AFAIK it is the only other 32bits color format).

For dataType, I would by elimination propose `GL_UNSIGNED_INT_8_8_8_8_REV` (as the non-_REV is incorrect). But I can't tell if `GL_UNSIGNED_CHAR` would be better for endian portability (thinking beyond this bug). I'm quite sure `GL_UNSIGNED_INT` is wrong, as this should mean each component is in a whole `int` by itself.

Could you try with the following code, replacing the change I initially proposed ?
```c++
        } else if (frame->format == Graphics::PixelFormat(4, 8, 8, 8, 0, 16, 8, 0, 0)) {
                format = GL_BGRA;
                dataType = GL_UNSIGNED_INT_8_8_8_8_REV;
```
And maybe also try with `GL_UNSIGNED_CHAR` - if it fails in little endian, it can be ruled out for portability.

**Comment by immi-h** [comment]
I agree with your analysis, and my computer does, too: The colors are correct now.
`GL_UNSIGNED_BYTE` also works, though I'd guess that on big endian machines, `GL_UNSIGNED_INT_8_8_8_8_REV` would be the right one: If I understood correctly, what PixelFormat returns is which bytes of an an integer are which channels, and that's also what one gets with `GL_UNSIGNED_INT_8_8_8_8_REV`. In contrast, with `GL_UNSIGNED_BYTE`, one specifies the byte order in memory, so that would not fit to the output of PixelFormat.

(As you expected `GL_UNSIGNED_INT` is very wrong: segfault.)

What's still wrong, though (and seems to be a separate bug, through most likely related) are the colors when using "OpenGL with shaders"; also there, the order of the bytes seems to be exactly the opposite of what they should be i.e., somewhere one might have to replace a `GL_UNSIGNED_INT_8_8_8_8` by `GL_UNSIGNED_INT_8_8_8_8_REV`.

(I can turn this into a separate issue, if you want.)

**Comment by vpelletier** [comment]
For shaders, it is in [grim/gfx_opengl_shaders.cpp](https://github.com/residualvm/residualvm/blob/ca64a5677dc7c64e723fee5c058a491806f57e67/engines/grim/gfx_opengl_shaders.cpp#L1902). It uses `GL_UNSIGNED_BYTE` and `GL_RGBA` but moves components around in the [corresponding fragment shader](https://github.com/residualvm/residualvm/blob/ca64a5677dc7c64e723fee5c058a491806f57e67/engines/grim/shaders/smush.fragment).

@Botje: What do you think of using `GL_BGRA` in `GfxOpenGLS::prepareMovieFrame` and removing `_smushSwizzle` ? Also, I think this code will need to check more from format than just `bytesPerPixel` and use `GL_UNSIGNED_INT_8_8_8_8`/`GL_UNSIGNED_INT_8_8_8_8_REV` accordingly. Am I missing something ?

**Comment by bgK** [comment]
You might also want to call `VideoDecoder::setDefaultHighColorFormat` in `QuickTimePlayer` so that the video output is always in the same format, rather than in a platform dependent format.

**Comment by vpelletier** [comment]
Hello. I'm back on this, and created pull request #1302 which should fix this bug both in opengl and shader modes.

@immi-h : Could you verify this fixes the crash ? Also, could you check the colors are consistent accross software, opengl and shaders renderer for the video where it used to crash ? I could not identify a quicktime video.

@bgK : I included your suggestion, but could not exercise that code path.

**Comment by immi-h** [comment]
Yes, this fixes the crash, and colors are correct now with all three renderers.
One thought: Is there a way to test it in a setting where the shader has to both, swizzle *and* swap (to make sure this is done in the right order)?

**Comment by vpelletier** [comment]
Looking more into it, I just realised the bink video in the EN demo and my full FR version actually exercise both: the intro video in EN demo is RGB888, but in FR full is BGR888, unlike my first report (which I will amend right away). And the colors are consistent in both cases.

Reversing the swap and swizzle operations in FR full gives a blue title and a violet Guybrush.

**Comment by vpelletier** [comment]
#1302 is merged, fixing this issue.
