### ISSUE TITLE
MYST3: The game does not start after update ResidualVM

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1303]
C:\Program Files (x86)\ResidualVM>"C:\Program Files (x86)\ResidualVM\residualvm.exe"
User picked target 'myst3-win' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
INFO: OpenGL Vendor: Intel
INFO: OpenGL Renderer: Intel(R) HD Graphics 2500
INFO: OpenGL Version: 4.0.0 - Build 10.18.10.4358
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
Common::Array: failure to allocate 1073741824 bytes!

**Comment by bgK** [comment]
Please provide more details regarding your version of Myst III (CD, DVD, Patch level, Language, Platform), and your version of ResidualVM (Release / Daily build, version string).

**Comment by ctoroman** [comment]
-ResudualVM v0.3.0git16938a6 (Sep 17 2016 16:44:16)
-Myst III DVD (patch v1.22, English)
I tried on different computers and systems, an error:
Common::Array: failure to allocate 1073741824 bytes!

PS. Sorry for my english)  I'm russian)

**Comment by ctoroman** [comment]
Thanks. I have another question . The game had "Easter eggs" , called by pressing the " ~ " during the game. Will they maintained ResidualVM?
Sorry for offtopic)

**Comment by bgK** [comment]
The easter eggs worked a long time ago. They probably still work.

**Comment by ctoroman** [comment]
Does not work. Perhaps another key to activate ?

**Comment by bgK** [comment]
Ok, I'll check the easter eggs.

**Comment by ctoroman** [comment]
Thank you )
