### ISSUE TITLE
Myst III: Some animations bugs

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1308]
1. J'nanin. The marbles on the pedestal in the tower moving too slowly when pressing the button in the middle.
![screen1_jnanin](https://cloud.githubusercontent.com/assets/22292375/19713190/8e17e7dc-9b76-11e6-9fa5-480281f49cfa.jpg)

2. Edanna. The middle orchid. Look into the lens and find the rolled up leaf bridge. The bridge unfurls. (No animation). 
![screen2_edanna](https://cloud.githubusercontent.com/assets/22292375/19713337/cdfab252-9b77-11e6-92b6-e85c6787ed84.jpg)

3. Edanna. Go down the path to the end and turn left. In this clearing there is a huge plant. Follow the path all the way up to reach another white orchid. Look into the lens and pan about until the light shines onto the stamen of the huge plant. They rise up in the light. (No animation).
![screen3_edanna](https://cloud.githubusercontent.com/assets/22292375/19713410/77a8c67c-9b78-11e6-9007-09b8d5e62f79.jpg)

**Comment by bgK** [comment]
Can you please provide saves for the last two items?

**Comment by ctoroman** [comment]
[saves.zip](https://github.com/residualvm/residualvm/files/552476/saves.zip)

**Comment by bgK** [comment]
I've been able to reproduce and fix 1. However I'm not sure what's wrong with 2 and 3. Here is how it looks for me:
[Uploading videos.zip…](videos.zip)
Is it different for you?

**Comment by ctoroman** [comment]
Here's my videos. I tried on different computers.
https://cloud.mail.ru/public/K7hz/VganChV1M

**Comment by bgK** [comment]
Thanks, this bug was not affecting the Shader renderer I was testing with.

**Comment by ctoroman** [comment]
Thanks, when distribution will be renewed? (residualvm-win32.exe)
