### ISSUE TITLE
MYST3: Another animation issue

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1310]
J'nanin. Lift handle moves with getting stuck

![screen1](https://cloud.githubusercontent.com/assets/22292375/19799581/0e6af6cc-9d2a-11e6-9b94-436bd912959b.jpg)

savegame: 
[save1.zip](https://github.com/residualvm/residualvm/files/557882/save1.zip)

**Comment by bgK** [comment]
What exactly is wrong with it? I get this: https://youtu.be/dk3zGPpYvPw

**Comment by ctoroman** [comment]
[video1.zip](https://github.com/residualvm/residualvm/files/559628/video1.zip)

By the way, I went through the game until the end and did not notice a problem with animation)

**Comment by bgK** [comment]
Thanks for the report, it's good to know the game is still working after the recent changes.
