### ISSUE TITLE
MYST3: Gear does not move when you press on it in J'nanin

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1312]
ResidualVM v0.3.0gita7aafc9 (Oct 30 2016 20:36:35)
![screen1](https://cloud.githubusercontent.com/assets/22292375/19920271/b0999f3e-a112-11e6-928a-8376a85b484a.jpg)

my savegame: [2.zip](https://github.com/residualvm/residualvm/files/565893/2.zip)

**Comment by bgK** [comment]
Sorry, I broke that with one of the recent commits
