### ISSUE TITLE
MYST3: Sound issue in Voltaic

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1318]
1. When you approach the hatch near the generator, the sounds of water disappears.
savegame: 
[save1.zip](https://github.com/residualvm/residualvm/files/605377/save1.zip)
2. When you approach the hatch after a run gererator, the sound of generator disappears.
savegame: 
[save2.zip](https://github.com/residualvm/residualvm/files/605430/save2.zip)

**Comment by ctoroman** [comment]
When the dam is closed, you can hear the sound of water. It should not be.
[save3.zip](https://github.com/residualvm/residualvm/files/610559/save3.zip)

**Comment by bgK** [comment]
It's normal hearing the sound of the water when the dam is closed, but the volume is lower when compared to when the dam is open.

**Comment by ctoroman** [comment]
ok, thanks )
