### ISSUE TITLE
ANDROID: Cannot browse filesystem on Android Nougat (7.0+)

### ISSUE THREAD

**Issue by Botje** [residualvm/residualvm#1320]
Two people on the G+ group have reported that they cannot browse the filesystem on Android Nougat.
I strongly suspect that this is due to a permissions problem.

**Comment by klusark** [comment]
I can reproduce this. We may want to switch to how ScummVM does android now using SDL. I'll take a look if I have time soon.

**Comment by ilopez85** [comment]
Any news about this issue?
