### ISSUE TITLE
MYST3: v1.2 German

### ISSUE THREAD

**Issue by andrews05** [residualvm/residualvm#1323]
I've had a report from someone using v1.2 German where ResidualVM isn't recognising the game. The md5 for GERMAN.m3u is: d54e25526fc1de55f405f87cef74fafe

**Comment by bgK** [comment]
Hi,

ResidualVM requires the md5 of the first 5000 bytes of the file. Is this the md5 of the full file, or the one outputted by ResidualVM in the "unknown game version" message ?

**Comment by andrews05** [comment]
Oh whoops, that's the full file. I'll get back to you...

**Comment by andrews05** [comment]
MD5 of first 5000 bytes is: 1b2fa162a951fa4ed65617dd3f0c8a53

I also have md5 for v1.2 Italian: 906645a87ac1cbbd2b88c277c2b4fda2

**Comment by bgK** [comment]
Thanks. Now we're just missing the Spanish and Polish v1.2 versions.

**Comment by andrews05** [comment]
Great, thank you!

**Comment by goodoldgeorge** [comment]
Myst III: Exile Spanish v1.2

SPANISH.m3u size: 2599818 bytes
MD5 of first 5000 bytes is: 1404b50c36516bf48e4d2cb00c5982bc

**Comment by bgK** [comment]
Thanks.

**Comment by goodoldgeorge** [comment]
Sorry, here is the real hash value
[SPANISH.m3u.txt](https://github.com/residualvm/residualvm/files/782229/SPANISH.m3u.txt)

Myst III: Exile Spanish v1.2
SPANISH.m3u size: 2599818 bytes
MD5 of first 5000 bytes is: 28003569d9536cbdf6020aee8e9bcd15

**Comment by goodoldgeorge** [comment]
yesterday first i opened another logfile. I corrected my mistake in GitHub, but the corrected values did not seem on your side.
Sorry again :(

**Comment by bgK** [comment]
Ok, don't sweat it. The safe way to get those values is from the log file / console output when trying to add an unrecognized game version.
