### ISSUE TITLE
STARK: Skip animations on Esc

### ISSUE THREAD

**Issue by timfel** [residualvm/residualvm#1324]
The original game skipped forward over animations when you pressed escape. Right now, the engine only skips videos and speech.

I tried to understand how the `getMillisecondsPerGameloop` influences how fast we go through animations, but I seem to missing something, because it seems to me that https://github.com/residualvm/residualvm/blob/13ad766b312f301c709f747451c3fa287fd69e4f/engines/stark/stark.cpp#L229 will just set the millisecondsPerGameloop near zero every time (because it looks like it basically sets it to `g_system->getMillis() - g_system->getMillis()`). So my intuition to just bump the millisecondsPerGameloop variable one time when you press escape so that animations will skip ahead a little further didn't work.

**Comment by bgK** [comment]
This has been implemented, but please keep in mind TLJ is not supported yet. We don't accept bugs except blockers for now.
