### ISSUE TITLE
EMI: Crash after weeding at Lava Pool during sequence

### ISSUE THREAD

**Issue by middletonlord** [residualvm/residualvm#1325]
ERROR: DC Value went out of bounds: -55119!

**Comment by klusark** [comment]
Would it be possible to provide a save game near the issue?

**Comment by middletonlord** [comment]
Think the efmi001 - copy.gsv is the one. I decided to watch the movie sequence on YouTube and skipped it in the game. Also found that the end of act III movie sequence crashed too, The game freezes about 20 secs in and then stays there. I force closed ResidualVM watched the movie sequence on-line and skipped it again. Think that efmi001.gsv might crash at this point. see dos screen error


[cid:2853b251-b905-4fee-b30d-8445429b30c1]


________________________________
