### ISSUE TITLE
GUI: Buttons are inactive as the cursor is over them

### ISSUE THREAD

**Issue by Trillien** [residualvm/residualvm#1347]
Hello,

I run ResidualVM 0.3.0 (built of June 3rd 2017) on a Raspberry Pi3 via RetroPie 4.2.
At the GUI, as I move the cursor on the button _Add Game..._ there is no change of the color indicated the mouse is over the button. Additionally there is no reaction when I click the button (same for all the buttons).
Actually, the button _Add Game..._ becomes active as the cursor is at the bottom of the R of ResidualVM logo. So I guess the screen resolution doesn't match the input event window (if we can call it like that...). This last seems smaller and shifted to the top-left of the screen.

Please let me know if you need logs or additional info on this issue.
Trillien

**Comment by Botje** [comment]
Can you replicate this outside of RetroPie? ie. boot to a regular desktop environment and try it there.
Does it happen in both windowed and fullscreen modes?
My first thought is that SDL2 is the culprit here, but we'll have to dig deeper.

**Comment by Trillien** [comment]
I've just install PIXEL environment for raspbian (based on LXDE) and run `startx`.
I then run ResidualVM from a console and obtain the error:
`pi@RetroPie:./residualvm`
`WARNING: Error: Invalid renderer!`
I see very briefly a window edge blinking and disappearing.
I obtain the same result by double-clicking on residualvm icon to execute it through the file explorer.
So I couldn't obtain a windowed instance of ResidualVM.
(same result with ScummVM)

However I investigate on the screen resolution parameter for ResidualVM (in fullscreen mode). It appears the drift is the smallest at 640x480... but still there.

**Comment by Botje** [comment]
I don't own a Raspberry Pi myself, but you might fix the renderer error by increasing the video ram size, the default Raspbian is 64MB. Other than that, no idea..

**Comment by Trillien** [comment]
I had the idea to slightly change the arguments of `./configure` before the compilation.
I set up Netbeans (on a Windows 7 pc) and first try to compile with the exact configuration as RetroPie does:
```
CXXFLAGS=" -I/opt/vc/include"
LDFLAGS=" -L/opt/vc/lib"
./configure --enable-opengl-shaders --enable-vkeybd --enable-release --disable-debug --enable-keymapper --force-opengles2
```

I used a remote compilation thanks to my Raspberry Pi3 (GCC 4.9.0)
As I compared the compilation results between command lines on a console and Netbeans instructions (on Windows), I never got the same _residualvm_ executable. That's a shame I couldn't overcome this point even with the exact copy of the command line on Netbeans...
However, I then compared both the config.mk issued from `./configure` and found a main difference on LIBS line.

Here is the config.mk generated from the command line (identical to RetroPie script output)
`LIBS += -L/usr/local/lib -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2 -lm   -lvorbisfile -lvorbis -logg  -lmad  -lasound  -ljpeg  -lpng -lz  -ltheoradec  -lz  -lmpeg2 -lfreetype -lGLESv2`
[https://paste.ubuntu.com/24818707/](https://paste.ubuntu.com/24818707/)

Here is the config.mk generated after Netbeans pre-build instruction
`LIBS += -L/usr/lib/arm-linux-gnueabihf -lSDL -lm   -lvorbisfile -lvorbis -logg  -lmad  -lasound  -ljpeg  -lpng -lz  -ltheoradec  -lz  -lmpeg2 -lfreetype -lGLESv2`
[https://paste.ubuntu.com/24818730/](https://paste.ubuntu.com/24818730/)

I notice a change on SDL library. One defines SDL, the other SDL2.
And I don't encounter the issue I describe previously with _residualvm_ executable using SDL.

**Comment by Botje** [comment]
That is some excellent detective work!
We recently switched to SDL2 for more platform support, so it'd be good to have this working on your Pi too.
In the RetroPie case, which version of libSDL2 is installed? Can you try updating that to a more recent version?

**Comment by Trillien** [comment]
I noticed the bug with SDL2-2.0.2
I then installed manually SDL2-2.0.5 and compiled ResidualVM once more.
No improvement.

**Comment by aquadran** [comment]
Is the issue still valid?
