### ISSUE TITLE
MYST3: Add support for hebrew version

### ISSUE THREAD

**Issue by BLooperZ** [residualvm/residualvm#1348]
Hello,
I would like to add support for hebrew version of Myst III
Couldn't find documentation about reporting checksums for ResidualVM,
so checksums assumed as recommended for ScummVM (by md5deep with size 5000)

It seems the needed datafiles to recognize this version are:
bin\M3.exe - 7a4eaea5f19f621e05e732d657c15fe3
M3Data\TEXT\ENGLISH.m3t - 9bdc05c61d4a67d0f51b10bd4464c64d
M3Data\TEXT\HEBREW.m3u - 16fbbe420fed366249a8d44a759f966c

Thanks for all the amazing work!

**Comment by bgK** [comment]
I wasn't aware there was an Hebrew version. Let's try to make it work. I have a few questions you need to answer before I can add a detection entry since it is a new language.
1. Does the in-game menu allow to select the language? Ie switch between Hebrew and English? Or between Hebrew and more languages?
2. Is there a `HEBREW.m3t` file in `M3Data\TEXT`?
3. Are there fonts in `M3Data\TEXT`? Which ones? What is the mapping between the font file name and the font name (eg `arir67w.ttf` => `Arial Narrow`)?
4. What is the `M3.exe` version? (documentation purposes only)
5. What exactly is translated? Menus? In game text? Subtitles? Speech?

**Comment by BLooperZ** [comment]
Thank you for your very quick response,

1. the game do not allow changing the language.
2. no
3. arir67w.ttf => Arial Narrow Bold
    GIFFRD-H.TTF => GiffordsHand
    MacFonts.suit (How to check?)
4. I should say hebrew version has 4 CDs + patch CD, this is after the patch.
    the game says Version 1.2 (164)
5. Menus, In game text (letters etc. - also appears from right to left as it should be in hebrew) and subtitles are translated.
   The speech remains english

**Comment by bgK** [comment]
Thanks for your answers. I have added a detection entry for your version, it will be available in the next daily build.

A few more changes will probably be  required to make it work perfectly. Can you please report any bug you notice here, including the error messages generated by ResidualVM?
I suspect the game uses a system font to render the subtitles. Can you try enabling the subtitles? ResidualVM will probably generate an error indicating the which font mapping needs to be added.

Are the subtitles rendered from right to left in the original engine?

**Comment by goodoldgeorge** [comment]
Wrong filename in detection.cpp:

// Hebrew release (Hebrew only) (1.2 - Patched using the patch CD)
	MYST3ENTRY(Common::HE_ISR, "HEBREW.m3t",  "16fbbe420fed366249a8d44a759f966c", 0, kLocMonolingual) // #1348, BLooperZ
 
Sorry, but the Real filename is 'HEBREW.m3u' not 'HEBREW.m3t'

**Comment by bgK** [comment]
Right, thanks, this is fixed.

**Comment by aviloria** [comment]
First of all thanks a lot for adding this "Myst III - Exile" (HE) version...

I have added the content of the 4 CD's patched with patch 1.2 CD, but after running the game, and selecting "New game" option, the game halted... The console output can be seen here:
```
User picked target 'myst3-win-he' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
INFO: OpenGL Vendor: NVIDIA Corporation
INFO: OpenGL Renderer: GeForce GTX 460/PCIe/SSE2
INFO: OpenGL Version: 4.5.0 NVIDIA 382.53
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
INFO: GLEW Version: 1.13.0
INFO: GLSL version: 4.50 NVIDIA
WARNING: Too much metadata, skipping!
Initializing OpenGL Renderer
Unknown subtitles font face 'Arial2'!
```

I've been looking for an "Arial2" font in the 4+1 CDs, but I have no success.

**Comment by bgK** [comment]
`Arial2` uh. Oh well. I have added a font mapping for `Arial2` as `hebrew.ttf`.
Users of the Hebrew version should provide a true type font file named `hebrew.ttf` with Hebrew glyphs in the directory where the game files are stored.
For now, the subtitles will not render right to left, but the game should no longer error out.

**Comment by aviloria** [comment]
Wow! That was really quick! Thanks for the fix!

**Comment by BLooperZ** [comment]
Thank you for adding support so quickly,
in-game text and menus seem to work great.

I have tested the game, with and without adding "hebrew.ttf" (arir67w renamed)
may have done something wrong because I got the same result.

the subtitles are in [the familiar] wrong-encoding gibberish,
I think encoding with "windows-1255"[1] might fix this, and also fix rendering right to left,
because punctuation apppears at the left side of the sentence already

alternatively, this can be explained if the publisher has wrote the subtitles backwards,
it was pretty common (called visual hebrew)
in this case encoding might be ISO-8859[2]

[1]https://en.wikipedia.org/wiki/Windows-1255
[2]https://en.wikipedia.org/wiki/ISO/IEC_8859-8

**Comment by bgK** [comment]
How strange. The game engine does have support for cp1255, but maybe it was not used and something else was hacked in for the Hebrew subtitles.
Can you post a screenshot of what it currently looks like in ResidualVM?

Also, if the `arir67w.ttf` shipped with the Hebrew version is the same as the one shipped with the other versions of the game, then it does not contain the Hebrew characters, and cannot be used. You need a proper Hebrew True Type font. Maybe use Arial from your system, or GNU Free Sans.
It's also curious the game works without a file named "hebrew.ttf" .. if it is the same version as @aviloria, it should quit with an error.

**Comment by aviloria** [comment]
At first I tried some hebrew opensource fonts, but finally I used M3Data\TEXT\GIFFRD-H.TTF renamed to HEBREW.TTF... maybe it helps

**Comment by bgK** [comment]
@aviloria And what does it do with `GIFFRD-H.TTF`? That font does not seem to have the Hebrew characters either.

**Comment by BLooperZ** [comment]
both fonts are exactly the same as the other versions.
and you're right, both do not contain hebrew characters.
very strange.

here is a screenshot
![screen](https://user-images.githubusercontent.com/10459948/27226124-273a5d78-52a6-11e7-82db-f4e06dc91061.png)
> ?עוצר נשימה, הלא כן

(I wrote the question mark before the sentence logically, to make it appear visually correct)
note the question mark does appear correctly on the left in the game

**Comment by BLooperZ** [comment]
trying to check again with clean installation...
when copying files from CDs directly, the game does search for 'hebrew.ttf'
the font does change (tried bold & italic to see it) but the encoding issue remains.

more files information:
ENGLISH.m3t (before patch) - 8a49e0fa5db56689434ea7cc1be0b1a3
HEBREW.m3u do not change by the patch (same checksum for whole file)
M3.exe (before patch) bcb347db5176e5d1a00dc378b4cac478

trying to check if there is any difference when actually installing

**Comment by bgK** [comment]
Thanks, using the screenshot, it seems the subtitles are indeed encoded in cp1255, but the encoding value does not seem to be set to the appropriate value in the game data files. I have forced the value in ResidualVM.
The next daily build should fix the characters. However, the text will still be rendered left to right. Right to left rendering will require more work as it is not supported by the font module in ScummVM.

Only `HEBREW.m3u` is used for the detection in ResidualVM, so the unpatched version should be detected as well.

**Comment by aviloria** [comment]
well.. I made a mistake suggesting GRIFFRD-H.TTF..., the one I'm using is this one: http://www.fonts2u.com/web-hebrew-ad.font

**Comment by BLooperZ** [comment]
Thanks, now the hebrew characters are rendered without needing 'hebrew.ttf'
(altough it is nice to be able to replace the subtitles font, as a feature :) )

**Comment by bgK** [comment]
Right, if the font requested by the game is not found then the GUI font from ResidualVM is used. It must have the Hebrew characters.

I've made a new change that should make the subtitles render from right to left. Please check it works properly so that this issue can be closed.

**Comment by BLooperZ** [comment]
Thank you,
now the subtitles render from right to left but first character is missing in some sentences

**Comment by bgK** [comment]
Ok, can you give me an example? I literally don't understand what I'm doing.

**Comment by BLooperZ** [comment]
for example:
the sentence
> .כי איננו צריכים לשחזר את העיר כמו שתכננו
appears as
> .י איננו צריכים לשחזר את העיר כמו שתכננו
(from the intro)

note the missing 'כ'
few sentences appear correctly (with the first letter), 
couldn't find what common between them yet

**Comment by bgK** [comment]
Thanks. I've been able to track down and fix the issue. Hopefully tomorrow's daily build will be working perfectly.

**Comment by BLooperZ** [comment]
Thank you,
all seem to be working correctly.

**Comment by bgK** [comment]
Thanks for your help.
