### ISSUE TITLE
MYST3: Sound of electricity is absent when the puzzle with the generator is passed. Voltaic.

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1349]
There is no sound of electricity when the puzzle with the generator is passed. The sound of elecricity appears when you step aside.
[Save.zip](https://github.com/residualvm/residualvm/files/1145720/Save.zip)

**Comment by ctoroman** [comment]
In the original game, the sound appears immediately after solving the puzzle

**Comment by bgK** [comment]
The other issue you created, #1337 has a nicer number. I'll close this one.
