### ISSUE TITLE
MYST3: Some sound issues in Voltaic

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1350]
Lava room: (save2.zip)
We hear the sound of lava. When we lower the platform down, the lava goes away, and the sound of the lava remains. If you take a step to the side, the sound of the lava disappears. 
When you raise the platform again, there is no lava sound, the sound appears when stepping aside. (save5.zip)

The same is true for the platform in the lava room (save3.zip, save4.zip)

The four wheel valves: (save6.zip)
All valves are closed. There is no sound of air. We rise to the next floor. The valves are open, but there is still no sound of air. The sound appears when we begin to close the valves.

It's the same when the valves are open, there is air sound. We go down to the floor below, where the valves are closed, the sound of air is still there. The sound of air disappears when we start to open the valves.

The airship: (save8.zip)
From below is a river. There is no sound of water. The sound appears when we sit in the ship and move the handle.

P.S.  These issues are similar to #1349, as it seems to me.

[save2.zip](https://github.com/residualvm/residualvm/files/1154706/save2.zip)
[save3.zip](https://github.com/residualvm/residualvm/files/1154715/save3.zip)
[save4.zip](https://github.com/residualvm/residualvm/files/1154714/save4.zip)
[save5.zip](https://github.com/residualvm/residualvm/files/1154716/save5.zip)
[save6.zip](https://github.com/residualvm/residualvm/files/1154750/save6.zip)
[save8.zip](https://github.com/residualvm/residualvm/files/1154749/save8.zip)

**Comment by bgK** [comment]
Thanks for the report, this is now fixed, the ambient sounds are now properly refreshed. #1337 was caused by the same issue. I'm a bit sad to have to close an issue with such a nice number.

I'm pretty sure the airship / no sound of water case is normal. The sound of water seems to come from the waterfall, and not from the river below.

**Comment by ctoroman** [comment]
Many thanks! But what's wrong with this number? Why is it nice?

**Comment by Diskutant** [comment]
@ctoroman 
https://en.wikipedia.org/wiki/Leet
http://www.urbandictionary.com/define.php?term=1337
