### ISSUE TITLE
MYST3:  The lift handle does not work smoothly. J'nanin.

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1351]
Effect as on the attached video is observed, if the parameter "transition_speed" is set to default (50).
If the parameter "transition_speed" is set to 99 (max), then it is displayed normally, but the movements in the game become too fast, not smooth.

I have already indicated this earlier, #1311, but not yet fixed. If it can be fixed at all... 

[video1.zip](https://github.com/residualvm/residualvm/files/1161053/video1.zip)

**Comment by ctoroman** [comment]
Game I launch by reference (in the archive). There is also my ini file. I realized that if you run the game from Far manager, then everything works fine. If I run through explorer, or Total Commander, we see what's on the attached video. (video1.zip)

[Myst3_ini_lnk.zip](https://github.com/residualvm/residualvm/files/1175644/Myst3_ini_lnk.zip)

P.S. bgK, can you tell me, please, how to properly run the game so that this effect is not observed? How do you start this game?

**Comment by bgK** [comment]
Can you please check if the vsync option in ResidualVM affects this issue?

**Comment by ctoroman** [comment]
Just checked. The option does not affect.

**Comment by ctoroman** [comment]
The same is observed on ResidualVM v.0.2.1

**Comment by dafioram** [comment]
I also observed this while playing. Ubuntu 17.04  on 020e09bce602806ae7dca112e0c356365645e383 ( Sep 3). If you go into the lift and then pull the handle it shows the animation correctly. Don't know if its in the original or not. It doesn't seem to happen in this [youtubers](https://youtu.be/xWZ1B0CFrjI?list=PLjjNZRzFam-rtCd3i0uTy5M7nMr9WMhSV&t=966) playthrough.

**Comment by ctoroman** [comment]
Wow!  Many thanks!!!    :)
