### ISSUE TITLE
Myst III unable to open archive TOHOnodes.m3a

### ISSUE THREAD

**Issue by thomasj041** [residualvm/residualvm#1354]
My first issue I've encountered that won't let me play the game.

**Comment by bgK** [comment]
When reporting problems, you want to provide as much information as you can to help narrow down the issue. Also be aware that the ResidualVM forums are better suited for user assistance. Github issues are mostly for bug reports.

So ... do you have a file named TOHOnodes.m3a, is in a location where ResidualVM can find it as per the documentation? http://wiki.residualvm.org/index.php/Datafiles
