### ISSUE TITLE
EMI: I cannot load my saved game

### ISSUE THREAD

**Issue by lsenecaux** [residualvm/residualvm#1357]
ResidualVM v0.3 (08/21/2017)
EMI v1.1

When I load my saved game, residualVM crash and return to Windows.

Here are my logs

Thanks 
[residualvm.log.txt](https://github.com/residualvm/residualvm/files/1272011/residualvm.log.txt)

**Comment by bgK** [comment]
It would be useful if you attached the saved game that fails to load.

**Comment by lsenecaux** [comment]
Here is the saved game
Thanks
[efmi001.zip](https://github.com/residualvm/residualvm/files/1272059/efmi001.zip)

**Comment by mparnaudeau** [comment]
@lsenecaux Your saved game crash here 0.4.0-git2cad855 with that:

```
GrimEngine::savegameRestore() started.
WARNING: Could not find sprite fx/paper_smalld.sprb!
WARNING: Could not find animation joj/joj_mk_fail.anim!
WARNING: Could not find sprite fx/up_arrow_small.sprb!
WARNING: Could not find sprite fx/down_arrow_small.sprb!
residualvm: engines/grim/lua/lrestore.cpp:179: void Grim::recreateObj(Grim::TObject *): Assertion `found' failed.
Abandon (core dumped)
```

Note that when we start EMI, a dialog says ""WARNING: The game you are about to start is not yet fully supported by ResidualVM. As such, it is likely to be unstable, and any saved game you make might not work in future versions of ResidualVM."

I don't know if it's concretely the case. I experienced crashes about save/restore operations playing with fullscreen and windowed modes. So there is certainly some work on this topic.
