### ISSUE TITLE
MYST3: Red bar to the left of the elevator knob. J'nanin

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1358]
When you call the elevator and move the handle, a red bar appears to the left of it.

[save1.zip](https://github.com/residualvm/residualvm/files/1272970/save1.zip)

**Comment by dafioram** [comment]
Can you add a pictures of the before and after the red bar is present?

**Comment by ctoroman** [comment]
Here are these pictures.

![screen1](https://user-images.githubusercontent.com/22292375/30594540-02e62a8a-9d81-11e7-99ca-04bd5eabade8.jpg)
![screen2](https://user-images.githubusercontent.com/22292375/30594554-08fea208-9d81-11e7-9f83-b44ae618fa91.jpg)

**Comment by bgK** [comment]
ffmpeg seems to decode that video correctly, it's probably a bug in ResidualVM's Bink decoder

**Comment by ctoroman** [comment]
But in fact before it was not. Appeared about a month ago.
