### ISSUE TITLE
MYST3: Looking around spins wildly

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1359]
residualvm: 0.3.0git-020e09bc
OS: Ubuntu 16.04 64-bit
Game: Myst 3 DVD v1.27

When the hand is locked in-front If I look around the view spins wildly. I started a new game. It doesn't matter if I am in full screen, widescreen mode, or windowed. Same result for sdl2 and sdl1.2. If I right click and move the hand around that works fine. If I open the GMM then the cursor also works fine there. I am on a vm if that matters. 

In the window it shows 
WARNING: [UnityTaskbarManager::addRecent] Not implemented!
WARNING: Unable to enable VSync: glXSwapIntervalMESA failed!
INFO: OpenGL Vendor: VMware, Inc.
INFO: OpenGL Renderer: Gallium 0.4 on SVGA3D; build: RELEASE;  LLVM;
INFO: OpenGL Version: 3.0 Mesa 17.0.7
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
Initializing OpenGL Renderer

**Comment by bgK** [comment]
Myst III uses the relative mouse movement information from SDL when looking around. This data is not used in ScummVM or in other ResidualVM games. It's likely you are hitting a bug related to your VM setup.

**Comment by dafioram** [comment]
I setup ubuntu on a laptop and myst3 works there without the erratic mouse behavior. Any idea what can be done to get it working on my linux vm? I did run myst3 using wine on the linux vm and I did also have mouse movement issues, but it was different. 

When I ran wine it was hypersensitive at all times (menus and in-game) while in residualvm it was only when looking around in game. The residualvm movements where much more sensitive than the wine one was, but both were unplayable.

**Comment by bgK** [comment]
Maybe try playing with the `pref.gamingMouseMode` setting in the VMWare configuration file.

**Comment by dafioram** [comment]
That didn't work, but I found that if I "claim" my mouse in the vm machine that that works. Claiming it takes it away from the host machine and uses it natively rather than emulating it from the host. 

Whats weird is that my windows vm doesn't have these issues and the way vmware is emulating works fine for that case (residualvm works fine in my windows vm). So I wonder if it is vmware's mouse emulation for linux that could be improved in the future or if it is something ubuntu is doing that it could improve upon.

Thanks.

**Comment by bgK** [comment]
I'm glad you got it working.
