### ISSUE TITLE
MYST3: Split background image when gmm menu is open

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1360]
![image](https://user-images.githubusercontent.com/5838258/30525175-f16cabba-9bcf-11e7-8670-06f75552f43f.png)
residualvm:  0.3.0git-020e09bc
OS: Ubuntu 16.04 VM and Ubuntu 17.04 laptop
Game: Myst3 dvd 1.27
It shows the bottom half of the background on top and the top half on the bottom.

Only happens for OpenGL renderer and player has to be in-game.

**Comment by bgK** [comment]
Your screenshot shows a git revision that is a few months old. Does it still happen with the current version?

**Comment by dafioram** [comment]
![screenshot from 2017-09-18 18-49-23](https://user-images.githubusercontent.com/5838258/30569558-95ece298-9ca9-11e7-909d-97d21892b511.png)

Actual Background:
![screenshot from 2017-09-18 18-50-13](https://user-images.githubusercontent.com/5838258/30569582-ad71813a-9ca9-11e7-8c0e-50f79683df70.png)

**Comment by bgK** [comment]
You might be interested in building with `libglew`, which disables the use of the legacy OpenGL code path which was affected by this bug.
