### ISSUE TITLE
MYST3: Issues when skipping animation for lower end machines

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1362]
residualvm: 0.3.0git-020e09bc
OS: UUbuntu 17.04 laptop
Game: Myst3 dvd 1.27

When I played on my ubuntu laptop I ran into serious issues once I skipped an animation. I can't reproduce this on more powerful windows computer so I believe it is because my ubuntu laptop has low specs, but I only run into issues if I skip animations.

If I skip an animation (using spacebar/esc) then all future animations will be automatically skipped. If I try to leave via esc I cannot, If I try to leave via the gmm and hit quit it doesn't leave, I then have to kill it by selecting the process id. So it has some locked resource not being freed when I skip an animation.

Specifically I have been using the lift in J'nanin, [A.zip](https://github.com/residualvm/residualvm/files/1309571/A.zip) to test this, and the blocker I then run into after skipping the lift animation is that if I go under the lift and spin the two wheels they continue to spin forever.

If you want to try some stuff on a branch I can build from that.

**Comment by bgK** [comment]
Interesting, the key release event does not seem to make its way to the main event loop. In the case of skipping videos it should be possible to work around it by consuming the keypress, but I'll look for a more general fix.
```diff
diff --git a/engines/myst3/myst3.cpp b/engines/myst3/myst3.cpp
index f0060078..cbaefe2b 100644
--- a/engines/myst3/myst3.cpp
+++ b/engines/myst3/myst3.cpp
@@ -1189,6 +1189,8 @@ void Myst3Engine::playSimpleMovie(uint16 id, bool fullframe, bool refreshAmbient
                // Handle skipping
                if (_inputSpacePressed || _inputEscapePressed) {
                        // Consume the escape key press so the menu does not open
+                       _inputSpacePressed = false;
+                       _inputEscapePressed = false;
                        _inputEscapePressedNotConsumed = false;
                        break;
                }
```
