### ISSUE TITLE
MYST3: Memory leak in createRenderer

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1365]
020e09bce602806ae7dca112e0c356365645e383

==17065== 1,920 bytes in 1 blocks are definitely lost in loss record 2,370 of 2,406
==17065==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17065==    by 0x6BED5B3: glXGetFBConfigs (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==17065==    by 0x6BEE8D1: glXChooseFBConfig (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==17065==    by 0x4EFEC11: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.1)
==17065==    by 0x4EF02BF: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.1)
==17065==    by 0x33B304: OpenGLSdlGraphicsManager::createOrUpdateGLContext(unsigned int, unsigned int, ResVmSdlGraphicsManager::GameRenderTarget) (openglsdl-graphics.cpp:306)
==17065==    by 0x33ACE3: OpenGLSdlGraphicsManager::createOrUpdateScreen() (openglsdl-graphics.cpp:174)
==17065==    by 0x33A99F: OpenGLSdlGraphicsManager::setupScreen(unsigned int, unsigned int, bool, bool) (openglsdl-graphics.cpp:117)
==17065==    by 0x32C97F: ModularBackend::setupScreen(unsigned int, unsigned int, bool, bool) (modular-backend.cpp:115)
==17065==    by 0x15ED7A: OSystem_SDL::setupScreen(unsigned int, unsigned int, bool, bool) (sdl.cpp:420)
==17065==    by 0x15EEB8: OSystem_SDL::launcherInitSize(unsigned int, unsigned int) (sdl.cpp:430)
==17065==    by 0x1624D3: setupGraphics(OSystem&) (main.cpp:292)

==17065== 1,920 bytes in 1 blocks are definitely lost in loss record 2,371 of 2,406
==17065==    at 0x4C2DB2F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17065==    by 0x6BED5B3: glXGetFBConfigs (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==17065==    by 0x6BEE8D1: glXChooseFBConfig (in /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1.2.0)
==17065==    by 0x4EFEC11: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.1)
==17065==    by 0x4EF02BF: ??? (in /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0.4.1)
==17065==    by 0x33B304: OpenGLSdlGraphicsManager::createOrUpdateGLContext(unsigned int, unsigned int, ResVmSdlGraphicsManager::GameRenderTarget) (openglsdl-graphics.cpp:306)
==17065==    by 0x33ACE3: OpenGLSdlGraphicsManager::createOrUpdateScreen() (openglsdl-graphics.cpp:174)
==17065==    by 0x33A99F: OpenGLSdlGraphicsManager::setupScreen(unsigned int, unsigned int, bool, bool) (openglsdl-graphics.cpp:117)
==17065==    by 0x32C97F: ModularBackend::setupScreen(unsigned int, unsigned int, bool, bool) (modular-backend.cpp:115)
==17065==    by 0x15ED7A: OSystem_SDL::setupScreen(unsigned int, unsigned int, bool, bool) (sdl.cpp:420)
==17065==    by 0x264853: Myst3::createRenderer(OSystem*) (gfx.cpp:191)
==17065==    by 0x269079: Myst3::Myst3Engine::run() (myst3.cpp:150)

**Comment by bgK** [comment]
Thanks, but that leak comes from SDL2. There is nothing we can do about it in ResidualVM.
