### ISSUE TITLE
MYST3: Laggy and subpar fullscreen when renderer is software

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1367]
residualvm: 0.3.0git-020e09bc
OS: Win7-64
Game: Myst3 dvd 1.27
[save.zip](https://github.com/residualvm/residualvm/files/1326608/save.zip)

When selecting fullscreen and having the renderer set to software the game is laggy and rather than make the viewing area of the game larger the fullscreen mode just adds more black area. Doesn't matter if I use  widescreen mode. The lag is still present for windowed play.

When the renderer is OpenGL everything works as expected.

Demo: https://streamable.com/z5ug8

**Comment by bgK** [comment]
Nowadays it is expected to have 3D hardware to play 3D accelerated games. The software renderer should not be used with Myst III. The legacy OpenGL and Shaders OpenGl renderers are much better.

**Comment by dafioram** [comment]
How do I build ResidualVM so that shaders work? During the ./configure process it says ... yes for the OpenGL shaders enabled line. I have glew installed.

**Comment by vpelletier** [comment]
> Demo: https://streamable.com/z5ug8

So it is smooth when fully inside the room, a bit laggy when just at the entrance (the part accessible before solving any puzzle) and very laggy outside ? This would point at the wave animation, which is expensive indeed. Does disabling it in the options (options -> game -> wave animation, or some localised version of it) improve speed ?

> When selecting fullscreen and having the renderer set to software the game is laggy

Is windowed different ? Software being slow is, as @bgK said, somewhat expected, but it being slower in full-screen (especially non-stretched) would be news to me - although I did not play much with fullscreen.

**Comment by dafioram** [comment]
If I play in windowed mode with software renderer with waves effects on it is laggy more so in front of the waves and if I turn off waves it is considerably less laggy, but there is still a noticeable delay between my clicking and the response as well as turning. 

Its even laggy at the main menu (esc).

The reason I did fullscreen was to show that most of my screen is filled with black rather then the game stretched.
