### ISSUE TITLE
MYST3: Hang when using shaders for Amateria double rotator puzzle

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1370]
Load saved game then grab one of the cylinder blockers that are in the slots then the game will hang.
If I run regular openGL it runs fine.
[save.zip](https://github.com/residualvm/residualvm/files/1335221/save.zip)
residualvm: a13e3f7bdd851c37b0782d6d29f588711adfb65c
game: myst 1.27 dvd
os: ubuntu 17.04

#0  0x00007ffff508143d in __lll_lock_wait ()
    at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007ffff507af0d in __GI___pthread_mutex_lock (mutex=0x555555e5ded0)
    at ../nptl/pthread_mutex_lock.c:80
#2  0x00007fffe96dd478 in  () at /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
#3  0x00007fffe942a906 in  () at /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
#4  0x00007fffe96cf5c4 in  () at /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
#5  0x00007fffe96dd42c in  () at /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
#6  0x00007fffe942a72d in  () at /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so
#7  0x00005555555bce84 in Myst3::ShaderRenderer::drawTexturedRect3D(Math::Matrix<3, 1> const&, Math::Matrix<3, 1> const&, Math::Matrix<3, 1> const&, Math::Matrix<3, 1> const&, Myst3::Texture*) (this=0x555555ebf920, topLeft=..., bottomLeft=..., topRight=..., bottomRight=..., texture=0x55555685b9d0)
    at engines/myst3/gfx_opengl_shaders.cpp:379
#8  0x000055555561cef6 in Myst3::Movie::draw3d() (this=0x555556a52fd0)
    at engines/myst3/movie.cpp:148
#9  0x000055555561cf2a in Myst3::Movie::draw() (this=0x555556a52fd0)
    at engines/myst3/movie.cpp:156
#10 0x000055555561d47a in Myst3::ScriptedMovie::draw() (this=0x555556a52fd0)
    at engines/myst3/movie.cpp:250
#11 0x00005555555b6c7b in Myst3::Renderer::renderDrawable(Myst3::Drawable*, Myst3::Window*) (this=0x555555ebf920, drawable=0x555556a52fd0, window=0x555556858300) at engines/myst3/gfx.cpp:238
#12 0x00005555555c1985 in Myst3::Myst3Engine::drawFrame(bool) (this=
    0x55555669c490, noSwap=false) at engines/myst3/myst3.cpp:689
#13 0x00005555555bfc6f in Myst3::Myst3Engine::run() (this=0x55555669c490)
    at engines/myst3/myst3.cpp:209
#14 0x00005555555a3576 in runGame(EnginePlugin const*, OSystem&, Common::String const&) (plugin=0x555555f721b0, system=..., edebuglevels=...)
    at base/main.cpp:264
#15 0x00005555555a4528 in scummvm_main(int, char const* const*) (argc=1, argv=0x7fffffffe018) at base/main.cpp:531
#16 0x00005555555a178a in main(int, char**) (argc=1, argv=0x7fffffffe018)
    at backends/platform/sdl/posix/posix-main.cpp:45

**Comment by bgK** [comment]
That looks like a crash in the WMware guest GL driver to me. I can't reproduce it using native Linux + mesa RadeonSI driver. ApiTrace shows no GL error.
The mesa developers might be interested in it if it still reproduces using the latest version and you can provide them with an ApiTrace trace.

**Comment by dafioram** [comment]
I didn't encounter this issue on my linux laptop (rather than the vm) when using shaders.
