### ISSUE TITLE
MYST3:  Сlicks when playing background music

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1371]
Tester: Win10 x64
ResidualVM 0.3.0git9484bbdd

**Comment by bgK** [comment]
Do you have more details about how to reproduce this?

**Comment by ctoroman** [comment]
You can just stand and do nothing, wait for the musical fragment to sound. In any era. During the sound of music, clicks will be heard. Like on a vinyl record.

**Comment by bgK** [comment]
Interesting. I suspect resampling is needed for some reason on your system, and that it introduces glitches. Can you try adding the following setting to your `residualvm.ini` file?
```ini
[residualvm]
output_rate=48000
```

48KHz is the standard output rate for modern systems. ResidualVM defaults to 44.1KHz. If that does not fix the issue, do you mind making an uncompressed recording ?

**Comment by ctoroman** [comment]
Just checked on Win 7 x64. There are no clicks. Perhaps there is issue in sound driver in Win 10. Or sound card.
