### ISSUE TITLE
MYST3: Easter Eggs issue

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1373]
Easter eggs in the game works only with the English keyboard layout (press "~"). On a different layout, they do not work. 
   In the original game, the keyboard layout does not change and the eggs always work.

**Comment by bgK** [comment]
Are you using Linux/X11?

**Comment by ctoroman** [comment]
No. I'm use Windows

**Comment by ctoroman** [comment]
Сan you fix it? After all, when you save a game, the keyboard layout does not change, it remains in the same language. But to turn on Easter eggs, sometimes you have to press alt + shift. In the original game, do not do this. Thanks.
