### ISSUE TITLE
MYST3: Assertion on game start

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1374]
ResidualVM 0.4.0git (Nov 22 2017 20:37:56)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

I don't reach any game screen, everything stays black and i get this assertion in the console.

Mouse shown 0
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
User picked target 'myst3-win' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
Initializing OpenGL Renderer
WARNING: GL_ARB_texture_non_power_of_two is not available.!
assertion "rgbaFormat == Graphics::PixelFormat(4, 8, 8, 8, 8, 0, 8, 16, 24)" failed: file "engines/myst3/myst3.cpp", line 1375

Myst III Exile (Windows/English)

AmigaOS4 - PPC -SDL - BE

**Comment by bgK** [comment]
Sorry about that.

Would you mind doing a bit of big endian testing for Myst III (Running a bit around / saving - loading games should be enough)? There have been quite some changes in that area.

**Comment by raziel-** [comment]
No need to apologize.

And i'll certainly test it out.
Doing dome OpenGL testing on my platform anyway.

Thank you for the fix

**Comment by raziel-** [comment]
@bgK

Not trying to spam this report, but did you get my eMail?

**Comment by bgK** [comment]
no, and it's not in spam either

**Comment by raziel-** [comment]
Resent to your handle at scummvm org
