### ISSUE TITLE
MYST3: DVD version 1.27 - Hash unknown

### ISSUE THREAD

**Issue by lmerckx** [residualvm/residualvm#1375]
Game: Myst III
Language: Multiple
Version: DVD - Version 1.27 for Windows 95 / 98 / ME / XP, Mac OS 8.1 or 9.1 or OS 10.1

The game in '/recalbox/share/roms/scummvm/Myst 3 - Exile.scummvm' seems to be unknown.
Please, report the following data to the ResidualVM team along with name
of the game you tried to add and its version, language, etc.:

{"RSRC.m3r", 0, "a2c8ed69800f60bf5667e5c76a88e481", 1223862},
{"ENGLISH.m3t", 0, "74726de866c0594d3f2a05ff754c973d", 3407120},

**Comment by bgK** [comment]
That means you are missing a [language].m3u file from the DVD. Please refer to the readme for instructions.

I've patched ResidualVM so this warning is not shown when users forget to copy that file.

**Comment by lmerckx** [comment]
I already put the language file, but I named it language.m3u.
The right name should be FRENCH.m3u in my case.

Thank you for your help.
