### ISSUE TITLE
LAUNCHER: Crash when using "Edit Game" on self inflicted broken(?) entry

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1376]
ResidualVM 0.4.0git (Nov 26 2017 11:58:25)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

For more info, please also see https://bugs.scummvm.org/ticket/10334 as this seems to stem from the ScummVM source, except the crash, that one is a residualvm original ;-)

Preliminaries:
I only have one entry for Myst III in my residualvm.ini, which looks like this:

[myst3-win]
description=Myst III Exile (Windows/English)
widescreen_mod=true
path=Games:GamesVM/Cyan Productions/Exile/
gameid=myst3
language=en
platform=windows
guioptions=sndNoSubs sndNoSpeech sndNoSFX sndNoMIDI gameOption1 lang_English

Steps to reproduce:
1) Go to your console
2) Type "residualvm myst3" (note that i have made a mistake by not using the correct game ID which would be "myst3-win"
3) residualvm will print the following on the console:

WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
User picked target 'myst3' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
WARNING: Myst III Engine failed to instantiate engine: Path does not exist (target 'myst3', path '')!
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8

4) Ok, now i'm getting a window telling me the same again:
Error running game: Path does not exist

5) Now i'm in the Launcher with a incorrectly added new entry of Myst 3.
The bad part starts when i try to Edit that entry.

6) Click on the new entry
7) Click on Edit game (instant crash)

(As i have written in the scummvm report, it does not crash in scummvm for some reason)

I added the info about the initial scummvm bug report on top of this issue report, so you guys can maybe work together on this?

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 5.3.0) 5.3.0

Crashlog:

[HAL_DfltTrapHandler] *** Warning: Fatal exception in task 0x4B2AC060 (Shell Process, etask = 0xDFC71F10) at ip 0x7F0BDDB4
Dump of context at 0xDFC6BBA0
Trap type: DSI exception
Machine State (raw): 0x100000000200B030
Machine State (verbose): [Hyper] [ExtInt on] [Super] [FPU on] [IAT on] [DAT on]
Stacktrace:
#0: 0x7F0BDDB4
#1: 0x7F084F34
#2: 0x7F0DAC20
#3: 0x7F0C2C30
#4: 0x7F0CE820
#5: 0x7F0C2690
#6: 0x7F0C04F4
#7: 0x7F0D9ED4
#8: 0x7F072C80
#9: 0x7F079AF0
#10: 0x7F07A838
#11: 0x7F0C2690
#12: 0x7F0BEC04
#13: 0x7F073504
#14: 0x7F0764F0
#15: 0x7F075558
#16: 0x7F072C90
#17: 0x7EEAF7D4
#18: 0x7EEB1898
#19: 0x7EEAF504
#20: in module newlib.library.kmod+0x000020A4 (0x0227F404)
#21: in module newlib.library.kmod+0x00002D0C (0x0228006C)
#22: in module newlib.library.kmod+0x00002EE8 (0x02280248)
#23: 0x7EEAC398
#24: in module dos.library.kmod+0x000255C8 (0x02172CC8)
#25: in module kernel.debug+0x0006E9C0 (0x0206E9C0)
#26: in module kernel.debug+0x0006EA08 (0x0206EA08)
#27: 0x00000000

Crashed process: residualvm (0x4B2AC060)
DSI verbose error description: Access not found in hash or BAT (page fault)
Access was a load operation
 0: 7F084F34 5D3ED730 ABADCAFE 00000000 00000000 4F4D4944 00000000 4F4D4944
 8: 00000000 00000000 00000072 5D3ED750 000007A8 61DCB2C0 00000000 4B0F2340
16: 7EEAF2D8 00000000 60AD3010 61D92700 02B30000 02B30000 00000000 00000006
24: 6FF8C180 5D2E4298 00000001 5D2E4298 00000001 00000001 00000000 5D3ED730
CR: 55953933   XER: 8000007E  CTR: 022AB334  LR: 7F084F34
DSISR: 40000000  DAR: 0000006C

FP0 : FFF8000082004000 3FE99999A0000000 3FF0000000000000 0000000000000000
FP4 : 3FF0000000000000 0000000000000000 C000000000000000 4000000000000000
FP8 : BFF0000000000000 BFF0000000000000 3FE3333340000000 4330000080000000
FP12: 4070000000000000 4330000080000280 0000000000000000 0000000000000000
FP16: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FP20: 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FP24: 406FE00000000000 41E0000000000000 3EF0000000000000 4330000080000000
FP28: 40F0000000000000 4330000000000000 40F0000000000000 41E0000000000000
FPSCR: 82004000
HID0: 0x8000000000000000  HID1: 0x000000005CE993B1
HID4: 0x4400240000080180  HID5: 0x0000006600000080

V0 : 00000000000000000000000000000000 00000000000000000000000000000000
V2 : 01010101FF99CC99FF99CC99FFDBDBDB 00000000000000000000000000000000
V4 : DA25DA25DA25DA25DA25DA25DA25DA25 FE01DA25FE01DA25FE01DA25FE01DA25
V6 : 00000000010101010202020203030303 FF000000FF000000FF000000FF000000
V8 : 001002120414061608180A1A0C1C0E1E FFDBDBDBFFDBDBDBFFDBDBDBFFDBDBDB
V10: 01000100010001000100010001000100 00000000000000000000000000000000
V12: 00000000000000000000000000000000 00000000000000000000000000000000
V14: FFDBDBDBFFDBDBDBFFDBDBDBFFDBDBDB FE01DA25FE01DA25FE01DA25FE01DA25
V16: DB25DB25DB25DB25DB25DB25DB25DB25 00000000000000000000000000000000
V18: FF01DB25FF01DB25FF01DB25FF01DB25 DA25DA25DA25DA25DA25DA25DA25DA25
V20: 00000000000000000000000000000000 00000000000000000000000000000000
V22: 00000000000000000000000000000000 00000000000000000000000000000000
V24: 00000000000000000000000000000000 00000000000000000000000000000000
V26: 00000000000000000000000000000000 00000000000000000000000000000000
V28: 00000000000000000000000000000000 00000000000000000000000000000000
V30: 00000000000000000000000000000000 00000000000000000000000000000000
VSCR: 00000000 VRSAVE: 00000000

Disassembly of crash site:
 7F0BDDA4: 907F0008   stw               r3,8(r31)
 7F0BDDA8: 7C892378   mr                r9,r4
 7F0BDDAC: 993F000C   stb               r9,12(r31)
 7F0BDDB0: 813F0008   lwz               r9,8(r31)
>7F0BDDB4: A129006C   lhz               r9,108(r9)
 7F0BDDB8: 552A07FE   rlwinm            r10,r9,0,31,31
 7F0BDDBC: 893F000C   lbz               r9,12(r31)
 7F0BDDC0: 7F8A4800   cmpw              cr7,r10,r9
 7F0BDDC4: 419E0054   beq-              cr7,0x7F0BDE18
 7F0BDDC8: 893F000C   lbz               r9,12(r31)

Kernel command line: serial munge debuglevel=1

Registers pointing to code:
r0 : [gui/options.cpp:912] residualvm:_ZN3GUI13OptionsDialog20setMIDISettingsStateEb()+0x9c (section 1 @ 0x1DDF10)
r13: residualvm:_ZN4GrimL14smushDestTableE()+0x130e (section 23 @ 0x796C)
r16: residualvm:main()+0x0 (section 1 @ 0x82B4)
r20: native kernel module graphics.library.kmod+0x00828da0
r21: native kernel module graphics.library.kmod+0x00828da0
r26: module SYS:Utilities/MultiView at 0x00000001 (section 0 @ 0xFFFFFFDC)
r28: module SYS:Utilities/MultiView at 0x00000001 (section 0 @ 0xFFFFFFDC)
r29: module SYS:Utilities/MultiView at 0x00000001 (section 0 @ 0xFFFFFFDC)
ip : [gui/widget.cpp:188] residualvm:_ZN3GUI6Widget10setEnabledEb()+0x24 (section 1 @ 0x216D90)
lr : [gui/options.cpp:912] residualvm:_ZN3GUI13OptionsDialog20setMIDISettingsStateEb()+0x9c (section 1 @ 0x1DDF10)
ctr: native kernel module newlib.library.kmod+0x0002dfd4

Stack trace:
(0x5D3ED730) [gui/widget.cpp:188] residualvm:_ZN3GUI6Widget10setEnabledEb()+0x24 (section 1 @ 0x216D90)
(0x5D3ED750) [gui/options.cpp:912] residualvm:_ZN3GUI13OptionsDialog20setMIDISettingsStateEb()+0x9c (section 1 @ 0x1DDF10)
(0x5D3ED770) [gui/editgamedialog.cpp:437] residualvm:_ZN3GUI14EditGameDialog13handleCommandEPNS_13CommandSenderEmm()+0x22c (section 1 @ 0x233BFC)
(0x5D3ED9C0) residualvm:_ZN3GUI6Widget13handleCommandEPNS_13CommandSenderEmm()+0x80 (section 1 @ 0x21BC0C)
(0x5D3ED9E0) [gui/widgets/tab.cpp:183] residualvm:_ZN3GUI9TabWidget13handleCommandEPNS_13CommandSenderEmm()+0x40 (section 1 @ 0x2277FC)
(0x5D3EDA00) [gui/widget.cpp:55] residualvm:_ZN3GUI13CommandSender11sendCommandEmm()+0x70 (section 1 @ 0x21B66C)
(0x5D3EDA20) [gui/widget.cpp:568] residualvm:_ZN3GUI14CheckboxWidget8setStateEb()+0x9c (section 1 @ 0x2194D0)
(0x5D3EDA40) [gui/editgamedialog.cpp:336] residualvm:_ZN3GUI14EditGameDialog4openEv()+0x950 (section 1 @ 0x232EB0)
(0x5D3EDE50) [gui/dialog.cpp:77] residualvm:_ZN3GUI6Dialog8runModalEv()+0x34 (section 1 @ 0x1CBC5C)
(0x5D3EDE70) [gui/launcher.cpp:446] residualvm:_ZN3GUI14LauncherDialog8editGameEi()+0x170 (section 1 @ 0x1D2ACC)
(0x5D3EE3C0) [gui/launcher.cpp:638] residualvm:_ZN3GUI14LauncherDialog13handleCommandEPNS_13CommandSenderEmm()+0x1a0 (section 1 @ 0x1D3814)
(0x5D3EE690) [gui/widget.cpp:55] residualvm:_ZN3GUI13CommandSender11sendCommandEmm()+0x70 (section 1 @ 0x21B66C)
(0x5D3EE6B0) [gui/widget.cpp:348] residualvm:_ZN3GUI12ButtonWidget13handleMouseUpEiiii()+0xe8 (section 1 @ 0x217BE0)
(0x5D3EE6E0) [gui/dialog.cpp:216] residualvm:_ZN3GUI6Dialog13handleMouseUpEiiii()+0x16c (section 1 @ 0x1CC4E0)
(0x5D3EE720) [gui/gui-manager.cpp:581] residualvm:_ZN3GUI10GuiManager12processEventERKN6Common5EventEPNS_6DialogE()+0x408 (section 1 @ 0x1CF4CC)
(0x5D3EE760) [gui/gui-manager.cpp:351] residualvm:_ZN3GUI10GuiManager7runLoopEv()+0x318 (section 1 @ 0x1CE534)
(0x5D3EE7D0) [gui/dialog.cpp:80] residualvm:_ZN3GUI6Dialog8runModalEv()+0x44 (section 1 @ 0x1CBC6C)
(0x5D3EE7F0) [base/main.cpp:106] residualvm:_ZL14launcherDialogv()+0x78 (section 1 @ 0x87B0)
(0x5D3EE8E0) [base/main.cpp:605] residualvm:scummvm_main()+0xe5c (section 1 @ 0xA874)
(0x5D3EF0D0) [backends/platform/sdl/amigaos/amigaos-main.cpp:79] residualvm:main()+0x22c (section 1 @ 0x84E0)
(0x5D3EFD00) native kernel module newlib.library.kmod+0x000020a4
(0x5D3EFD70) native kernel module newlib.library.kmod+0x00002d0c
(0x5D3EFF10) native kernel module newlib.library.kmod+0x00002ee8
(0x5D3EFF50) residualvm:_start()+0x170 (section 1 @ 0x5374)
(0x5D3EFF90) native kernel module dos.library.kmod+0x000255c8
(0x5D3EFFC0) native kernel module kernel.debug+0x0006e9c0
(0x5D3EFFD0) native kernel module kernel.debug+0x0006ea08

Disassembly of crash site:
 7F0BDDA4: 907F0008   stw               r3,8(r31)
 7F0BDDA8: 7C892378   mr                r9,r4
 7F0BDDAC: 993F000C   stb               r9,12(r31)
 7F0BDDB0: 813F0008   lwz               r9,8(r31)
>7F0BDDB4: A129006C   lhz               r9,108(r9)
 7F0BDDB8: 552A07FE   rlwinm            r10,r9,0,31,31
 7F0BDDBC: 893F000C   lbz               r9,12(r31)
 7F0BDDC0: 7F8A4800   cmpw              cr7,r10,r9
 7F0BDDC4: 419E0054   beq-              cr7,0x7F0BDE18
 7F0BDDC8: 893F000C   lbz               r9,12(r31)
Stack pointer (0x5D3ED730) is inside bounds
Redzone is OK (4)

68k register dump
DATA: 97316200 00000000 00000000 00000000 00000000 00000000 00000000 00000000
ADDR: 6FFB8000 957EC000 00000000 00000000 00000000 00000000 00000000 5D3EE280
Page information:
Page not found

**Comment by klusark** [comment]
I can't seem to reproduce this issue.

**Comment by raziel-** [comment]
Still crashing here with latest sources.

This is my residualvm.ini:
[residualvm]
filtering=false
mute=false
speech_volume=256
check_gamedata=true
gui_theme=modern
kbdmouse_speed=3
savepath=Games:ResidualVM/saves/
renderer=opengl
extrapath=Games:ResidualVM/extras/
soft_renderer=false
subtitles=false
fullscreen=true
gui_browser_show_hidden=false
browser_lastpath=Cache:Downloads/Betatest ScummVM Games/grimdemo/
lastselectedgame=grim-win
themepath=Games:ResidualVM/themes/
sfx_volume=192
talkspeed=179
music_volume=129
speech_mute=false
bpp=16
vsync=true
aspect_ratio=true
versioninfo=0.4.0git
autosave_period=300
gui_language=C

[grim-win]
description=Grim Fandango (Windows/English)
speech_volume=254
check_gamedata=false
use_arb_shaders=true
game_devel_mode=false
datausr_load=false
savepath=Games:ResidualVM/saves/
path=Games:GamesVM/Lucas Arts/Grim Fandango/
engine_speed=62
subtitles=false
gameid=grim
language=en
last_set=me.set
gui_saveload_last_pos=11
sfx_volume=192
talkspeed=153
music_volume=128
show_fps=true
platform=windows
gamma=0
joystick=false
speech_mute=false
last_saved_game=grim27.gsv
guioptions=sndNoMIDI gameOption1 gameOption2 lang_English

[monkey4-win]
description=Escape From Monkey Island (Windows/English)
check_gamedata=false
datausr_load=false
path=Games:GamesVM/Lucas Arts/Monkey Island/Escape from Monkey Island/
engine_speed=62
gameid=monkey4
language=en
show_fps=true
platform=windows
guioptions=sndNoMIDI gameOption1 gameOption2 lang_English

[myst3-win]
description=Myst III Exile (Windows/English)
widescreen_mod=true
path=Games:GamesVM/Cyan Productions/Exile/
gameid=myst3
language=en
platform=windows
guioptions=sndNoSubs sndNoSpeech sndNoSFX sndNoMIDI gameOption1 lang_English

[grim-demo-win]
description=Grim Fandango (Demo/Windows/English)
check_gamedata=false
datausr_load=false
path=Cache:Downloads/Betatest ScummVM Games/grimdemo/
gameid=grim
language=en
show_fps=false
platform=windows
guioptions=sndNoMIDI gameOption1 gameOption2 lang_English



I can trigger the error with all three games, using either of the follwoing three commands

Command-Line: residualvm grim (mind the missing "-win")

Mouse shown 0
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
User picked target 'grim' (gameid 'grim')...
  Looking for a plugin supporting this gameid... Grim Engine
  Starting 'Grim Fandango'
WARNING: Grim Engine failed to instantiate engine: Path does not exist (target 'grim', path '')!
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8

There is no target "grim" anywhere in my residualvm.ini, so why is residualvm making one up? (and crashing in the process)



Command-Line: residualvm monkey4 (mind the missing "-win")

residualvm monkey4
Mouse shown 0
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
User picked target 'monkey4' (gameid 'monkey4')...
  Looking for a plugin supporting this gameid... Grim Engine
  Starting 'Escape From Monkey Island'
WARNING: Grim Engine failed to instantiate engine: Path does not exist (target 'monkey4', path '')!
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8


There is no "monkey4" target in the .ini



Command-Line: residualvm myst3

residualvm -F myst3
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
User picked target 'myst3' (gameid 'myst3')...
  Looking for a plugin supporting this gameid... Myst III Engine
  Starting 'Myst III Exile'
WARNING: Myst III Engine failed to instantiate engine: Path does not exist (target 'myst3', path '')!
Mouse shown 0
WARNING: Could not parse GLSL version 'Huh?'!
INFO: OpenGL Vendor: The MiniGL Team
INFO: OpenGL Renderer: MiniGL/Warp3D AMD Radeon HD Southern Islands
INFO: OpenGL Version: 1.3
INFO: OpenGL Red bits: 0
INFO: OpenGL Green bits: 0
INFO: OpenGL Blue bits: 0
INFO: OpenGL Alpha bits: 0
INFO: OpenGL Z buffer depth bits: 0
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8

There is also no "myst3" target in the.ini, still residualvm makes one up.



The only game where it doesn't happen is "grim-demo".
Using this demo, it will show the correct message:

Command-Line residualvm grim-demo (mind the missing "-win")

residualvm: Unrecognized game target 'grim-demo'
Usage: residualvm [OPTIONS]... [GAME]

Try 'residualvm --help' for more options.

**Comment by raziel-** [comment]
The underlying "bug" seems to be old and known
https://bugs.scummvm.org/ticket/2788

Probably nothing that can be done about it unless it was fixed in ScummVM (which will also fix the crash accordingly)

**Comment by raziel-** [comment]
Bug was fixed in ScummVM, but is still present in residualvm
