### ISSUE TITLE
Unable to add Myst 3 from datafiles in Myst 3 Collectors DVD (came with Myst 4)

### ISSUE THREAD

**Issue by hfball** [residualvm/residualvm#1378]
I'm getting an error with the SVN downloaded 11/26/2017 when I try to add Myst 3, English.

The console error is as follows:

The game in 'D:\Games\ResidualVM\Myst3\' seems to be unknown.
Please, report the following data to the ResidualVM team along with name
of the game you tried to add and its version, language, etc.:

  {"RSRC.m3r", 0, "a2c8ed69800f60bf5667e5c76a88e481", 1223862},
  {"ENGLISH.m3t", 0, "74726de866c0594d3f2a05ff754c973d", 3407120},

**Comment by hfball** [comment]
![residualvm_svn](https://user-images.githubusercontent.com/17295957/33246449-0e278ca2-d2da-11e7-9a11-56a08981d354.png)

**Comment by bgK** [comment]
That means you are missing a [language].m3u file from the DVD. Please refer to the readme for instructions.

Newer versions of ResidualVM don't show that warning when users forget to copy that file.

**Comment by hfball** [comment]
Ah. I had left it named "language.m3u" instead of renaming it to "English.m3u." I used the wiki for the file format, and it says either/or, not that you need to rename "language.m3u."

Once I renamed the file, the problem went away.
