### ISSUE TITLE
GRIM: Conveyer belt doesn't render correctly

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#1382]
I've put the chain down it and reverse the direction, then put the chain up. This happens both in OpenGL and Software.

![screenshot 2017-12-02 18 46 34](https://user-images.githubusercontent.com/240865/33521821-a9031da2-d791-11e7-95f0-3bf4495820a0.png)

save: ![grim35](https://user-images.githubusercontent.com/240865/33521825-dca70d44-d791-11e7-98dc-5c2f39dbc9e4.png)

**Comment by klusark** [comment]
Later when I put the chain back down it looks like this

![image](https://user-images.githubusercontent.com/240865/33521903-283a64a2-d794-11e7-9060-0e486963a287.png)

**Comment by bgK** [comment]
The same happens in 0.2.1 using your save.
