### ISSUE TITLE
SDL: enters an infite loop on screen(window) switch

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1383]
ResidualVM 0.4.0git (Dec  1 2017 23:17:43)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

See here: https://sourceforge.net/p/sdl2-amigaos4/tickets/35/

When i switch (LALT+ENTER) from screen to window, SDL2 enters an infinite loop on switching between window and screen.
After some more testing this issue is prominent with ALL games supported and happens everytime.

quote from the AmigaOS4 SDL2 dev:
Finally found where the extra events are coming: https://github.com/residualvm/residualvm/blob/13ad766b312f301c709f747451c3fa287fd69e4f/backends/events/default/default-events.cpp#L235
In fact if you comment out 233-242 the fullscreen loop goes away. Otherwise it will send the keydown event (ALT+ENTER) again and again even though AmigaOS is not sending it.
I don't know the purpose of this code. Maybe ScummVM devs could help as my progress is slow.
/quote

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 5.4.0) 5.4.0

**Comment by bgK** [comment]
That code is responsible for generating key down repeat events while a key is pressed. If you are seeing an infinite stream of events, that means SDL never sent the key up event matching a key down event it sent. That's a bug in the Amiga version of SDL that should be fixed.

However, that code was recently disabled in ScummVM in favor of SDL2's native key repeat events. I'll import the changes from ScummVM to see if it helps.

**Comment by raziel-** [comment]
Thank you

**Comment by raziel-** [comment]
quote:
Alright, thank you. Missing key ups might be explained by the transition between window and fullscreen because we have close our window and then reopen it on another screen. We assign a shared message port during window creation. So there is a certain "blind" period for SDL, if you happen to release key during the blind period, then we could miss it.
/quote

So, yeah, waiting for the native key repeat to test :-)

**Comment by raziel-** [comment]
The "endless loop" was fixed with the latest code (although i now have a bug where the "right" and "left" cursor keys stop working as soon as i enter window mode and they never come back, even switching back to fullscreen. Need to check with the SDL2 maintainer, otherwise i'll open a new item here.)

Thank you

**Comment by raziel-** [comment]
Sorry, but could we keep this open?

The loop is not gone as i thought but has changed.

See ticket 35 from my first post.

**Comment by bgK** [comment]
Sure. I've imported some more code I missed from ScummVM. Could you check if it solves the issue for you?

**Comment by raziel-** [comment]
Thank you.

I will check it as soon as i get home...unfortunately not before the 23rd.

**Comment by raziel-** [comment]
Sorry for the long delay and thank you again for keeping this open.

Issue has been fixed with the latest builds.
