### ISSUE TITLE
GRIM: Manny holds scythe wrong

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#1384]
![image](https://user-images.githubusercontent.com/240865/33527827-228c3558-d80c-11e7-93e0-2a071f942007.png)
[grim46.zip](https://github.com/residualvm/residualvm/files/1524992/grim46.zip)

**Comment by bgK** [comment]
The same happens in 0.2.1 using your save.

**Comment by eblanca** [comment]
This issue seems to be fixed in latest residualvm.

ResidualVM 0.4.0git (Jul  4 2018 20:27:13)
Features compiled in: Vorbis MP3 ALSA RGB zLib Theora FreeType2 JPEG PNG

![falce](https://user-images.githubusercontent.com/1640886/43289612-cce28f4c-912b-11e8-8782-76edfc1dad9a.png)
