### ISSUE TITLE
GRIM: Smoke goes behind manny

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#1385]
![image](https://user-images.githubusercontent.com/240865/33528023-737a36a6-d80f-11e7-9b7b-bdb6927af7cd.png)

In this scene, if you hit enter on the logo on the ground manny takes a smoke. The smoke renders behind him.
[grim49.zip](https://github.com/residualvm/residualvm/files/1525002/grim49.zip)

**Comment by bgK** [comment]
The same happens in 0.2.1 using your save.
