### ISSUE TITLE
MYST3: Polish subtitles fail to decode on Windows due to libiconv and glibc's iconv different naming schemes

### ISSUE THREAD

**Issue by dagashiya** [residualvm/residualvm#1387]
Hi,
after submitting [a pull request to properly handle encoding of Polish subtitles in Myst 3](https://github.com/residualvm/residualvm/pull/1386), I noticed that Windows builds would still fail on the first subtitle. After some investigation, I discovered the issue lies with different ways of referring to MacOS brand of 8-bit encodings across different iconv versions.

For example, libiconv (like the one bundled with MinGW) accepts only MACCENTRALEUROPE while the version of iconv that ships with glibc (and is likely used by majority of GNU/Linux machines) accepts only MAC-CENTRALEUROPE or CP1282 (which, according to a gconv alias file, is only an alias of MAC-CENTRALEUROPE). If there is a middle ground that is shared between those versions, I wasn't able to find it.

This can be easily verified by invoking iconv -l and comparing output of both versions.

While the MinGW version of libiconv is outdated, upgrading it to latest one seems to do nothing - libiconv 1.15's naming scheme remains the same.

**Comment by bgK** [comment]
Thanks for the very detailed bug report.

It's pretty sad two open source implementations of iconv can't agree on such simple things ...
