### ISSUE TITLE
SDL 1: Black Window/Screen (not updated?) on mode switch while in Options (Pause)

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1389]
ResidualVM 0.4.0git (Dec 31 2017 15:41:14)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

- Start any game (preferably Grim Fandango)
- Press ESC to get right into the game
- Press F1 to bring up the "menu" (game is paused)
- Perform a mode switch (ALT+Enter) to switch to/from window/screen

One will end up with a black screen/window due to, what i think, is a missing screen/window redraw command after said mode switch. I guess it's not trggered because the game is in pause mode(?)

Pressing ESC or cursor up/down will trigger a redraw and all is fine again, but imho it's a bad idea to leave users with a black window/screen...at least i thought residualvm has crashed on me.

AmigaOS4 - SDL - BE - PPC
gcc (adtools build 5.4.0) 5.4.0

**Comment by raziel-** [comment]
Only the SDL 1 build is affected

**Comment by raziel-** [comment]
One funny thing i found out is that the demo displays this problem on both SDL1 and SDL2, while the full game suffers only in SDL1 from it.

Might this be an issue in the original data files?

**Comment by klusark** [comment]
I guess the game data affects how this issue occurs, but it's something we could fix properly regardless of game version.
