### ISSUE TITLE
GRIM: Audio stuttering

### ISSUE THREAD

**Issue by Napper64** [residualvm/residualvm#1391]
Issue reported in http://forums.residualvm.org/viewtopic.php?f=1&t=156

The audio for grim fandango running on Windows is intermittently stuttering. I think I might have narrowed it down. 

residualvm/engines/grim/imuse/imuse_track.cpp
line 278
`int32 mixer_size = track->feedSize / _callbackFps;`
If i replace the above line with something like
`int32 mixer_size = (track->feedSize * 1.1) / _callbackFps;`
This seems to solve/help the issue. 
But when I increase the size of the "mixer_size" variable this has a slight knock on effect to the delay in lip syncing for Manny and specific timing between lines of dialogue.

If some developer who has an actual understanding of the imuse implementation could take a better look.

**Comment by Botje** [comment]
Thank you for keeping track of this.
