### ISSUE TITLE
EMI crashes on save

### ISSUE THREAD

**Issue by Protarios** [residualvm/residualvm#1394]
EMI is generally very unstable an crashes often on trying to save. Music stuttering, complete Operating Systems comes to halt. Even forced restart of X11 server is not working anymore.
I can play up to where the rubber band is added to the cactus at Marley Mansion. After this step the game crashes on simply trying to enter save menu.

OS: Linux.Mint 18.3, ResidualVM 0.3

**Comment by Botje** [comment]
Does this happen on all three rendering methods? (ie. software, OpenGL, OpenGL with shaders)
Can you run other 3D games well?
Can you capture a crash dump?
