### ISSUE TITLE
Myst 3: Exile - wrong texts on letters in Polish version

### ISSUE THREAD

**Issue by ziele6** [residualvm/residualvm#1405]
I have 4 cd version of Myst 3 with Polish and English language. Main menu and sounds are correctly in Polish but texts on letters are in English. It looks like residualvm load wrong graphics.
Language is ok when I run Myst 3 without residualvm, but game has glithes in all animations between locations, so it is unplayable :(

Windows 10 Pro 64bit Polish
game version 1.22PO (172)

**Comment by bgK** [comment]
The option screen from the main menu should offer the ability to change language between English and Polish. Is it not working for you ?

**Comment by ziele6** [comment]
It changes all voices and texts to Polish language except pre rendered graphics like letter from Atrus at the beginning of the game. It should looks like on attached screenshot, but it is in English.
![list](https://user-images.githubusercontent.com/37051335/37243313-92ec361a-2477-11e8-8d1c-01ec518e8ef6.png)
