### ISSUE TITLE
STARK: Clicking "Continue the Journey" should show "Load game" window

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1419]
First of all, thanks @DouglasLiuGamer for implementing a main menu and intro/credits video! I like them a lot and even if it's a small thing they really give feel for a progression. Thanks to @bgK for all the other hard work I've been keeping an eye for as well during the last few months :).

Now, back to the issue – I guess it should be easy enough to implement, but since I don't feel up for coding, I'm just posting a suggestion – it would be nice if clicking the *Continue the Journey* button in the main menu would show the *Load game* window (Residual's for the time being), as currently clicking it seems to do nothing.

**Comment by DouglasLiuGamer** [comment]
Hi. Thanks for the words! Right now the Continue button really does nothing. I have made the PR to provide the rough loading functionality. BTW, You can always use the launcher or the Global Main Menu (ctrl + F5 on Windows) to load the game.

It is planned to implement the original save & load menu in this week. Big thanks for watching :)
