### ISSUE TITLE
GRIM: Unable to find track to change volume!

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#142]
Almost all tracks have "Unable to find track '*' to change Volume!" warnings currently, making the dialogue when he finds Glottis' heart in the Petrified Forest almost impossible to hear.

Afterwards, this makes the Car sounds horribly loud as well.

Submitted:
Einar Johan T.S. ( somaen ) - 2011-04-05 18:45:14 CEST

Issue ported from sf.net-tracker.

**Comment by d356** [comment]
I'm having trouble reproducing this bug on master as well as the 0.2.1 release.  Are these the two scenes being referred to? ![screen shot 2015-02-05 at 3 45 30 pm](https://cloud.githubusercontent.com/assets/10871998/6068934/3d5d89cc-ad4e-11e4-9953-833f2a0ef5a6.png)
![screen shot 2015-02-05 at 3 45 10 pm](https://cloud.githubusercontent.com/assets/10871998/6068939/42f27aaa-ad4e-11e4-834f-4e04c5d9d38c.png)

While the "Unable to find track '*' to change Volume!" warnings still appear, in the first scene, Manny's dialogue seems to be at a normal volume. In the second, the car seems to be at a normal volume as well.
