### ISSUE TITLE
STARK: Credits doesn't work without High Quality Video (GOG version)

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1423]
Steam version and Steam demo doesn't have option to uncheck the high quality videos, plus Steam demo doesn't have credits at all, so I can't check that, but for the full GOG version unchecking the *High Quality Video* option makes the credits unable to play – not sure if it's due to lack of high quality video of credits in game file and if it is intentional or not, but I thought I'll let it now in case it's an overlook.

**Comment by DouglasLiuGamer** [comment]
Strange. I am also using the Steam version for development, which does not have any low-resolution videos. In this case, the settings menu should not have the video option, so normally you can't *uncheck* it unless you manually change it in the configuration file.

Could you please take a look at your Steam version's game data, go to the **Global/xarc** folder, and see if there is any **.bbb** file with the suffix "_lo_res" in its name? If it does, does it have **1402_lo_res.bbb**? I use this FunCom logo video to check whether there are low-resolution videos.

**Comment by Faalagorn** [comment]
Oops, my bad – i confused it – it was *GOG* version that had the videos, while Steam indeed doesn't have the option present as well, so the bug is for the GOG version, not the *Steam* version :)

**Comment by Faalagorn** [comment]
I found out that ***0e02.bbb** file is the one with credits and there's indeed no *lo_res* version of it distributed with GOG files. Steam full version and Steam demo doesn't have low res files at all, so it seems to be game's version issue. I'm not sure if any of the other versions have a low resolution credits, and how the original game behaves in that case.

**Comment by DouglasLiuGamer** [comment]
It will be unrealistic to check all the videos to determine whether to provide the setting... Anyway, I made a PR which will use the original video when low-res one cannot be found. There is a cost added for such an additional checking, but if that's the case for all GOG versions, I think we have to cover this.

**Comment by Faalagorn** [comment]
Not sure how computational heavy is this, but This should also help if for some reason someone manually change it in configuration files like you said before – though it would be worth checking how the original game behaves with that, even if just for curiosity.

**Comment by DouglasLiuGamer** [comment]
Now that I think of it there is almost no computational heaviness actually... I thought too much.

My original implementation can well handle the case of changing the configuration files manually. The GOG version you mentioned is just kind of strange, whose videos are not consistent with only the credits video lacking low-res version. Anyway, if this exists, we need to handle it.

**Comment by Faalagorn** [comment]
Confirmed working as of 388eafa (tested with GOG version).
