### ISSUE TITLE
MYST3: Glyph Zoom puzzle resets state to last state on menu return

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1427]
This bug is also present in the original.

In J'nanin when lining up the glyphs by zooming in and out and panning if you make progress on this puzzle and open the in-game menu while still looking at the puzzle and hit resume the state of the puzzle will be reset to where it was before your last changes. So if you made no changes it will be as it was, but if you have those changes will be reverted.

Annoying if you spend time solving the puzzle go to save it (which also shows the solution in the thumbnail) to have the puzzle be reverted back when you return from the menu. A workaround is to solve the puzzle, step back from the puzzle, and then save.

**Comment by bgK** [comment]
This is a limitation of the game engine design. Nodes are reloaded when leaving the menu, resetting their non pesistent state. There is not much to do about it.
