### ISSUE TITLE
STARK: Segmentation fault when most commands are being used when level is not loaded

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1430]
When you type any of these commands to the debug console (`Ctrl +d`), while the game is at the initial Funcom video, credits, main or setting menu (and probably other menus that are yet to be implemented in `master`), it crashes with the `Segmentation fault (core dumped)` error printed to stdout:
* `changeChapter` + param
* `changeKnowledge` + params
* `changeLocation` + params
* `chapter`
* `decompileScript` + param
* `dumpGlobal`
* `dumpKnowledge`
* `dumpLevel`
*  `dumpLocation`
* `dumpRoot`
* `enableInventoryItem` + param
* `enableScript` + params
* `forceScript` + param
* `listInventory`
* `listScripts`
*  `location`

Commands that don't cause the crash:
* `dumpArchive` + param
* `dumpStatic`
* `listLocations`
* `testDecompiler`

as well as the commands that require parameters when passed without any parameters + built-in commands (`help`, `quit`, `exit`, `openlog`, `debugflag_list`, `debugflag_enable`, `debugflag_disable`, `md5` and `md5mac`).

I think additional check should be performed when these commands are initiated to check whether the level is loaded.

* Information about the game: The Longest Journey, all versions (tested on GOG, Steam, Steam demo, retail demo)
* Language of game: English
* Platform: Linux

**Comment by Faalagorn** [comment]
The same happens on the newly implemented save/load menu, but only when accessed from the main menu, so nothing really changes.

**Comment by DouglasLiuGamer** [comment]
Fixed in #1456
