### ISSUE TITLE
STARK: listInventory should print list in debug console instead stdout

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1431]
`listInventory` command from the debug (`ctrl + d`) menu currently print the list of items as `WARNING: Item…` into stdout. It should probably print it's info to the residual's console, just like the `listLocations` and `listScripts` commands do.

* Information about the game: The Longest Journey, all versions (tested on GOG, Steam, Steam demo, retail demo)
* Language of game: English
* Platform: Linux

**Comment by DouglasLiuGamer** [comment]
Fixed in #1456
