### ISSUE TITLE
STARK: enableInventoryItem crashes the game when used with non-existing id

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1432]
When you type `enableInventoryItem` with an id that does not exist, ex. `enableInventoryItem 107` or `enableInventoryItem -1` into the game debug console (`ctrl + d`), the game crashes with the following error message:
```
residualvm: ./common/array.h:192: T& Common::Array<T>::operator[](Common::Array<T>::size_type) [with T = Stark::Resources::Item*; Common::Array<T>::size_type = unsigned int]: Assertion `idx < _size' failed.
Aborted (core dumped)
```

* Information about the game: The Longest Journey, all versions (tested on GOG, Steam, Steam demo, retail demo)
* Language of game: English
* Platform: Linux

**Comment by DouglasLiuGamer** [comment]
Fixed in #1456
