### ISSUE TITLE
STARK: Segmentation fault or crash when loading wrong level/location with changeLocation

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1435]
The Longest Journey crashes with `Segmentation fault (core dumped)` error printed to stdout when trying to load a non-existing level (e.g. `changeLocation ff ff`) or with  `Unexpected resource type when casting resource Level instead of Location!` printed to stdout when level is right but location is wrong (e.g. `changeLocation 0a ff`.

I think additional check should be performed when these commands are initiated to check whether the level or location exist and if not, just print an error to console instead stdout and do not crash ResidualVM.

* Information about the game: The Longest Journey, all versions (tested on GOG, Steam, Steam demo, retail demo)
* Language of game: English
* Platform: Linux

**Comment by DouglasLiuGamer** [comment]
Fixed in #1456
