### ISSUE TITLE
MYST3: Subtitles can be stretched

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1445]
Windows 10. 
Screen resolution is 1842 x 1036.

Starting a game in fullscreen shows the subtitles at the bottom being stretched. If I start the game windowed it doesn't happen. If I start the game in fullscreen and then window it it still shows it stretched. If I start the game windowed and make it fullscreen (alt+enter) it shows the subtitles correctly.

doesn't matter if widescreen or aspect ratio on/off or opengl render type.

The attached screenshot I got after starting in fullscreen and then windowing it.

![screenshot 3](https://user-images.githubusercontent.com/5838258/41389579-9a542bf0-6f5f-11e8-9864-ef64f4c8d9ae.png)

**Comment by bgK** [comment]
Please check if this is fixed for you. It seems to be graphics driver dependent.

**Comment by dafioram** [comment]
Fixed.
