### ISSUE TITLE
MYST3: Crash when switching saves from regular to widescreen when viewing subtitles

### ISSUE THREAD

**Issue by dafioram** [residualvm/residualvm#1446]
Windows 10.

1. Turn off widescreen, but do fullscreen.
2. Load Test.m3s from gui
3. Look left at the rocks so the subtitle below appears
![screenshot 4](https://user-images.githubusercontent.com/5838258/41390155-678cd994-6f62-11e8-9ccb-9dd15f84f527.png)

4. Using the in game menu load Test2.m3s (saved with widescreen)
5. look at rocks again and it should crash.
[Saves.zip](https://github.com/residualvm/residualvm/files/2100713/Saves.zip)
[log2.txt](https://github.com/residualvm/residualvm/files/2100711/log2.txt)

**Comment by bgK** [comment]
I cannot reproduce the crash. Please check if this was fixed at the same time as #1445 and reopen if needed.

**Comment by dafioram** [comment]
It is fixed.
