### ISSUE TITLE
EMI: Guybrush can get stuck after bumping into the LUA bar waitress

### ISSUE THREAD

**Issue by Tea23** [residualvm/residualvm#1452]
I think I can vaguely remember this happening in the original game, but it's been 9 years since I last played.

When Guybrush makes contact with the LUA bar waitress he says "Oops, sorry" and moves away from her. If both the waitress and Guybrush are trying to get over the bridge towards the kitchen at the same time, with the waitress to Guybrush's left, Guybrush can become stuck in a permanent walking animation as he can't get past her. I guess he always goes in the same direction in this event.

Inputs aside from opening the main menu are disabled until the animation is finished, so pressing the exit key doesn't work to escape the animation loop and leave the bar, the only option is to load a save game.

**Comment by Nitrus** [comment]
In light of the game being released on GOG, I reproduced that behaviour in the original game (without ResidualVM).
Here is an original savegame and a clip if they are of any use:
![originalbridgebump](https://user-images.githubusercontent.com/1910122/41810681-d480b884-7702-11e8-83a1-53b9f5071d6f.gif)

[original-savegame.zip](https://github.com/residualvm/residualvm/files/2129981/original-savegame.zip)

**Comment by Tea23** [comment]
@Nitrus Is he getting stuck in this? In your clip it looks like he's moving out of the way exactly as I'd have expected?

**Comment by Nitrus** [comment]
@Tea23 No sorry, I wasn't clear in my original comment.
I was trying to reproduce for a good 10 minutes without success. I tried to go from the section where the tourist is, towards the kitchen, timing it just as soon as the waitress tries to go over as well.
I wasn't able to get stuck even once.
I uploaded the savegame as a close point to anyone that might want to try it, and the clip just as a demonstration of the "Aahh... oops, sorry." line.

Here's another original savegame that's even closer to trying to reproduce the event:
[original-savegame.zip](https://github.com/residualvm/residualvm/files/2129990/original-savegame.zip)

**Comment by Nitrus** [comment]
I managed to reproduce it, the trick seems to be being close to the railing. I also had a better success rate if Guybrush was facing/looking at the waitress.
Reproducible in the original game and latest ResidualVM daily.
I used debug command "jump 200" to get close to that point.

![sstuck](https://user-images.githubusercontent.com/1910122/41811116-b30d1358-7709-11e8-8c43-dcf4b6c1e1da.gif)

**Comment by Tea23** [comment]
Ah I guess if it's reproducible in the original game we're SOL! I feel like it's happening more frequently in Residual though.

Playing to this point earlier I even got stuck when the waitress was over by the salad bar and I had Guybrush standing on the bridge. She just turned around and I guess gave Guybrush a dirty look because he decided to say sorry and start walking away, but got stuck.

Perhaps this has something to do with the pathing over the bridge?

**Comment by Nitrus** [comment]
In the clip above, Guybrush is trying to get to the left of the bridge, on the kitchen-side of the restaurant.
I've gotten these messages in the console debugger, after enabling the scripts flag:
```
Debug: waitress has run into Guybrush
Debug: Guybrush has run into waitress
WARNING: Actor::walkTo(): No path found for waitress!
...
WARNING: Lua_V2::ActorStopMoving, actor: Guybrush!
Debug: guy ensure walk
```
So several things are probable I guess:
- Waitress has no path, and then just collision prevents Guybrush from going about his business.
- I'm not sure if Guybrush has a path himself, but perhaps just a target location. Collision with the railing may be stopping him from getting there

Also yes, seems quite easy to reproduce in ResidualVM. To me it seems it also happens when the waitress just _decides_ to go over on the other side, Guybrush says "Ah... oops, sorry.", gets stuck, but the waitress just keeps going about her business, doesn't even try to cross the bridge.
