### ISSUE TITLE
EMI: Carla is invisible in the Microgroggery

### ISSUE THREAD

**Issue by Tea23** [residualvm/residualvm#1453]
Carla should be slouched over the bar getting sloshed but in ResidualVM it looks like she's only there in spirit.

![residualvm opengl renderer with shaders_006](https://user-images.githubusercontent.com/1298028/41812984-bf2570fc-7724-11e8-97e7-fe3694a8a10c.png)

**Comment by Nitrus** [comment]
I've not been able to reproduce by jumping to point 251. Could be a pre-condition, or...
Could you try with the regular renderer (no shaders)?

**Comment by Tea23** [comment]
Tried all the avilable renderers, OpenGL with and without shaders and software.

This is on Arch Linux with an Nvidia 1070 using proprietary driver 396.24.

**Comment by Botje** [comment]
Cannot reproduce with current version as of 2020-05-17.
