### ISSUE TITLE
STARK: Setting chapter with "changeChapter" debug command very high (or low) results in weird chapter values

### ISSUE THREAD

**Issue by Faalagorn** [residualvm/residualvm#1466]
Related to #1456.

There seems to be no checks performed on setting the value of the "setChapter" command – while luckily it doesn't crash the game, setting too high (or too low) value results in wrong values being set, for example bu setting `changeChapter -9999999999` I get the value of -14100565407 (opposite in case of the positive values).

It seems to happen starting at 2^31 so `changeChapter 2147483647` is okay, while `changeChapter 2147483648` overflows the value to -2147483648. Then setting `changeChapter 2147483649` continues to go higher setting it to -2147483647

Setting it to even more extreme value, such as `changeChapter 99999999999999999999` sets the chapter at -1. I didn't tested at which point exactly does it happen.

**Comment by DouglasLiuGamer** [comment]
Unfortunately, this issue **does** crash the game. The chapter value is used to acquire the chapter title when saving. If the chapter value is illegal, the assertion there will fail. #1484 didn't fix this either. It will be better to add a range check.
