### ISSUE TITLE
STARK: Swedish CD version no longer starts

### ISSUE THREAD

**Issue by eriktorbjorn** [residualvm/residualvm#1469]
The Swedish version of The Longest Journey used to start, but now it crashes after the FunCom logotype movie with the following messages:

````
User picked target 'tlj-win-se' (gameid 'stark')...
  Looking for a plugin supporting this gameid... Stark Engine
  Starting 'Stark Game'
INFO: OpenGL Vendor: X.Org
INFO: OpenGL Renderer: AMD BONAIRE (DRM 2.50.0, 4.16.0-2-amd64, LLVM 6.0.0)
INFO: OpenGL Version: 3.1 Mesa 18.1.2
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
INFO: GLEW Version: 2.0.0
INFO: GLSL version: 1.40
Unable to find render entry with name 'VERSION INFO REALLY' in location 'MainMenuLocation'
Segmentation fault
````
Unlike the English DVD version, the MainMenuLocation.xarc file does not contain the string "VERSION INFO REALLY" anywhere. Changing the source code to request "VERSION INFO" instead allows it to start, though I don't see any information besides the hard-coded string.

**Comment by DouglasLiuGamer** [comment]
Yeah changing to request "VERSION INFO" should be enough. I assume that the version info stored in both "VERSION INFO" and "VERSION INFO REALLY" is broken (which is the case for the Steam version I use), so I build the version info text on my own.

I'll prepare the PR for the patch right away.
