### ISSUE TITLE
WEB: FAQ refers to "Bug Reports" instead of "Issue reports"

### ISSUE THREAD

**Issue by eriktorbjorn** [residualvm/residualvm#1473]
The [ResidualVM FAQ](http://www.residualvm.org/faq/) says, in part, that

`To report a bug, please create a GitHub account and follow the Bug Reports link from our homepage.`

The link on the [ResidualVM home page](http://www.residualvm.org/) does have a link, but there it's called "Issue Tracker" instead of "Bug Tracker". A minor issue, but it did make it harder for me to find the link when I was looking for it.

**Comment by aquadran** [comment]
corrected
