### ISSUE TITLE
GRIM: Dialogue transcript of cutscenes is always in english

### ISSUE THREAD

**Issue by BLooperZ** [residualvm/residualvm#1477]
Hi,
When viewing dialogue transcript through the menu (F1),
the transcript of the opening cutscene always appear to be in english,
even when playing Non-English version of the game.
This issue occurs in official translations (Italian, Spanish) and fan translations (Greek).
The transcript of in-game dialogue appears in the respective language as it should.

Thanks.

**Comment by eblanca** [comment]
I can confirm this happens with recent residual.

ResidualVM 0.4.0git (Jul  4 2018 20:27:13)
Features compiled in: Vorbis MP3 ALSA RGB zLib Theora FreeType2 JPEG PNG

Ubuntu Xenial, x86_64 bit, ita version of the game.
