### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by necros2k7** [residualvm/residualvm#1487]
[gui\ThemeEngine.cpp:862]: (error) Memory leak: srcSurface
[backends\cloud\dropbox\dropboxstorage.cpp:162]: (error) Memory leak: request
[engines\dialogs.cpp:211]: (error) Memory leak: title
[audio\decoders\qdm2.cpp:2049]: (error) Memory leak: gb

**Comment by Botje** [comment]
Thanks for reporting this. I think these files are all imported from ScummVM, our upstream project, unless marked with a `ResidualVM specific code` comment. Could you report them there? The changes will come back to ResidualVM eventually.

**Comment by necros2k7** [comment]
ok
