### ISSUE TITLE
STARK: April floating on the raft is not in sync with background sea

### ISSUE THREAD

**Issue by Snejp** [residualvm/residualvm#1495]
I came into this in location 50 00 in the beginning of chapter 7 when ship just wrecked.

![sea](https://user-images.githubusercontent.com/4354469/46043953-b8964880-c119-11e8-8186-2da366161dcf.gif)

Save game from English GOG version:
[tlj-win-043.zip](https://github.com/residualvm/residualvm/files/2417154/tlj-win-043.zip)

**Comment by sebastianrothe** [comment]
It seems to be fixed. Didn't occur to me on this location.
