### ISSUE TITLE
EMI: [AmigaOS4] Videos appear white

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1498]
ResidualVM 0.4.0git (Sep 11 2018 14:59:16)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

All of the videos appear as a white screen/window.
I don't know what the reason for this is, it worked before, but that was a long time ago.
It might be because the RGB ordering on my platform/SDL is different, but i'm only parroting what i heard somewhere else.

Is there anything i could try in my local build to make the videos play back correctly?

AmigaOS4 - PPC - BE - SDL
gcc (adtools build 8.1.0) 8.1.0

**Comment by raziel-** [comment]
No one with an idea?

I'd love to roll out a version which fully supports EMI (as the daily builds crash on AmigaOS4)

**Comment by raziel-** [comment]
Still the case with todays local build

**Comment by raziel-** [comment]
As soon as the white videos appear i get lots and lots of those
Quote:
WARNING: GL error 1282!

Which means INVALID_OPERATION if i got that right from a quick web search.

**Comment by Botje** [comment]
I cannot find any log statement in the code that would produce that. Can you get a stack trace to that warning print?

**Comment by raziel-** [comment]
I added it myself.

GLenum err;
to
backends/graphics/openglsdl/openglsdl-graphics.cpp, line 516
and
while ((err = glGetError()) != GL_NO_ERROR)
{
	warning("GL error %d", err);
}
to the same file, line 539

Trying to get more info on that error

**Comment by Botje** [comment]
That is already something. If you know this error happens during video, I would investigate the video playback code for errors then, using the techniques I posted in your forum topic.

**Comment by Botje** [comment]
The most probable cause of errors is the [prepareMovieFrame](https://github.com/residualvm/residualvm/blob/master/engines/grim/gfx_opengl.cpp#L1576-L1646) function, more specifically line 1626. Can you put a call to `glGetError`before and after that line? If your theory is correct there should be no errors before, and error 1282 after the glTexImage2D call.

**Comment by raziel-** [comment]
Correct.

I get
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 0!
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 0!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 1282!
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 0!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 1282!

where 1625 is set before the line and 1627 is set after.

Thanks for the help, btw

**Comment by Botje** [comment]
What is the value of `dataType` there?
Is it 0x8363 (GL_UNSIGNED_SHORT_5_6_5) or 0x8367 (GL_UNSIGNED_INT_8_8_8_8_REV)?

**Comment by raziel-** [comment]
Sorry, not sure what you need.
This are the values of glTexParameter, as they are appear in the code
WARNING: glTexParameteri, 1625: 2034561924 (3553, 10240, 9728)!

**Comment by Botje** [comment]
I need the parameters of glTexImage2D, not glTexParameteri.

**Comment by raziel-** [comment]
A few lines down i see a dataType at GLTexImage2D and it is
WARNING: dataType: 32821!

**Comment by Botje** [comment]
Can you change all assignments to `dataType` there to `GL_UNSIGNED_BYTE`? Just to see if it still produces those errors.

**Comment by raziel-** [comment]
WARNING: glTexImage2D(GL_TEXTURE_2D, GL_RGB, BITMAP_TEXTURE_SIZE, BITMAP_TEXTURE_SIZE, dataType): 2034561772 (3553, 6407, 256, 256, 32821)!

I'll try...

**Comment by raziel-** [comment]
Hmm, i'm sorry, but i messed up with the GLError, i had a loop where none should have been.

I have now put
			err = glGetError();
			warning("engines/grim/gfx_opengl.cpp, 1625 - GL error: %d", err);
before line 1626

and
			err = glGetError();
			warning("engines/grim/gfx_opengl.cpp, 1627 - GL error: %d", err);
after and i now get the exact opposite :-(

WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 0!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 0!
WARNING: glTexImage2D(GL_TEXTURE_2D, GL_RGB, BITMAP_TEXTURE_SIZE, BITMAP_TEXTURE_SIZE, dataType): 2034561772 (3553, 6407, 256, 256, 32821)!
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 1282!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 0!
WARNING: glTexImage2D(GL_TEXTURE_2D, GL_RGB, BITMAP_TEXTURE_SIZE, BITMAP_TEXTURE_SIZE, dataType): 2034561772 (3553, 6407, 256, 256, 32821)!
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 1282!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 0!
WARNING: glTexImage2D(GL_TEXTURE_2D, GL_RGB, BITMAP_TEXTURE_SIZE, BITMAP_TEXTURE_SIZE, dataType): 2034561772 (3553, 6407, 256, 256, 32821)!
WARNING: engines/grim/gfx_opengl.cpp, 1625 - GL error: 1282!
WARNING: engines/grim/gfx_opengl.cpp, 1627 - GL error: 0!

**Comment by raziel-** [comment]
But, anyway...changing the two instances of dataType
glTexImage2D and glTexSubImage2D
 to GL_UNSIGNED_BYTE makes the videos play again correctly...have to let them play through to see all of them, but it looks promising. :-)

**Comment by raziel-** [comment]
Confirmed videos play correctly again

Albeit low, but that might have been the case beforehand too, can't remember.

**Comment by raziel-** [comment]
Forget about slow, of course it's slow, if i still hvae the debug stuff in place :-(

Should i write PR and #ifdef those two lines for AmigaOS4?

**Comment by Botje** [comment]
Make the [assignment](https://github.com/residualvm/residualvm/blob/master/engines/grim/gfx_opengl.cpp#L1588) to `dataType` conditional instead

**Comment by raziel-** [comment]
I'm sorry, but I have no idea how to do that.
And before I further shame myself...
Would you do it, please?

**Comment by Botje** [comment]
Try with that branch?

**Comment by raziel-** [comment]
Thanks a lot.

I can't test for a couple of days...at work and away from my gear.
But it should work nonetheless, since it does exactly what I did locally with changing the two instances manually, doesn't it?

**Comment by raziel-** [comment]
I'll report back if there's should be a Problem.
