### ISSUE TITLE
MYST3: Game screen is not centered on Macbook Pro, in lower left corner and not fully scaling to the screen

### ISSUE THREAD

**Issue by typhirz** [residualvm/residualvm#1500]
Opening the game on a Macbook Pro (15-inch, Late 2016) is yielding this off-center game screen behavior, as seen in the screenshots. We've tried editing the `residualvm-override.ini` to change `gfx_mode`, `aspect_ratio`, and `filtering` settings, as these were the settings that were different from our Riven build in ScummVM, and nothing worked here.

![image 1](https://user-images.githubusercontent.com/24869005/46564174-9ee3c680-c8ba-11e8-8745-3b6f0c23d090.png)

![image 2](https://user-images.githubusercontent.com/24869005/46564224-dfdbdb00-c8ba-11e8-9e09-3bae7c29d800.png)

These are uncropped screen caps from the Macbook. 

We are not seeing this behavior on our iMacs, and one has a Retina display like this Macbook Pro.

**Comment by bgK** [comment]
Could you try the changes in that branch to see if they solve the issue? https://github.com/bgK/residualvm/tree/resizable-window.
They should make ResidualVM more resilient to drawable area size changes. In this particular case, I believe the fullscreen drawable area the OS is giving to the program does not match the requested size.
