### ISSUE TITLE
SDL.h not found.

### ISSUE THREAD

**Issue by Protarios** [residualvm/residualvm#1501]
Residualvm cannot be compiled in Manjaro Linux.
It complains "./backend/platfdorm/sdl/sdl-sys.h:144:10: SDL.h: File or directory not found".
SDL is installed.

The solution is to edit sdl-sys.h:
Line 144: #include <SDL.h> -> #include <SDL/SDL.h>
and
Line 147: #include <SDL_syswm.h> -> #include <SDL/SDL_syswm.h>

**Comment by Botje** [comment]
How did you configure residualvm? Did it pick up SDL from `pkg-config`? If so, what are the full parameters it specifies?

If I look at the Debian `libsdl1.2-dev` package, its `sdl.pc` adds extra CFlags:
```
Cflags: -I${includedir}/SDL -D_GNU_SOURCE=1 -D_REENTRANT
```

You should be able to achieve the same by adding a similar `-I..../SDL` to your `CXXFLAGS` environment variable when configuring

**Comment by Protarios** [comment]
Actually I tried to install via AUR. So might be misconfigured AUR package.
After searching for SDL issue, I found this solution of editing the source file.

**Comment by Botje** [comment]
I see you have already posted something on the ResidualVM AUR package. Does adding the SDL subdirectory to your CXXFLAGS solve your issues?

**Comment by Protarios** [comment]
Unfortunately still not fully successful in compiling.
Now stuck at a undefined reference "SDL_GL_Swapbuffer".
But seems to be different issue.

**Comment by Protarios** [comment]
I would close the issue, as it seems there is no issue at all with ResidualVM Code, but wrong settings of the AUR package.

**Comment by Botje** [comment]
Can you show the link command used? `make VERBOSE_BUILD=1` should show it. I bet it is missing `-lSDL`

**Comment by Protarios** [comment]
I simply edited the AUR package's PKGBUILD with the line above:

`# Maintainer: Joel Teichroeb <joel@teichroeb.net>

_pkgname=residualvm
pkgname=${_pkgname}-git
pkgver=r7048.de230485
pkgrel=1
pkgdesc="A cross-platform 3D game interpreter which allows you to play LucasArts' LUA-based 3D adventures"
arch=('i686' 'x86_64')
url='http://www.residualvm.org'
conflicts=('residualvm')
license=(LGPL)
depends=(sdl2 zlib alsa-lib libmad mesa libmpeg2 freetype2
         glew libjpeg-turbo)
CXXFLAGS="-I/usr/include/SDL2/"
makedepends=(git)
source=(git://github.com/residualvm/residualvm.git)
sha1sums=('SKIP')

pkgver() {
	cd ${_pkgname}
	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
	cd ${_pkgname}
	./configure --prefix=/usr --enable-release
	make
}

package() {
	cd ${_pkgname}
	make DESTDIR=${pkgdir} install
    install -Dm644 "dists/${_pkgname}.desktop" \
        "${pkgdir}/usr/share/applications/${pkgname}.desktop"
    install -Dm644 "icons/${_pkgname}.png" \
        "${pkgdir}/usr/share/icons/hicolor/256x256/residualvm.png"
    install -Dm644 "icons/${_pkgname}-big.png" \
        "${pkgdir}/usr/share/icons/hicolor/512x512/residualvm.png"
}`

**Comment by Botje** [comment]
is it possible the `configure` step did not find SDL2?

**Comment by Protarios** [comment]
Not unlikely. That was my thought, that maybe it might be expected in `/usr/local/include` instead of `/usr/include`
