### ISSUE TITLE
Errors compiling on Mac OS X

### ISSUE THREAD

**Issue by eisnerguy1** [residualvm/residualvm#1503]
So, I'm having issues compiling from the master.  I get this error message at the very end when running "make bundle":
```
clang: error: no such file or directory: '/opt/local/lib/libvorbisfile.a'
clang: error: no such file or directory: '/opt/local/lib/libvorbis.a'
clang: error: no such file or directory: '/opt/local/lib/libogg.a'
clang: error: no such file or directory: '/opt/local/lib/libmad.a'
clang: error: no such file or directory: '/opt/local/lib/libglew.a'
```

Not sure what I'm missing as I've been able to build residualvm from the source in the past.

Attached is the Terminal output when I ran ./configure & then make bundle
[residualvm_compile.txt](https://github.com/residualvm/residualvm/files/2498753/residualvm_compile.txt)

Any help would be greatly appreciated.

**Comment by Botje** [comment]
The root problem is that `make bundle` requires static libraries that can be linked to the final executable. A regular compilation can get by with dynamic libraries.

Your Mac has both Homebrew and MacPorts installed, and the paths it complains about come from MacPorts. You may need to add special options to `port install` to make it also compile static libraries. From what I found (I don't have MacPorts, only brew) You can do this by disabling the `no_static` option, so `sudo port install glew -no_static`.

Alternatively, you can install the libraries with brew, as @Snejp said. I just checked, and it always provides static libraries as well. If you choose the brew variants, it is best if you explicitly point the configure step to those libraries (in /usr/local as opposed to /opt/local), or uninstalled the MacPorts altogether.

**Comment by Botje** [comment]
Closing this issue, feel free to comment and/or reopen.
