### ISSUE TITLE
[Grim Fandango] Checksums for the Russian version from 7Wolf

### ISSUE THREAD

**Issue by StalinEXE** [residualvm/residualvm#1508]
**Version of ResidualVM**: 0.3.1
**Game**: Grim Fandango
**Version**: Retail 2CD Russian Localization (Voice + Subtitles) from 7Wolf with integrated 1.01 patch

There are the checksums for the one of the Russian translations for this game. Patch was integrated by 7Wolf, I didn't any changes to files. It is not so good like a fan made text translation from ENPY, but deserves to be supported by ResidualVM. At least for history,
```
The game in 'D:\Games\ResidualVM\Grim Fandango [7Wolf]\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the Grim Engine engine: grim-win

  {"VOX0001.LAB", 0, "b517dbb493679b1679036de1a1bfc8a5", 57180788},
```
Also, if you need I can upload this file to Mega or Google Drive for you.

**Comment by Botje** [comment]
Does this website have the patch separately? Grabbing isos from BitTorrent is a Rule 0 violation...

**Comment by StalinEXE** [comment]
I'm sorry, but I don't know about existing of Russian 1.1 patch by 7Wolf. Only as a part of main installation.
If you know what files shoud be changed after applying by patch, I can send them.

Also someone found sound files (without text) from that release and share them for Remastered version due to the compability.
Link to Steam Community: https://steamcommunity.com/sharedfiles/filedetails/?id=465771248 (in Russian)
Link to archive: https://yadi.sk/d/NKQ9foBGhNgMZ

I think it will be good compromise if you can't add support for the "original" cd release.
