### ISSUE TITLE
[The Longest Journey] Checksums for the Russian 2CD version from 7Wolf

### ISSUE THREAD

**Issue by StalinEXE** [residualvm/residualvm#1510]
**Game**: The Longest Journey ["Долгое Путешествие"]
**Type**: Retail 2CD version from 7Wolf
**Version**: Build 142
**ResidualVM**: 0.4.0git379-gfee73851 (Dec 3 2018 15:00:54)

There are checksums for the Russian retail 2CD version (voice + subtitles) of game. A lot of gamers say that this pirate translation is much better that official translation by 1C. IMHO, it has more nicer voices. I hope, you'll add support for this version of game.

```
The game in 'D:\Games\The Longest Journey [7Wolf]\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the Stark Engine engine: tlj-win

  {"x.xarc", 0, "a0559457126caadab0cadac02d35f26f", 3032},
  {"chapters.ini", 0, "8e08025c89575d2573c2edf0daa1cb34", 406},
```

**Comment by Botje** [comment]
As with the other 7wolf edition: is the language pack available as a separate patch?

**Comment by StalinEXE** [comment]
Unfortunatly I didn't find it, only with translation by 1C (and that archive is 1.2Gb).
Plus I found a language pack by Zone of Gamers (creators of a lot of their own translations for games) with only text inside, but I can't identify it now, because ZoG is not an author of translation.

I'll check again, but I think that 7Wolf's language pack as a patch doesn't exists.

**Comment by sev-** [comment]
I added detection, however, the game requires much more work: main menu image is different, fonts are different.

Since we merged with ScummVM, further discussion will continue at bugs.scummvm.org
