### ISSUE TITLE
[Escape from Monkey Island] Checksums + Error "Invalid magic reading script.tab: 61727470"

### ISSUE THREAD

**Issue by StalinEXE** [residualvm/residualvm#1511]
**Game**: Escape from Monkey Island
**Type**: Russian 2CD Retail Version from Fargus (subtitles only)
**ResidualVM**: 0.4.0git379-gfee73851 (Dec 3 2018 15:00:54)

I've tried to add Russian version from Fargus, but found two problems.

**First**: engine thinks that some files can be corrupted:
   **artAll.m4b** : 52111c719bcccacd4b4b8548007edd9c
    **local.m4b** : 6bd6582e9ab602c1f86c8593563cc9e5

**Second**: Invalid magic reading script.tab: 61727470
After this problem I can not start this game.

Please, find the attached screenshots.

![residualvm 2018-12-16 16-12-43-290](https://user-images.githubusercontent.com/1181085/50053981-fec5db80-014d-11e9-8a45-5c09447d5ea7.jpg)
![residualvm 2018-12-16 16-12-48-785](https://user-images.githubusercontent.com/1181085/50053982-ff5e7200-014d-11e9-862f-c0f7d16536ff.jpg)
![residualvm 2018-12-16 16-12-58-513](https://user-images.githubusercontent.com/1181085/50053983-ff5e7200-014d-11e9-9c85-1b83c296552b.jpg)

**Comment by StalinEXE** [comment]
If you need, I can split this bug-report to two different.
I've left it in one place, because they appeared with one launch of game.

**Comment by Botje** [comment]
There is currently no code to handle that tag (\x61\x72\x74\x70 = 'artp').
Is that tag present on other versions beside the russian version?

**Comment by Botje** [comment]
Looks like we need to do some reverse engineering then ...
Is this `script.tab` something fan-generated, or was it part of the commercial release?
If it is not fan-generated, we will have to track down an official copy first (sharing the file directly is a rule 0 "no piracy" violation... :/)

**Comment by StalinEXE** [comment]
> Is this script.tab something fan-generated, or was it part of the commercial release?

I checked on the commercial release, but applied one local patch for fixing one crash (bug of our translation). Everything else is "vanilla" without language packs and any other fixes, patches.

**Comment by Botje** [comment]
Any idea where/how we can get this commercial release if the Russian translation is not part of a separate patch?

**Comment by brainwachowski** [comment]
You need to know which files are replaced by Russian localization? Right? Sry my English, please.

**Comment by StalinEXE** [comment]
> 
> 
> Any idea where/how we can get this commercial release if the Russian translation is not part of a separate patch?

Due to the piracy type of distibution, you can't get it legally (there is no official publisher in our country for most of old games). Today we have to ways to play this game:

1) Find CDs on local flea markets (I didn't find this game on Ebay)
2) Download torrent file.

I didn't find information about fanat's language pack with this translation (or any other translation).

**Comment by StalinEXE** [comment]
> 
> 
> You need to know which files are replaced by Russian localization? Right? Sry my English, please.

If you sent this message to me, so... It is interesting information. If you tell, what files contains the Russian translation, I can send them to ResidualVM Team. If these files will be supported, I'll save them and publish for using with GOG-release.

**Comment by brainwachowski** [comment]
artAll.m4b and local.m4b. On Zone of Games there is a translation in the form of a separate patch (7-Wolf maybe?)

**Comment by brainwachowski** [comment]
I have these files

**Comment by StalinEXE** [comment]
Here the link: [Click](https://drive.google.com/open?id=17nT3GbzgT8Ldd6ExS_ppnoXj3EESjPw-) to Google Drive.

I've uploaded:

- **artAll.m4b** and **local.m4b** to _Data Files folder_;
- **patch from Fargus** (from readme: "fixes a crash at the australian mansion") to _patch_fargus folder_;
- **additional patch** from the how-to list of actions for starting this version of game (I think, it is an official patch without any changes, but I've included it just in case) to _patch_1_1 folder_.

Sorry, but it is the best what I can do now.

Also, I can send you a zip archive, that includes all files after installing without patching, but I know that it can be a piracy action, so I hope  that my Google Drive link will help you.

If you need something else, please tell me. I'll try to help.

**Comment by sev-** [comment]
Detection added, startup fixed. Please test. If you encounter further problems, please move on to https://bugs.scummvm.org
