### ISSUE TITLE
Myst 3 crash in Amateria age

### ISSUE THREAD

**Issue by Atrus1** [residualvm/residualvm#1514]
Hi, Myst 3 Exile crashes in Amateria age after I press Esc key at certain spot near magnetic ring it quits to console screen and displays the following error:

Console is ready
Debugger started, type 'exit' to return to the game.
Type  'help' to see a little list of commands and variables
ERROR: Magnet effect support file 32005 does not exist!

**Comment by Atrus1** [comment]
When I can expect this residualvm update release on Steam?

**Comment by Botje** [comment]
I don't know who manages Steam releases, but you can always download a nightly build from our website and use that.

**Comment by Atrus1** [comment]
Ok, thanks for quick reply.
