### ISSUE TITLE
[The Longest Journey] Crashes on spanish version

### ISSUE THREAD

**Issue by Al4ris** [residualvm/residualvm#1517]
The game crashes after a pair of events on spanish version.
The first is on chapter 2, when you ask the cups handler how to play, after the explanation the game crash. This action is not mandatory so you can continue the game without it.
The second is on chapter 13, after talk with April's father the game crash, this is mandatory and there's no option to skip it, so you can't continue to play and the game can't be finished.
I don't know if these crashes happens on english or other versions cause I haven't tested it.

**Comment by bgK** [comment]
Could you please you attach saved games just before for each crash to this issue?

**Comment by Al4ris** [comment]
I only have the savegame before April's father conversation on chapter 13.
[tlj-win-es-002.zip](https://github.com/residualvm/residualvm/files/2819379/tlj-win-es-002.zip)

**Comment by bgK** [comment]
Thank you for your report. Both crashes are fixed now. You'll be able to finish the game with the next daily build.
