### ISSUE TITLE
[The Longest Journey] Game crashed when asking cup handler "how do I play?"

### ISSUE THREAD

**Issue by arjabov** [residualvm/residualvm#1521]
Game crashed when asking cup handler "how do I play?" in chapter 2. Specificly after his line about the amulet. GOG.com version.

**Comment by bgK** [comment]
This is supposed to be fixed already (bug #1517). Can you please try it again with the latest daily build?

**Comment by arjabov** [comment]
I am sorry I didn't notice that issiue. Everything is ok now. This bug is not reproducible with the latest daily build.
