### ISSUE TITLE
MYST3: Music not playing correctly.

### ISSUE THREAD

**Issue by realXCV** [residualvm/residualvm#1522]
Go to Amateria. Its full theme should start playing (MA_THEME_full). Wait until it's finished. The "extended" version should start playing (MA_THEME_*). 

The problem is: that extended version is not playing correctly. One of the first sound that should start playing is MA_THEME_pad1 but it doesn't. On the other hand, MA_THEME_ghost plays way too often.

This issue is not specific to that particular track.

**Comment by bgK** [comment]
I've made some fixes related to the sound script system. Please confirm the tracks are playing as intended.

**Comment by realXCV** [comment]
Way better.
