### ISSUE TITLE
GRIM: [AMIGAOS4] Software renderer wrong colors

### ISSUE THREAD

**Issue by raziel-** [residualvm/residualvm#1523]
ResidualVM 0.4.0git (Feb 12 2019 22:07:48)
Features compiled in: Vorbis MP3 RGB zLib MPEG2 Theora FreeType2 JPEG PNG 

The software renderer displays false colors (see screenshot)
The light in Manny's office is pink, Manny (and all other characters) itself have switched colors.

Grim Fandango (Windows/CD)

AmigaOS4 - PPC - SDL - BE
gcc (adtools build 8.1.0) 8.1.0

https://i.postimg.cc/yd6SjqSH/Residual-VM-Software-3-D-Render-000.png

**Comment by raziel-** [comment]
So, where in the code should i look to possibly fix this?

**Comment by aquadran** [comment]
it's not just amigos, It looks like BE endian issue somewhere.
