### ISSUE TITLE
invisible characters (Ive tried old solutions and they didnt work)

### ISSUE THREAD

**Issue by Askmewho** [residualvm/residualvm#1524]
Hi devs! a couple of months ago i compiled a GL ES residualvm than runs grim fandango and escape from monkey island pretty good on the pi under mesa drivers. Recently, i could make a residualvm with full opengl implementation and even The Loungest Journey its really playable on this little and cheap board. the problems occurs in grim and on monkey island. if i open a saved game itthe characters may appeard..but if i start a game they are never on scene. maybe I should compile Lua? dont know. 
ive compiled the master and sometimes the last release, but i keep on master because the latest commits reffers on longest journey...

my youtube channel if you want to see how it performs:
mesa rocks!!! btw... its seams tha full opengl performs better on monkey 4 and grim...but i couldnt call it a better performance if the characters arent there haha

https://www.youtube.com/channel/UCgfQjdc5RceRlTGfuthBs7g

my config file:

[residualvm]
filtering=false
autosave_period=300
mute=false
speech_volume=192
use_arb_shaders=false
gui_use_game_language=false
talkspeed=179
renderer=opengl_shaders
subtitles=true
fullscreen=true
updates_check=0
gui_browser_show_hidden=true
gui_renderer=antialias
browser_lastpath=/media/pi/RASPBERRY/The Longest Journey
sfx_volume=56
music_volume=38
speech_mute=false
lastselectedgame=grim-win-es
vsync=true
aspect_ratio=false
versioninfo=0.4.0git
gui_theme=builtin
gui_language=es_ES

[monkey4-win-es]
movie_subtitles=true
filtering=false
description=Escape From Monkey Island (Windows/Spanish)
mute=false
speech_volume=192
check_gamedata=false
use_arb_shaders=false
datausr_load=false
renderer=opengl_shaders
path=/home/pi/Monkey4
fullscreen=true
gameid=monkey4
language=es
gui_saveload_last_pos=0
fullscreen_res=desktop
sfx_volume=192
music_volume=163
show_fps=true
platform=windows
vsync=true
aspect_ratio=false
guioptions=sndNoMIDI gameOption1 gameOption2 lang_Spanish

[grim-win-es]
description=Grim Fandango (Windows/Spanish)
mute=false
speech_volume=192
check_gamedata=false
use_arb_shaders=false
game_devel_mode=false
datausr_load=true
savepath=/home/pi/.local/share/residualvm/saves
path=/home/pi/Grim Fandango
subtitles=true
gameid=grim
language=es
sfx_volume=56
talkspeed=153
music_volume=38
show_fps=true
platform=windows
gamma=0
guioptions=sndNoMIDI gameOption1 gameOption2 lang_Spanish
speech_mute=false
last_saved_game=grim00.gsv
movement=Camera

[tlj-win]
filtering=false
description=The Longest Journey (GOG/Windows/English)
extra=GOG
enable_assets_mod=true
use_linear_filtering=true
renderer=opengl_shaders
path=/media/pi/RASPBERRY/The Longest Journey
fullscreen=true
gameid=stark
language=en
platform=windows
vsync=true
aspect_ratio=false
guioptions=sndNoMIDI gameOption1 gameOption2 lang_English

my log:

i@pi:~ $ residualvm
INFO: OpenGL Vendor: Broadcom
INFO: OpenGL Renderer: VC4 V3D 2.1
INFO: OpenGL Version: 2.1 Mesa 18.3.3
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 1
INFO: OpenGL Stencil buffer bits: 8
INFO: GLEW Version: 2.2.0
INFO: GLSL version: 1.20
User picked target 'grim-win-es' (gameid 'grim')...
  Looking for a plugin supporting this gameid... Grim Engine
  Starting 'Grim Fandango'
INFO: OpenGL Vendor: Broadcom
INFO: OpenGL Renderer: VC4 V3D 2.1
INFO: OpenGL Version: 2.1 Mesa 18.3.3
INFO: OpenGL Red bits: 8
INFO: OpenGL Green bits: 8
INFO: OpenGL Blue bits: 8
INFO: OpenGL Alpha bits: 8
INFO: OpenGL Z buffer depth bits: 24
INFO: OpenGL Double Buffer: 0
INFO: OpenGL Stencil buffer bits: 8
INFO: GLEW Version: 2.2.0
INFO: GLSL version: 1.20
WARNING: Lua_V1::SetGamma, implement opcode, level: 0.000000!
WARNING: !!!! Trying to call MakeSectorActive without a scene!
WARNING: !!!! Trying to call MakeSectorActive without a scene!
WARNING: !!!! Trying to call MakeSectorActive without a scene!
WARNING: !!!! Trying to call MakeSectorActive without a scene!
WARNING: !!!! Trying to call MakeSectorActive without a scene!
WARNING: Stub function: Lua_V1::GetCameraLookVector!
WARNING: Stub function: Lua_V1::GetCameraLookVector!
WARNING: Stub function: Lua_V1::GetCameraLookVector!
WARNING: Stub function: Lua_V1::GetCameraLookVector!
WARNING: Lua_V1::SetGamma, implement opcode, level: 0.000000!

**Comment by Botje** [comment]
Could you let the game run under `gltrace` (pick the game, hit 'start game in the menu', skip the intro cinematics) and provide us with the output file? That might give some clues as to what goes wrong.

**Comment by Askmewho** [comment]
I couldn't compile gltrace, just apitrace and it doesn't output log. So, I will figured out soon how to do that. Opengl + shadders runs much better than opengl. Myst 3 works great. https://www.youtube.com/watch?v=AZipdKSSLFY I forget to set full screen.

**Comment by Askmewho** [comment]
The are many gltrace programs. You are asking for a particular mesa tool called gltrace?  Oranother one ?

**Comment by Botje** [comment]
Sorry, I meant [apitrace](https://github.com/apitrace/apitrace).

**Comment by Askmewho** [comment]
Ok!!!

**Comment by Askmewho** [comment]
sorry for that. a mistake. this trace its on grim under opengl + shaders and arb activated, because that doesn't solve the issue  . As i said the performance its much better on opengl + shader on emi and grim... but i could use it one any of them because this problem. meanwhile, i could run monkey4 on opengl lonely and the characters are there. https://drive.google.com/file/d/1Jo9WFSy7Xu4Gtcjh0x2aRM7Kvnpht4KP/view?usp=sharing

**Comment by Botje** [comment]
Running the trace on my desktop doesn't point out the issue; it just works ... We'll need someone with a raspberry Pi to find out what is wrong.

**Comment by Askmewho** [comment]
Ok. I will try a partial solution having 2 resdualvms than targets differents opengl libs linking to differents opengl libs obviously

**Comment by ccawley2011** [comment]
This problem occurs on Android as well. Can this issue be reopened?

**Comment by Askmewho** [comment]
@ccawley2011  did you try to set "use_arb_shaders=false" on the config file?? Just to be sure if your problem its related and unsolved like mine.
