### ISSUE TITLE
Website does not use https

### ISSUE THREAD

**Issue by joveian** [residualvm/residualvm#1534]
It is poor security practice to download and run unsigned binaries from the internet (this allows someone who can intercept the connection to change the binary), however the ResidualVM website does not fully support https at this point (mixed content).  Ideally the whole site should be on https, although if at least the download links are https then it would be possible to check the download url.  The downloads do seem to work over https so changing the download urls would be a good start if it isn't trivial to fix the whole site.

**Comment by Botje** [comment]
Seems like a small change to `data/downloads.xml` in the residualvm-web repo should suffice.

**Comment by Botje** [comment]
residualvm/residualvm-web#11 should fix it.

**Comment by aquadran** [comment]
Fixed with above mentioned fix plus fixed url on website which prevented enabling https on main page.
