### ISSUE TITLE
The Longest Journey with German patch not playing german samples

### ISSUE THREAD

**Issue by TheRealDadbeard** [residualvm/residualvm#1539]
The whole game is in german. All the subtitles everything after the patch. Just the voices are in english. Sometimes there is german voices like when looking at the "secret" door next to the cafe.

Starting the game with the exe makes them work properly but is a bad experience.

**Comment by bgK** [comment]
Is there any reason why you are not using one of the official German versions of the game?

I don't think ResidualVM should support legally questionable patches such as the one you are referring to.

**Comment by TheRealDadbeard** [comment]
Omg not this again please. It's abandonware, the only pockets I'm filling with is the few people that sell original CDs on Ebay, not the ones wo actually made it.

I bought it from GOG and patched it with a german patch. Nobody cares. I'm not going to look over ebay to buy CD version. Heck, I don't even have a CD drive!

**Comment by bgK** [comment]
Look, I really don't want to have to deal with all the half-assed patched versions of the game floating around the internet.
There is no difference between downloading an illegal patch and illegally downloading a game to my eyes.

**Comment by TheRealDadbeard** [comment]
When I buy the game now (Original CD 4CD version) and the german version does not work will you fix it? Are my savegames going to work still?

**Comment by bgK** [comment]
The 4 CD German version is supposed to be working with ResidualVM already (the 2 CD / DVD version as well).
Savegames are not compatible between versions, but you may try your luck as it sometimes happens to work.

**Comment by TheRealDadbeard** [comment]
Going to buy it and then play quick to my old state with a walkthrough if savegames are broken.

**Comment by TheRealDadbeard** [comment]
Just got the 4CD version, used the installer, apllied the latest patch for the game and could load my last savegame perfectly fine. Everything is in german now.

**Comment by TheRealDadbeard** [comment]
Okay so I don't want to open a new issue but after playing I found out that I had missing cutscenes and saw that those were not copied by the installer.

Trying to copy them manually makes it stall. Could this be some kind of copy protection on the CDs? There are rings on them, any ideas how to get the files off of them?

Thanks!
