### ISSUE TITLE
EMI: No Music On Steam Version 

### ISSUE THREAD

**Issue by z1pperm0nkey** [residualvm/residualvm#1541]
The steam version of the game only includes 1 FullMonkeyMap.imt. I have tried replacing the single file with the two from the cds and renaming them.as instructed. I have also tried manually splitting the fullmonkeymap file included with steam into two files as it seems to be just the two put together into one. Still no music. I am not receiving any error messages. I am running this on retropie through a raspberry pi 3 b.

**Comment by Botje** [comment]
I did not mean to auto-close this just yet. Can you try recompiling with an updated HEAD? Also, did you build with libmad support? That is required for the soundtrack.

**Comment by z1pperm0nkey** [comment]
Hey I actually meant to close this. I was able to get music to work by using the map files from the cd version. Although support for the combined map file is nice for future users! Sorry I didn't update this and thank you for looking into it and fixing it for future users!
