### ISSUE TITLE
[The Longest Journey] HD Mod Fullscreen problems

### ISSUE THREAD

**Issue by GrimChaos** [residualvm/residualvm#1543]
In windowed mode it pulls in the HD files from the mods folder but switching to full-screen it does not.  Even switching (alt-enter) to full-screen from windowed doesn't work.

**Comment by bgK** [comment]
It's possible the root cause for this issue was the same as #1547. Could you please try this build of ResidualVM and see if the issue is resolved:
https://ufile.io/o7nchg9w

**Comment by bgK** [comment]
Closing due to lack of answer from OP. Please re-open if you encounter that issue.
