### ISSUE TITLE
[The Longest Journey] The game seems to be an unknown game variant.

### ISSUE THREAD

**Issue by ifride** [residualvm/residualvm#1548]
Hi, i'm using the residual version 0.4 (18 may) but when I load the game this message comes out:

Matched game IDs for the Stark Engine engine: tlj-win

  {"x.xarc", 0, "de8327850d7bba90b690b141eaa23f61", 3032},
  {"chapters.ini", 0, "9a81ea4e6f5b84511dd4e56d04a64e2e", 498},

The game is The longest journey gog version with italian translation. 
Thank you!

**Comment by somaen** [comment]
GoG only has the game in english and polish. Is this a third party translation?

**Comment by ifride** [comment]
It is the official italian translation taken from the original version of the game (in Italy were released  two versions: the 4 cd and the most updated dvd ones).
Eventually, the gog version came unexpectedly from the 4 cd version and not from the dvd one.

**Comment by somaen** [comment]
How is this different from the disc version?

I’m a bit confused, why not just use the disc only? Is there some benefit to mix?

**Comment by ifride** [comment]
The bugfix. The cd version is older and without update. 
I'm using the gog version with italian translation because with Residual i can use the mods for hd texture and anti aliasing. 

I think that the problem with Residual is that it doesn't recognize the italian version.

**Comment by somaen** [comment]
Can you try with just the Italian discs, to verify that the issue is that we can’t detect the Italian version?

I’d rather we check that before looking into mixed versions.

**Comment by federicorosso1993** [comment]
I was able to start the italian version of the game with ResidualVM just by changing the chapters.ini from the italian version to the gog english version, I tried to change the detection.cpp and create a pull request (this is the first time I try something like this).

**Comment by ifride** [comment]
Thank you Federico!

**Comment by bgK** [comment]
The Italian versions were added in #1550. Note that to use the mixed English / Italian version, you'll probably need to remove the English speech files. And even then things may break.
