### ISSUE TITLE
[The Longest Journey] Problems with animations

### ISSUE THREAD

**Issue by OleLjosland** [residualvm/residualvm#1549]
Hi, I've been really enjoying The Longest Journey in ResidualVM, it works great, especially with the new HD mod.

I've noticed a few things with the animations in the game though (I'm using the Steam version):
- Some animations fail to complete, or are skipped altogether. Some notable examples include the cups handler in the marketplace shuffling the cups, April spinning when she receives her new clothes at The Journeyman and April lifting the mole man to the window in the gribbler's lair. Note that the animations do work correctly if you cancel the preceeding dialog with the Escape-button, but not if you let the dialog end on its own.
- April does her idle animation during conversations, which does not occur when running the game outside ResidualVM.
- There is a notable delay whenever Zack enters his room.

Hope this helps, and keep up the awesome work!

**Comment by bgK** [comment]
Thanks for your report. It was indeed helpful. I've fixed points 1 and 2.
If you find other problems please open one bug report per issue, bug reports with multiple issues are kind of a pain to manage.

**Comment by OleLjosland** [comment]
Great, got it!
