### ISSUE TITLE
 [The Longest Journey] Objects under water have shadows

### ISSUE THREAD

**Issue by OleLjosland** [residualvm/residualvm#1552]
If the option to display shadows is selected, 3D objects under water (in chapter 7), such as the maerum queen, the snapjaw fish and April carrying the spear, have shadows. This does not happen when the game runs without ResidualVM.

**Comment by ogromanas** [comment]
![IMG_20190602_215319](https://user-images.githubusercontent.com/2190247/58809320-fdb13980-861b-11e9-98a8-d6fbac045a9d.jpg)

**Comment by bgK** [comment]
Good catch!

**Comment by ogromanas** [comment]
The shadow is on 2/3 of the queen 😉
