### ISSUE TITLE
TLJ: ResidualVM cannot read saves generated from the original game

### ISSUE THREAD

**Issue by alexwald** [residualvm/residualvm#1554]
during my gameplay of modded TLJ, I've stumbled upon a very rare bug in Chapter 4, in which the City Green (a game location) does not appear on the map. I was able to find a savegame which loads successfully when launching the game through the original .exe, but crashes when I try to load it through residual. any siggestions?

**Comment by bgK** [comment]
The save format is not the same in ResidualVM and in the original engine. So it's not supposed to work.

I've attached a save from the beginning of chapter 4 to help you. However, I'd like to investigate why the game won't allow you to see Abnaxus. Do you know how it happened? Could you please attach a broken save?

[tlj-win-106.zip](https://github.com/residualvm/residualvm/files/3262966/tlj-win-106.zip)

**Comment by alexwald** [comment]
many thanks. 
the save is in front of the enclave. if you enter the map. you'll see there is no city green location. I can't tell precisely, how it happened - I've chatted with abnaxus at the journeyman inn, where he is supposed to invite April for a visit, but the map icon is missing. since I can't talk to Abnaxus, I cannot get topics to investigate at the enclave and thus cannot progress.

https://www.dropbox.com/s/b7jvbl80g5so211/tlj-win-003.tlj.zip?dl=0

**Comment by bgK** [comment]
I don't know what could have happened to cause that bug. The only place that particular variable `KnowledgeCityGreen` is set is when meeting Abnaxus in the Journeyman Inn:

```rust
let ScriptDiaryScript = (Level idx 0) (KnowledgeSet idx 1) (Container idx 1) (Script idx 3)
let ScriptMouthOnStrangeCreature = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 17) (PATTable idx 0) (Script idx 1)
let SpeechThankYou = (Level idx 59) (Location idx 0) (Container idx 3) (Script idx 1) (Dialog idx 1) (Speech idx 0)
let ScriptSpeakingWithAbnaxus = (Level idx 59) (Location idx 0) (Container idx 3) (Script idx 6)
let PATTableStrangeCreature = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 17) (PATTable idx 0)
let ItemApril = (Level idx 0) (Item idx 0)
let AnimBow = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 17) (Anim idx 4)
let ScriptGettingTired = (Level idx 59) (Location idx 0) (Container idx 3) (Script idx 7)
let KnowledgeInvitationFromAbnaxus = (Level idx 0) (KnowledgeSet idx 4) (Knowledge idx 30)
let BookmarkToDarkness = (Level idx 59) (Location idx 0) (Layer idx 1) (Container idx 1) (Bookmark idx 0)
let ItemApril = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 8)
let KnowledgeCityGreen = (Level idx 0) (KnowledgeSet idx 3) (Knowledge idx 19)
let StringAbnaxus = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 17) (PATTable idx 0) (String idx 0)
let DialogStrangeWords = (Level idx 59) (Location idx 0) (Container idx 3) (Script idx 1) (Dialog idx 0)
let ItemAbnaxus = (Level idx 59) (Location idx 0) (Layer idx 1) (Item idx 17)
 
begin()
if (isItemNearPlace(ItemApril, ItemAbnaxus, 200)) {
	itemSetActivity(ItemApril, 1, 0)
	setInteractiveMode(0)
	itemLookAt(ItemAbnaxus, ItemApril, 1, 1)
	showPlay(SpeechThankYou, 1)
	itemLookAt(ItemApril, ItemAbnaxus, 1, 1)
	playAnimation(AnimBow, 0)
	dialogCall(DialogStrangeWords, 1)
	diaryEnableEntry(KnowledgeInvitationFromAbnaxus)
	scriptCall(ScriptDiaryScript, 0)
	pATChangeTooltip(PATTableStrangeCreature, StringAbnaxus)
	scriptEnable(ScriptMouthOnStrangeCreature, 0)
	scriptEnable(ScriptSpeakingWithAbnaxus, 0)
	scriptEnable(ScriptGettingTired, 1)
	item3DWalkTo(ItemAbnaxus, BookmarkToDarkness, 1)
	itemEnable(ItemAbnaxus, 0)
	knowledgeSetBoolean(KnowledgeCityGreen, 1)
	setInteractiveMode(1)
	end()
} else {
	end()
}
```

And as the game is not interactive until the value is set, it's not supposed to be possible to exit of the script early.

**Comment by alexwald** [comment]
at least I know I'm not alone as a found references to the same bug in two more places:
http://forums-archive.longestjourney.com/showthread.php?10158-City-Green-missing-from-Chapter-4-No-previous-save-to-reload

and also:
http://forums-archive.longestjourney.com/showthread.php?8507-Chapter-4-City-Green-missing
