### ISSUE TITLE
The Longest Journey (Game Completed 100%)

### ISSUE THREAD

**Issue by ogromanas** [residualvm/residualvm#1555]
Game completed in the Spanish version 4CD, with HD mod and without HD mod. Minimal problems: Shadows of Maerum and Alatien (shadows in 1/3 of the body) Issue # 1552 and Issue # 1551
Great work !! Thank!!

**Comment by bgK** [comment]
Thanks for the kind words! Both issues are fixed now.

**Comment by alexwald** [comment]
+1. I've finished the game last week with the HD mod. what an epic.
