### ISSUE TITLE
TLJ: chapter 4 - Strange creature wont talk

### ISSUE THREAD

**Issue by audricd** [residualvm/residualvm#1557]
Hello,
I am running 0.4 git Jun 15 2019 9:00:00 with TLJ (Steam version with fonts from GOG) so far flawlessly for the most part. My host is Debian 9.

https://youtu.be/ZjunfDjpelg

I have encountered a few times where after an ingame cutscene, where a loop sound effect would not stop. So far it has not been game breaking. Until now. What you see here is the beginning of chapter four, entering the Journeyman Inn. After talking to the owner, she goes away. Walking away. And that is precisely the tap tap we keep hearing in the background although she is long gone. Now I am supposed to talk to the "strange creature". But as you can see, it wont budge. I have restarted the game three times. The tap tap loop wont break!

~~Of course, I am going to try updating. That is rule number one. Regardless that fixes it or not, I wanted to report it.~~ I was already on the latest build unfortunately..! 

Thank you.

**Comment by bgK** [comment]
Thanks for your report. Could you please attach your save file here?

Also, would you mind trying if the save from this comment allows you to progress:
https://github.com/residualvm/residualvm/issues/1554#issuecomment-499616287

**Comment by audricd** [comment]
Thank you for your reply.

Here is my save file:
[TLJ - residualvm bug1557.zip](https://github.com/residualvm/residualvm/files/3317797/TLJ.-.residualvm.bug1557.zip)

And yes! The linked saved file allows me to load the game and continue, although I dont know where I am, clearly past where I was stuck as I have never seen the place I landed.

**Comment by audricd** [comment]
My bad, I just realized I downloaded the second save in the link that was provided. Apologies. 
But your save, https://github.com/residualvm/residualvm/files/3262966/tlj-win-106.zip does not load for me? I am a bit speechless. So I will leave the screenshot do the talking for me:

![image](https://user-images.githubusercontent.com/10130344/60192970-256c7980-9837-11e9-99c3-42cb2e8e8194.png)

To make sure any previous saves wouldnt affect, I have backed them up / moved them and just leave yours, as it just doesnt show up in game. Am I doing this wrong?

Thank you,

**Comment by bgK** [comment]
Oh. The save use the slot 106 which too high to be accessible from the in-game save menu. You can rename the file to a lower number. Alternatively you can load the save from ResidualVM's own menu.

**Comment by audricd** [comment]
My bad again, I had no idea. Okay so that drops me exactly where you intended to! Thank you for that!

Now, should I close this issue? I mean this definitely solves the issue for me. The game being in beta not only means bugs are to be expected but, it gives users like me the opportunity to help solving them. I imagine you plan on a more elegant solution for this bug to drop a save file. I would be more than happy continuing helping in any way I can with this issue. And any other than I find too! 

Regardless, thank you so much! Now I can resume my enjoyment discovering this game further!

**Comment by bgK** [comment]
Let's keep this bug open. I indeed would like to fix it properly.

Please keep opening bugs for other issues you find.
