### ISSUE TITLE
64-bit version of ResidualVM for macOS

### ISSUE THREAD

**Issue by Thunderforge** [residualvm/residualvm#1558]
I just downloaded the [latest Intel daily build](https://www.residualvm.org/downloads/#daily) of ResidualVM (2019-06-25), and the System Information tool on macOS notes that it is a 32-bit app.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/6200170/60069087-25556800-96d7-11e9-8540-df4ca454cb18.png">

The upcoming macOS 10.15, which will come out in 3-6 months, [will not support 32-bit apps](https://www.laptopmag.com/articles/macos-10-15-warning-32-bit-apps), meaning that if ResidualVM doesn't start distributing a 64-bit app, it will be unusable on the latest version of macOS.

Please consider creating a 64-bit distribution of ResidualVM before macOS 10.15 is released so that Mac users can continue to use it.

**Comment by Thunderforge** [comment]
macOS 10.15 "Catalina" is [going to be released this month](http://osxdaily.com/2019/09/11/macos-catalina-to-be-released-in-october/). If a 64-bit Mac version isn't released soon, users of the latest version of the OS won't be able to use ResidualVM at all because this version won't run 32-bit apps at all.

**Comment by Botje** [comment]
The Travis pipeline should be 64-bit by default. Just need to get those builds published somewhere...

**Comment by Thunderforge** [comment]
macOS 10.15 "Catalina" is now released, and as promised, it does not run any 32-bit apps.

Is there something that someone like me can help with to get this converted?

**Comment by Botje** [comment]
The PR I merged today produced the first 64bit build of ResidualVM. It still has a dynamic dependency on libSDL2 though...

**Comment by Thunderforge** [comment]
@Botje I'm pleased to hear this! Is there somewhere I can download this 64-bit build to test it on my Mac?

**Comment by Botje** [comment]
Can you try the build at https://sgaap.be/ResidualVM-snapshot.dmg ? This was produced from my most recent PR and launches on my 10.14.6 machine.

**Comment by Thunderforge** [comment]
@Botje Launches without issue on 10.5.1. I didn't have any games handy to try running them, but at least the app is good.

**Comment by ShakeItOff89** [comment]
> Can you try the build at https://sgaap.be/ResidualVM-snapshot.dmg ? This was produced from my most recent PR and launches on my 10.14.6 machine.

I've been looking for a 64-bit build of this for MacOS. I can confirm it successfully runs The Longest Journey (I have only played the prologue so far). Thank you.

**Comment by Thunderforge** [comment]
So it appears that this 64-bit version works. What can we do to make this a "real" release able to be downloaded on the ResidualVM website?

**Comment by Botje** [comment]
#1582 should get merged, and we should either figure out a way to upload to residualvm.org/downloads OR rewrite the daily download page.

**Comment by aquadran** [comment]
Fixed
