### ISSUE TITLE
TLJ: Please add Hungarian localisations

### ISSUE THREAD

**Issue by melanie1974** [residualvm/residualvm#1559]
The game in 'The Longest Journey\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the Stark Engine engine: tlj-win

  {"x.xarc", 0, "a0559457126caadab0cadac02d35f26f", 3032},
  {"chapters.ini", 0, "790b51a88b5493bff5168a77738e0e84", 451},

**Comment by bgK** [comment]
Hi,

It's the first time I hear of a Hungarian version. Do you have more details about that version? Does it come on 4 CDs or on 2 CDs / a DVD?

**Comment by melanie1974** [comment]
Hello Again!
The hungarian subtitles is a non commercial fan project! It Works the v1.60 CD or DVD versions, and the Steam and GOG actual versions too. You are right, full Hungarian version never released! When I add the original English version to ResidualVM everything Works fine! But when I try to ad the Hungarian subtitled files I get the error message! (I have the latest GOG English version).
Thank You! (and sorry for my English...)
melanie

**Comment by raziel-** [comment]
@melanie1974

Is there a download (link?) for that hungarian subtitle version somewhere?

**Comment by melanie1974** [comment]
The first one:
http://dl.magyaritasok.hu/thelongestjourney/tlj-hun_1.23s.rar
unpack and install! (the installer support only v1.60 English version, and GOG version!!!)
Anything else:
http://mwserv.sytes.net/tlj/tlj_hun.rar
unpack to: The Longest Journey path! Not support the GOG version!

**Comment by melanie1974** [comment]
Hi!
Some solutions  (GOG version only!): Before I install the hungarian subtitles I made a backup copy the chapters.ini. After the installation the chapters.ini is Hungarian, but i overwrite the original English, from the backup copy. So I can add the game to ResidualVM! (only the chapters name get back to English!!!).
I hope this worked another testers!
Have a nice Day!

**Comment by sev-** [comment]
@melanie1974 Added
