### ISSUE TITLE
please add stark shaders automatically in build folder

### ISSUE THREAD

**Issue by legluondunet** [residualvm/residualvm#1571]
Hello,
I compile manually ResidualVM from git.
I follow this steps:

`git clone https://github.com/residualvm/residualvm.git
cd residualvm
mkdir build
cd build
../configure
make -j4`

Then if I launch "The long journey" game, ResidualVM gave me an error message: it didn't find stark shaders...
I have to manually copy this folder in my build/engines/stark folder.
Could you add this step in the compile script?

**Comment by Botje** [comment]
You should actually `make install` and run the global ResidualVM binary.

**Comment by legluondunet** [comment]
I directly run my compiled program from their git folder (build folder).
Perhaps you could add a configure option to make ResidualVM more portable? Like "run in current build folder without install"?

**Comment by Botje** [comment]
That is already served by the `--prefix` argument to `./configure`. You can just point it to a subdirectory of the build directory (or your home directory) and `make install`.

**Comment by legluondunet** [comment]
I will give it a try, thanks.
