### ISSUE TITLE
GRIM: Residual doesn't recognize pt-br files / Can't pass the pigeon puzzle

### ISSUE THREAD

**Issue by caiot5** [residualvm/residualvm#1573]
Hello ResidualVM Team,
I would like to report some issues I'm facing whenever I try to play Grim Fandango (pt-br [portuguese brazil] version).
I have the jewel case pt-br edition and when I try to load it complains about the md5sums being incorrect:
WARNING: 'vox0004.lab' may be corrupted. MD5: '2be5b0cc13a83f59945d31080b0949bb'!
WARNING: 'vox0003.lab' may be corrupted. MD5: 'e107073a05f588df0c057b594c28b50e'!                                       
WARNING: 'vox0002.lab' may be corrupted. MD5: '0748f44ee1e67b6d7555a644a1fa43ce'!                                       
WARNING: 'vox0001.lab' may be corrupted. MD5: '31f261f87cc4854055c1ca1afddf677e'!                                       
WARNING: 'vox0000.lab' may be corrupted. MD5: 'd48832ea234015e74590654ada02e163'!                                       
WARNING: 'movie04.lab' may be corrupted. MD5: 'd9bfe59690a5de0500d18e29cdaa293f'!                                       
WARNING: 'movie03.lab' may be corrupted. MD5: '5280486c3aee4fb1f9dcbc289f5f58b9'!                                       
WARNING: 'movie02.lab' may be corrupted. MD5: '000185c50bbf09bcd7421667d46a9e5c'!                                       
WARNING: 'movie01.lab' may be corrupted. MD5: 'a88876b3347106d49b733c178f0d606a'!                                       
WARNING: 'data001.lab' may be corrupted. MD5: '94a442937bd4a4e3f459da6ddd3c7482'!                                       
WARNING: 'credits.lab' may be corrupted. MD5: '368baa2f319a72278035095e4f4a4466'!                                       
WARNING: 'local.lab' may be corrupted. MD5: '04d76cbbd5e603f35318bebb64f69378'!  

If I try to ignore that, when I get to the pigeon puzzle when climbing the last ladder where it is supposed to play a movie or so, it hangs with an error message:

WARNING: Comma in model components not supported: mannysuit.3do,1!                                                      WARNING: Could not find bitmap <none>!                                                                                  WARNING: Could not find bitmap <none>!                                                                                  Expected `costume v0.1', got EOF on file pigeon_os.cos!

**Comment by sev-** [comment]
hi @caiot5. ResidualVM has been merged with ScummVM. This issue has been carried over to https://bugs.scummvm.org/ticket/11887

We need your feedback there.
