### ISSUE TITLE
The Longest Journey FR 4CD: subtitles font is different?

### ISSUE THREAD

**Issue by legluondunet** [residualvm/residualvm#1575]
Hello,
I just installed TLJ FR 4CD, the font used for subtitles are different than the english version, is this normal? As I 'm not a Windows user, I can not verify directly.

capture screen from TLJ FR 4D:
![Capture d’écran de 2019-09-11 00-51-38](https://user-images.githubusercontent.com/325405/64656020-56b81700-d42e-11e9-9c05-3d0484fec518.png)

capture screen from TLJ EN GOG:
![Capture d’écran de 2019-09-11 00-53-34](https://user-images.githubusercontent.com/325405/64656128-aeef1900-d42e-11e9-952d-30cd06a0902e.png)

Thank you for your help.

**Comment by webfischi** [comment]
There have been different fonts in all different versions of the game. In the german version the subtitle font was Arial. In the gui.ini you can use any font and size you like. There is also an almost complete list of what is changing which text:

bigfont = conversation text, intro text, buttons (yes/no)
smallfont = tooltips

font0 = ?
font1 = ?
font2 = copyright text in startup screen
font3 = savegame description, (some) menu headings
font4 = menu items
font5 = conversation log
font6 = diary
font7 = books in the library

You also should change font size depending on your language settings. I'd set bigheight to 18 so the fourth line won't cut the bottom from letters like j, p, g, y, q.

**Comment by legluondunet** [comment]
So it's not a RVM issue, thank you for your answer.
