### ISSUE TITLE
TLJ HD . Bug on the subway

### ISSUE THREAD

**Issue by Askmewho** [residualvm/residualvm#1580]
Hi, the bug its simply than when you are o  the scanner it didnt allow you to push the bottons. I had to close my residualvm (master compilation) dont know if this happens kn non modded game. Cheers.

**Comment by bgK** [comment]
Hi,

Thanks for your report. Would you mind giving some more details?
* Did it work after restarting ResidualVM?
* Which version of the game/HD mod are you using?
* Can you attach a save file where the issue happens?

**Comment by Askmewho** [comment]
yes, it happened just one time. so, no problema.

amazing performance on rpi4, and it was on 2.1 gl, maybe 3.x gl ES could boost performance

https://www.youtube.com/watch?v=qRagErcUG74&t=258s
https://www.youtube.com/watch?v=dC2rBcCIH-U&t=765s
