### ISSUE TITLE
TLJ: GOG German fan patch translation

### ISSUE THREAD

**Issue by legluondunet** [residualvm/residualvm#1581]
Hello, could you add TLJ 4CD german compatibility:

Matched game IDs for the Stark Engine engine: tlj-win

  {"x.xarc", 0, "de8327850d7bba90b690b141eaa23f61", 3032},
  {"chapters.ini", 0, "d65f3cdf44ac4b5e3cd1a35e2a13f3db", 511},

thank you for your help.

**Comment by bgK** [comment]
Hi,

Where does this version come from? `x.xarc` is from a 2 CD / DVD version and `chapters.ini` does not match the usual german file.

**Comment by legluondunet** [comment]
You are right, it's a fan patch to translate GOG version in german. I found it here:
https://www.validstrategies.com/files/file/323-the-longest-journey-gog-german-language-pack/
Is it possible to support it?

**Comment by bgK** [comment]
I'm sorry, but, no. I don't want to deal with bugs caused by mixing files from various versions of the game. So what needs to happen is for the patch author to modify his package so that it matches either the 2CD or the 4CD version of the game.

**Comment by legluondunet** [comment]
you are right, I understand your position, thanks.
