### ISSUE TITLE
Can't add Longest Journey

### ISSUE THREAD

**Issue by budchu** [residualvm/residualvm#1583]
Hello
iMac Mojave 10.14.6
Residualvm 0.4.0git (Nov 16 2019 03:40:10)
The Longest Journey 4CD FRENCH (Ubisoft 1999)
I can't add the game. I have this message Residualvm could not find any game in the specify directory !
 Is the french version is OK for this test ?

**Comment by Botje** [comment]
Did you follow [the instructions](https://github.com/residualvm/residualvm/#51-required-files)?
If so, please show the contents of the directory where you copied the files to.

**Comment by bgK** [comment]
The macOS daily builds are not fixed yet, aren't they? Could you please try the macOS version from there: https://www.moddb.com/mods/the-longest-journey-hd/downloads/residualvm-for-macos?

**Comment by budchu** [comment]
Thank you,
With this version I can Add the game TLJ
I try another daily build MacOS in the future.
