### ISSUE TITLE
TLJ - Game not found

### ISSUE THREAD

**Issue by marus70** [residualvm/residualvm#1587]
I've just installed daily build 0.4 (12th october) and copied the required files (https://github.com/residualvm/residualvm/#51-required-files) from the 4 CD version of TLJ
but ResidualVM keep saying could not find any game in the specified directory.
Any suggestion?
Thanks

**Comment by bgK** [comment]
Are you on macOS? If so, please use ResidualVM from here:
https://www.moddb.com/mods/the-longest-journey-hd/downloads/residualvm-for-macos
The macOS daily builds are not working for TLJ.

**Comment by marus70** [comment]
Thank you!

**Comment by marus70** [comment]
> Are you on macOS? If so, please use ResidualVM from here:
> https://www.moddb.com/mods/the-longest-journey-hd/downloads/residualvm-for-macos
> The macOS daily builds are not working for TLJ.

I did it but once i tried to add game i got this message:

The game in '/Applications/Residual/Games/The Longest Journey' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the Stark Engine engine: tlj-win

  {"x.xarc", 0, "a0559457126caadab0cadac02d35f26f", 3032},
  {"chapters.ini", 0, "9a81ea4e6f5b84511dd4e56d04a64e2e", 498},

**Comment by bgK** [comment]
Oh, this is the Italian version. The version on moddb is too old to know about it. I've asked faberman to update it.

In the mean time, here is an updated version: https://ufile.io/8453heon.

**Comment by marus70** [comment]
> Oh, this is the Italian version. The version on moddb is too old to know about it. I've asked faberman to update it.
> 
> In the mean time, here is an updated version: https://ufile.io/8453heon.

It works, thank you!
