### ISSUE TITLE
ANDROID: File Browser not displaying properly

### ISSUE THREAD

**Issue by Smashman4** [residualvm/residualvm#1589]
I can't access any directory using the Google Play Store version. It'll start at \ and show no folders. It only happens on my MOQI I7s (using Android 8.1 not rooted). My Samsung Galaxy S9+ works just fine. What can I do to fix this?
![Screenshot_20200111-172316](https://user-images.githubusercontent.com/29053081/72211335-90aa3000-3497-11ea-8192-4d314e790c6d.png)

**Comment by Botje** [comment]
The Android version on Google Play is way out of date, sadly. We can only push new releases once #1568 is fixed, so keep an eye on that.

**Comment by Smashman4** [comment]
Ok I will. Have you been working on it, or is it on hold?

**Comment by Smashman4** [comment]
Is there a way I can build it myself? I tried using android studio and a terminal, but it gives me errors.

**Comment by klusark** [comment]
@Smashman4 I haven't done it for a few years, but the ScummVM page on how to build might help https://wiki.scummvm.org/index.php/Compiling_ScummVM/Android

As well as our travis scrips for building android which you can find here: https://github.com/residualvm/residualvm/tree/master/.travis

Let me know if you still have issues.

**Comment by Smashman4** [comment]
Just tried compiling using the .travis folder, and I get the error: "make: *** No rule to make target `libresidualvm.so'.  Stop."

**Comment by Smashman4** [comment]
@klusark any fix for this?

**Comment by nugemon** [comment]
I'm having the same issue. Is there an .apk available anywhere and not the google play store?

**Comment by Botje** [comment]
Either compile it yourself, wait until #1568 is fixed, or until me or @klusark manually upload a build.
