### ISSUE TITLE
PC/Linux:  Brightness/Gamma settings not working.

### ISSUE THREAD

**Issue by clort81** [residualvm/residualvm#1590]
When changing brightness of in-game option, or gamma level in config file, brightness/gamma does not change.  
```
WARNING: Lua_V1::SetGamma, implement opcode, level: 0.500000!
```

Tested in windowed mode, opengl, opengl_shader and software renderers.

Ideally i'd like to use a glsl shader with LUT for intensity:

![grimlighting2](https://user-images.githubusercontent.com/51511737/73332188-3e725880-4266-11ea-90ab-c2a5818171c1.png)

**Comment by clort81** [comment]
This shader makes backgrounds visible.  Drop it in /engines/grim/shaders and set renderer=opengl_shaders in your residualvm.ini

```
in vec2 Texcoord;

OUTPUT

uniform sampler2D tex;

const float myg = 0.58;  // our desired (inverse) gamma (0.72=1.38)

void main()
{
	vec4 c = texture(tex, Texcoord);
        outColor = vec4(pow(c.r,myg), pow(c.g,myg), pow(c.b,myg), c.a);
}
```

![grimfanfixed](https://user-images.githubusercontent.com/51511737/73343643-412e7700-4281-11ea-9f46-17ffd7905bba.png)

**Comment by clort81** [comment]
Here's a scene illustrating the 'black crush': loss of visual information due to (stylistic?) scooped intensity ramps at the low-end.

![grim-black_crush](https://user-images.githubusercontent.com/51511737/73371745-6f7a7980-42b6-11ea-9d3e-27841c41e9c9.png)

Notice in hand-corrected picture at bottom:
- trees have defined shape and depth 
- ground gradient fades to black instead of stopping abruptly
- metal on trailer has texture instead of being a black void

**Comment by Botje** [comment]
Thanks for the idea and the examples so far!

A small implementation remark: We can do color correction as a general post-processing step for the entire image. That eliminates the square you saw in the smush shader, at the expense of making foreground characters jump colors.

**Comment by clort81** [comment]
Would applying a parametric intensity function to background images at load-time be an option?  This would mean implementing one solution instead of three or four (tinyGL, opengl, opengl-shader and openglES), correct?

Just sharing thoughts here.

**Comment by Botje** [comment]
You would need to apply that correction to widescreen parts as well, but yes, that is doable.

**Comment by clort81** [comment]
An example showing why parametric curves can give results truer to the 'film noir' aesthetic while revealing objects that were hidden by the 'black crush'.
![more-grim_colors](https://user-images.githubusercontent.com/51511737/73429082-0ee15000-433b-11ea-905e-2b1e32f17c59.png)

**Comment by clort81** [comment]
Another comparison between hand-drawn curves and shader-based gamma, this time with gamma = 1.43 (1/0.70)
![grcascol](https://user-images.githubusercontent.com/51511737/73440644-edd82980-4351-11ea-9177-0498fb87c3ee.png)

**Comment by Deledrius** [comment]
I'd say the gamma adjustment looks better than the default _and_ the hand-crafted curves.  The original is definitely too dark, but the curves are flattening the image and are definitely showing too much; the areas that reveal so much dithering and incorrect hue need to be left in shadow.

A functional gamma adjustment would probably be sufficient, as the overall balance in the images looks fine once the gamma is pushed just slightly.
