### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [residualvm/residualvm#1594]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing ResidualVM on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by Botje** [comment]
How does that compare to the distribution packages we build now? Are all our dependencies available as Flatpak packages or do we need to compile SDL2, libmad, libvorbis, glew, ... from scratch?

**Comment by aquadran** [comment]
It sounds like another distribution, but more wide target. Anyway it's outside of ResidualVM, and our scope. if anyone willing support it on Flathub feel free do it. We had in past static compiled builds, but this required keep updating libraries.
