### ISSUE TITLE
Mac nightly build missing Vorbis support

### ISSUE THREAD

**Issue by ehoppmann** [residualvm/residualvm#1595]
When trying to use the current Mac nightly build for TLJ there is no sound (outside of cinematics) and there are many warnings like `WARNING: Cannot decode sound '00.ovs', Vorbis support is not compiled in!` 

Version: 0.4.0git (Feb 3 2020 03:46:51)

I just compiled master using the build commands from .travis.yml and that version is working great for me (compiled with `Apple clang version 11.0.0 (clang-1100.0.33.17)`)

Thanks for your work on this!!

**Comment by Botje** [comment]
I think @aquadran is the only one who can install libraries on the build machines.

**Comment by aquadran** [comment]
This mean, TLC engine lacks dependency on Vorbis

**Comment by Botje** [comment]
Looking at the code, this Vorbis support is only required for one specific edition of the game.
If we plan to ship this as "officially supported" in 0.4.0 eventually, it would be unfortunate to exclude people with this edition.

**Comment by aquadran** [comment]
I think engine should have dependency set to vorbis, it's not clear that is missing at runtime.

**Comment by bgK** [comment]
If it prevents users from running into issues, let's add it.

**Comment by aquadran** [comment]
fixed
