### ISSUE TITLE
TLJ: German HD-FMV 720/1080p60 videos slow

### ISSUE THREAD

**Issue by technician77** [residualvm/residualvm#1596]
Using the German DVD Version as a basis, applied the HD 1.02 patch and then added the german HD FMV videos. The german videos are, unlike the english version, in p60. The author claims that you need a strong CPU. I understand that but Taskmanager only show usage around 50%. Already using the 720p60 version, but it still stutters. Intel GPU usage is not above 20%. CPU is Intel Core i5-6600T. Should I get a Ryzen 2 or is it a Residual VM issue?

**Comment by bgK** [comment]
Where did you get the ResidualVM version you are using? An optimized build is required for the HD FMVs to play at full speed. You can get one of those on moddb:
https://www.moddb.com/mods/the-longest-journey-hd/downloads/residualvm-for-windows
https://www.moddb.com/mods/the-longest-journey-hd/downloads/residualvm-for-macos

**Comment by technician77** [comment]
Hmm, the version you linked is older then the one I used. The title page refers to the "daily" builds. I used the latest that is available for windows: https://www.residualvm.org/downloads/residualvm-win32.exe

**Comment by bgK** [comment]
The daily builds are debug-style build. They cannot run the HD FMVs at full speed. There have not been many changes since the versions on moddb. You are not missing anything by using them.

**Comment by technician77** [comment]
Ok, will try the december built and replace that one with the next stable version. Thanks.

**Comment by technician77** [comment]
A final note: These games are art, thanks for making all the efforts to preserve them.
