### ISSUE TITLE
Issue with F1 button on Mac can't Save/Load game

### ISSUE THREAD

**Issue by illollo74** [residualvm/residualvm#1597]
I can't save/load the game! I have ResidualVM 0.3.1 on a Mac OsX 10.11.6 and I have Grim Fandango installed (with the update 1.0.1).
It seems to work great but I can't open Menu Window with F1 Key (and with no other keys). 
Obviously the button works great and all the other keys works perfectly. 
Does anyone can help me?
Please!
Thank you

**Comment by aquadran** [comment]
it is 32bit or 64bit version? can you try daily?
0.3.1 64bits works fine for me and also daily.
