### ISSUE TITLE
BUILD: Compiler reported as not found by configure if options not recognized

### ISSUE THREAD

**Issue by mparnaudeau** [residualvm/residualvm#1610]
If a compilation option is given in CXXFLAGS to the configure command and it is not supported by the compiler (or if there is a typo), that causes an error saying the compiler is not found. For example:

```
mathias@brix-debian$ CXXFLAGS="-fstack-protetor" ./configure 
Running ResidualVM configure...
Looking for C++ compiler... none found!

mathias@brix-debian$ CXXFLAGS="-fstack-protector" ./configure
Running ResidualVM configure...
Looking for C++ compiler... g++
Checking for compiler version... 6.3.0, ok
```

Two checks should be distinct:

- on the compiler availability
- on the compilation with given options

**Comment by aquadran** [comment]
is this fixed in ScummVM already? ResidualVM follow ScummVM codebase.

**Comment by mparnaudeau** [comment]
I checked and this is not fixed in ScummVM (behaviour is the same). I did not think about that ... How do we proceed in this situation? Should I open a ticket in the ScummVM bugtracker? Or have you started to manage that (as you assigned the issue to yourself).
