### ISSUE TITLE
BUILD: AmigaOS build broken with OpenGL enabled

### ISSUE THREAD

**Issue by mparnaudeau** [residualvm/residualvm#1611]
Buildbot reports that the AmigaOS4 build is broken for a while.
This is due to the namespace Image (used for screenshots) that conflicts with the struct Image in the AmigaOS system includes.
Hopefully AmigaOS proposes to enable a namespace for its own structures and types.

However, that is not enough: there are 3 levels of includes implied with the OpenGL feature: MiniGL, Warp3D and system.
If the AmigaOS namespace is enabled, that makes some GL functions not accessible without the namespace prefix. That needs to be investigated further to tend to more refined changes.

I will look at that trying to minimize the changes in the ResidualVM but pushing changes in the MiniGL and/or Warp3D includes is not straightforward.

**Comment by mparnaudeau** [comment]
I found how to build successfully but that required a hack in AmigaOS4 includes (I don't know if changes there would be accepted), in addition to minor changes in the SDL backend.
Another solution would be to have an option to disable screenshot saving (in BMP, PNG, ...), avoiding the use of the namespace Image.

**Comment by raziel-** [comment]
@mparnaudeau

I encountered the namespace bug myself.
I asked the SDK maintainers and was told that residualvm has to fix it, because AmigaOS4 is not to blame...or something like that.

What i still don't understand is why is the screenshot saving working in ScummVM, they do share the same code base...does residualvm do it so different?

**Comment by mparnaudeau** [comment]
The difference relies on the use of OpenGL (as mentioned in the bug title) because MiniGL uses the Intuition includes that own the `struct Image` conflicting with `namespace Image`.
I presumed that OpenGL is not enabled in the AmigaOS build.

Thinking again about all that, I wonder if it  would be possible to act on MiniGL includes (if system structures couldn't be made private).

**Comment by raziel-** [comment]
OpenGL should be enabled in ScummVM (at least locally, not sure about the buildbot).
There isn't much (or any) impact speed-wise on using OpenGL with ScummVM though

**Comment by aquadran** [comment]
Image is part of ScummVM core. Change needs to be applied there first.
