### ISSUE TITLE
Grim Fandango (German)

### ISSUE THREAD

**Issue by pandaworld78** [residualvm/residualvm#1625]
Error message when starting the game:

  {"VOX0001.LAB", 0, "d304aa402098de5966816c0a11e45816", 388753408},

**Comment by Botje** [comment]
Which edition is this? We already have a detection entry for German Grim, with the same start but a file size of 66,829,347 bytes instead of 388,753,408

**Comment by somaen** [comment]
Related to #1173?

**Comment by bgK** [comment]
We had a tool for copying the copy-protected versions of Grim Fandango from the CDs but it got removed at some point: https://github.com/residualvm/residualvm-tools/commit/013e0a3a83215995061d50194a811446e41cba6f

**Comment by pandaworld78** [comment]
As far as I know, this version was available for free for a short time on any website.
Have now found a launcher v1.6 with which the game can be started in window mode. Full screen is selectable, but unfortunately does not work.

**Comment by aquadran** [comment]
We don't support this version
