### ISSUE TITLE
Hangs if pulseaudio connection fails on Linux

### ISSUE THREAD

**Issue by weskerfoot** [residualvm/residualvm#1629]
~~I'm not really sure what other information to give. I'm running it on Arch Linux, and when I type `residualvm` nothing happens. It simply hangs unless I send the process a SIGQUIT (I.e. Ctrl+c).~~

~~I do see the actual window flash briefly before it quits when I send it a SIGQUIT though.~~

The problem seems to have been pulse audio. I did an strace against it and saw that it was failing to get a connection to pulse, which for some reason causes it to hang without any visible error. I fixed it by killing and restarting pulse.

Could there be a better error message here?

Here is the version info
> ResidualVM 0.4.0git (May  4 2020 03:36:11)
Features compiled in: Vorbis MP3 ALSA RGB zLib MPEG2 FreeType2 JPEG PNG

**Comment by Botje** [comment]
Infinite blocking on the pulseaudio socket seems like a pretty niche condition to detect. Do you know of other software that handles this gracefully?

**Comment by weskerfoot** [comment]
> Infinite blocking on the pulseaudio socket seems like a pretty niche condition to detect. Do you know of other software that handles this gracefully?

I think there might be something else going on here as well since I usually don't have issues with pulse. I can try to reproduce it as well.

**Comment by weskerfoot** [comment]
Feel free to close this but I think it might be a good idea to add an entry to the troubleshooting guide for Linux at least

**Comment by Botje** [comment]
Connection to pulseaudio blocking should be a very rare occasion.
