### ISSUE TITLE
EMI (Mac) : Page-Up/Page-Down sends double keystroke, game unplayable

### ISSUE THREAD

**Issue by ferro4prez** [residualvm/residualvm#1630]
EMI, MacOS 10.14, MBPro 13", ResidualVM (Nightly):

Pressing Page-Up/Page-Down to cycle between multiple options in the game world results in a "double-press" of the key, skipping over every second option.  Game is unplayable in this state, right off the bat.

Example: visit the Voodoo lady and approach the hand, you will have options such as "Pull pinky finger, Pull Middle finger, Pull thumb".  Press Page-Down and it will go directly from "Pull pinky finger" to "Pull thumb".  Same behaviour in the Up direction.

Observation: This is on a 13" MBPro which does not have explicit Page-Up/Page-Down keys, instead you must use Option-Up/Option-Down.  Related?

**Comment by ferro4prez** [comment]
Any thoughts?

**Comment by Botje** [comment]
I could not reproduce this with an SDL2 event testing tool, so it must be something ResidualVM-specific. Need to check with an actual game.

**Comment by ferro4prez** [comment]
> I could not reproduce this with an SDL2 event testing tool, so it must be something ResidualVM-specific. Need to check with an actual game.

Thanks Botje, let me know if there's anything I can do to help.  Videos/screenshots etc.

**Comment by Botje** [comment]
I tried to reproduce this in the SCUMM bar near the pirates playing darts. fn-up/fn-down (not option) results in the selection jumping by one element for me. Are you using any special hardware?

My hardware: 13" MBPro 2015, macOS 10.14.6

**Comment by ferro4prez** [comment]
Weird, just using stock Macbook Pro 13" with Touchbar here.  Maybe something about the Function Keys is mapped differently when there's a touchbar?

[img]https://i.imgur.com/aCWKfex.mp4[/img]

[img]https://i.imgur.com/G4cAcsa.png[/img]

**Comment by Botje** [comment]
Can you compile the SDL2 event test program at https://gist.github.com/DanielGibson/12041b57a540cbbfbaf9 and see how many events a single option+up/down generates?

**Comment by ferro4prez** [comment]
This is from Option+Up/Down:

Last login: Sat May  9 13:53:10 on ttys000
DEBUSSY:~ ferro$ /Users/ferro/Downloads/sdl2test ; exit;
Warning: No joysticks connected!
SDL_KEYDOWN: Keycode: Left Option (1073742050) Scancode: Left Option (226)
SDL_KEYDOWN: Keycode: Down (1073741905) Scancode: Down (81)
SDL_KEYUP: Keycode: Down (1073741905) Scancode: Down (81)
SDL_KEYUP: Keycode: Left Option (1073742050) Scancode: Left Option (226)

**Comment by ferro4prez** [comment]
This is from Fn-Up/Down:

Last login: Sat May  9 13:53:38 on ttys000
DEBUSSY:~ ferro$ /Users/ferro/Downloads/sdl2test ; exit;
Warning: No joysticks connected!
SDL_KEYDOWN: Keycode: PageDown (1073741902) Scancode: PageDown (78)
SDL_KEYUP: Keycode: PageDown (1073741902) Scancode: PageDown (78)

**Comment by ferro4prez** [comment]
Thanks for investigating this btw!

**Comment by Botje** [comment]
This corresponds to the behavior on my machine .. SDL2 itself confirms that option-up/down does not generate a pageup/down! Unless the dailies are still built against SDL1 for some reason.

**Comment by ferro4prez** [comment]
Interesting...I did have to edit the sdl2test.c file to get it to even run:
#include </Library/Frameworks/SDL2.framework/Versions/A/Headers/SDL.h>

Without pointing directly it was failing with a "Cannot find SDL.h".  Does that imply the dailies are building against SDL1?  Should I try to install that and re-run the test?

**Comment by Botje** [comment]
I just checked: the dailies are built against SDL2 2.0.10; I see no relevant changes in the changelog. And the test application runs fine for you.

Can you reproduce this behavior elsewhere (ie the pirates playing darts) or is it limited to the voodoo lady?

**Comment by ferro4prez** [comment]
Same behaviour with pirates playing darts.  Fn seems to do nothing, and Option sort of works like Fn should work other than the double keystroke.  Outside of ResidualFM, Fn-Up/Down works as expected.

I'm going to try this on another Mac 13" and see how the Fn/Option keys behave.  I don't have access to another TouchBar Mac however, but let's see what happens.

**Comment by ferro4prez** [comment]
I don't want to be wasting devs time if this is something on my end...I just can't imagine it is.  The behaviour is so incredibly strange.

**Comment by ferro4prez** [comment]
I've made another video.  I've connected a full USB keyboard (with exclusive PgUp/PgDown keys) to the Mac and demonstrate the following:

1. PgUp/PgDown (directly on keyboard) does nothing.
2. Alt-Up/Down has the "doubled keypress" behaviour of Option-Up/Down on the built-in Mac keyboard.

 https://imgur.com/rSEVSty

**Comment by ferro4prez** [comment]
In addition to the above comment, I ran sdl2test.c with the external keyboard and pressing PgUp/PgDn keys correctly resulted in PgUp/PgDn press/release events, but these same keys did not work in ResidualVM.

**Comment by ferro4prez** [comment]
I deleted the ResidualVM Preferences/plists and downloaded the updated Daily, and it now works! Not sure what fixed it.  Thank you.
