### ISSUE TITLE
TLJ: random crashes to desktop and save corruption

### ISSUE THREAD

**Issue by NordicSnow** [residualvm/residualvm#1633]
Game crashes to desktop at random intervals and deletes all the data contained in save file 0, leaving it at 0KB.

[residualvm.log](https://github.com/residualvm/residualvm/files/4606951/residualvm.log)

**Comment by NordicSnow** [comment]
Issue appears to have been resolved by disabling auto saves.

**Comment by Botje** [comment]
Can you get us a crash dump? This sounds serious.
