### ISSUE TITLE
Joystick support

### ISSUE THREAD

**Issue by guijorgee** [residualvm/residualvm#1634]
Since b586571900c1790fc5c264e86b7abb573dab5958 joystick support is broken.

From what I understand, there is a mix between legacy SDL events and new SDL events that were introduced in ScummVM.

Some functions in ResvmSdlEvents are still defined but are now uncalled like
 - handleAxisToMouseMotion
 - handleKbdMouse

**Comment by aquadran** [comment]
yeah, I though something might be broken in joystick. I'll look into

**Comment by aquadran** [comment]
can you try with latest code? I tried to restore functionality. If this will not work I'll try find joystick to check this.

**Comment by guijorgee** [comment]
Left joystick now responds, but cursor movements are jerky or even simply blocked.
You still need to push button several times to have it working too.

**Comment by aquadran** [comment]
btw. what kind of joystick do you use?

**Comment by aquadran** [comment]
I got some joystick, indeed movement is jerky. I guess might be some events lost or something.
Interesting joystick doesn't work for me before sync with scummvm.

**Comment by aquadran** [comment]
ok, it was typo in pollEvent. can you try latest code?

**Comment by guijorgee** [comment]
I'm using an Xbox controller.
`input: Microsoft X-Box 360 pad as /devices/pci0000:00/0000:00:14.0/usb3/3-2/3-2:1.0/input/input36`

It seems to be ok for Myst 3 now. Thx !

But not for Grim Fandago / EMI. It seems that mapping from Grim games are not taken into account.
 - "A"; "B", "L1" are not working, such as left joystick. Indeed, left joystick moves the cursor, but not Manny.
 - "Y" button quit the game.
 - "Start" button doesn't open the "F1" menu anymore.

And after a while, jerking cursor movements happen again.
Example: Switch between "Start" button -> "Resume" -> "Start" button -> ...

**Comment by guijorgee** [comment]
Also I just noticed that "_km.modifier" is never set to "true". Something is possibly missing here too ?

**Comment by aquadran** [comment]
indeed, this is something with the mapping. It's a pad so code flow goes for controller not joystick.
I'll look into.

**Comment by guijorgee** [comment]
hi, any progress about this ?

**Comment by aquadran** [comment]
I don't know what is a problem. I suspect there are conflicts with new event code with old residualvm native controller code. I don't have 360 pad.

**Comment by aquadran** [comment]
I tried PS3 pad, analog and digital joystick works fine. about mapping it should be handled by generic mapping code. I'll try implement new way.

**Comment by aquadran** [comment]
Switched to new scummvm events manager. Lack joystick support in Myst3 for now.

**Comment by aquadran** [comment]
I just added new buttons mapping for grim fandango and monkey island. also joystick support available in myst3. try next build available on 7 October.
