### ISSUE TITLE
TLJ: Sudden crash affecting savegame 0

### ISSUE THREAD

**Issue by eriosl** [residualvm/residualvm#1635]
While I am playing, the game crashes at random time (i.e. not always in the same scene or with the same time intervals between crashes)

I noticed that when I restart the game after a crash, it crashes again as soon as I try to open the load game option (A console with an error stating that "can't read the saved game files" or something like that pops up)

It is worth to mention that the crash occurs suddenly when playing, not at specific action such as opening a video or saving/loading a game, but rather all of a sudden when walking or interacting normally with the game (although sometimes crashes when entering a new scene).

**I also noticed that when the crash happens, the size of the first saved game file (tlj-win-000.tlj) changes to 0 KB. And that as soon as I delete it, I can open the game and load any of the remaining files again, and even use slot 0 again to save a new game**. However, the game crashes again in 20 minutes or so.

I just tried to set "read only" to a newly created tlj-win-000.tlj file, in an attempt to make it imposible for the bug to open that file, though I don't expect to actually fix the problem, but perhaps just report what it actually does and report back to you.

Thanks for the great engine!

**Comment by bgK** [comment]
Hi, thanks for your report. This is fixed as part of issue #1633 already.
