### ISSUE TITLE
Please tag a new release

### ISSUE THREAD

**Issue by newbluemoon** [residualvm/residualvm#1641]
Hi,

I’m maintainig residualvm for [voidlinux](https://voidlinux.org). Policy is to update only releases and the last one is rather old (about two years). Much has been improved since then and I’d like to update the package. Is it possible that a new release can happen in the forseeable future? Thank you very much!

**Comment by aquadran** [comment]
Not sure if near future. There are some improvements and some regressions. TLJ I think is ready to release. Anyway release will be when it's ready to release. We don't have any time table.

**Comment by newbluemoon** [comment]
Thank you for clarifying! Anyway, I hope it will be rather sooner than later, but then again good things take as long as they take. :)
