### ISSUE TITLE
MYST3: unknown variant

### ISSUE THREAD

**Issue by epk-let** [residualvm/residualvm#1645]
<<

The game in 'Exile\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the myst3 engine: myst3-win

  {"RSRC.m3r", 0, "a2c8ed69800f60bf5667e5c76a88e481", 1223862},
  {"ENGLISH.m3t", 0, "74726de866c0594d3f2a05ff754c973d", 3407120},

>>

**Comment by bgK** [comment]
Hi,

It looks like your installation of Myst III is missing the language file. Please make sure to follow the installation instructions from the readme: https://github.com/residualvm/residualvm#41-required-files

**Comment by epk-let** [comment]
Cool, thanks! I had been working from a set of instructions that was a little less explicit about the handling of the language file. It was there, but not in the right place. appreciate your quick help.

________________________________
