### ISSUE TITLE
WINTERMUTE: Rpi3 build problems

### ISSUE THREAD

**Issue by paradadf** [residualvm/residualvm#1648]
Hi! I‘m trying to cross-compile ResidualVM for a Rpi3 and got problems on the Wintermute module about OpenGL context.

The full log can be seen here:  
https://pastebin.com/dBfzaC4F

**Comment by aquadran** [comment]
wintermute is not supported, disable engine from configure

**Comment by paradadf** [comment]
@aquadran if it isn't supported yet, shouldn't it not be built be default?
