### ISSUE TITLE
Crash - Assertion failed: _entriesPerPage > 0, file gui/widgets/list.cpp, line 724

### ISSUE THREAD

**Issue by buildist** [residualvm/residualvm#1658]
1. Check out and build latest source (Windows, MinGW MYSYS, current commit is https://github.com/residualvm/residualvm/commit/626c55780b605030e2fb308f7de0947e840ace09)
2. Add game Myst III: Exile (possibly not required to trigger the bug)
3. Open options, check "Fullscreen mode" and click Apply.
4. Crash, assertion error in console.

**Comment by aquadran** [comment]
works fine here
