### ISSUE TITLE
TLJ Czech localisation

### ISSUE THREAD

**Issue by Rendoss** [residualvm/residualvm#1700]
Hello, after installing czech localisation I get following message:

The game in 'The Longest Journey\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the stark engine: tlj-win

  {"x.xarc", 0, "de8327850d7bba90b690b141eaa23f61", 3032},
  {"chapters.ini", 0, "547f0b9c04c00d330b60eed6e8d24732", 484},

Czech is installed via self extracting archive which overwrites original files.
It states it is for version DVD v1.61.
Source: https://www.abcgames.cz/?p=preklady_zobraz&id=3973

**Comment by Botje** [comment]
Is this a fan translation or is this extracted from an official release somehow? The second case violates rule 0. (no piracy)

**Comment by Rendoss** [comment]
> Is this a fan translation or is this extracted from an official release somehow? The second case violates rule 0. (no piracy)

As far as I can tell it's fanmade by MMax.

**Comment by Rendoss** [comment]
Replacing chapters.ini with original "english" file fixes the issue. Found this under hungarian localisation post. 

But now I face font issues. Somehow it's not possible to edit fonts via gui.ini when running from residualVM. When I run the game by standard exe file, fonts are ok (as specified in gui.ini). Is there different way to edit font usage when you run it in RVM?

**Comment by Botje** [comment]
Show the contents of your gui.ini and residualvm config. I see references to a `ignore_font_settings` setting in the code.

**Comment by Rendoss** [comment]
> Show the contents of your gui.ini, ResidualVM config and logfile. I see references to a `ignore_font_settings` setting in the code.
> Also check the logs for entries of the kind `Unable to read font entry 'XXX' from 'gui.ini'`

Ok I will send settings later today.
I was succesfull with forcing different font by renaming font files to the ones used. But the issue seems to be in ResidualVM not supporting czech subtitles. Even tho correct font was used it still failed to show certain characters (ž, š, ř, ě, ď, ť).

**Comment by Rendoss** [comment]
It's under engines/stark/services/fontprovider.cpp
but I dont understand how this works

**Comment by Rendoss** [comment]
[residualvm.log](https://github.com/residualvm/residualvm/files/5162996/residualvm.log)

**Comment by Jurajov** [comment]
... in that gui.ini it is still necessary to change the font7 (April diary) to "Present Cyr", because these settings spoil the diacritics in the game when reading the diary...just such a detail. did something new happen that would start the game in residualvm in the Czech language?
