### ISSUE TITLE
MYST3: Autosave does not work

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1708]
ResidualVM 0.4.0git1069-gd0713f107 (Sep 30 2020 10:10:17)
OS: Windows 10 x64
Game: Myst 3 Exile v1.27 rvm (21807)

1. Autosave does not work

![screen3](https://user-images.githubusercontent.com/22292375/94886760-d9cb6580-04a6-11eb-9ac1-04c4ec81be33.JPG)

**Comment by aquadran** [comment]
I just checked, works for me. maybe your save game was corrupted somehow. can you delete it and check if it works?

**Comment by ctoroman** [comment]
The file Autosave.m3s is physically missing

**Comment by aquadran** [comment]
screenshot refer to existing file. what exactly happen?

**Comment by ctoroman** [comment]
That's just the point, the file seems to be in the game, but in fact it is not. It is not created by the game.

**Comment by aquadran** [comment]
if file is missing then from where you get autosave on the list in game. can you check configuration file if all looks ok?

**Comment by ctoroman** [comment]
I am using the compiled version of residualvm. Downloaded from here: https://www.residualvm.org/downloads/residualvm-win32.exe
In the settings, all paths are correct.

**Comment by ctoroman** [comment]
I rolled back to commit 6fed84899. macOS: resynced makefile with scummvm. Compiled residualvm. 
Autosave works. 
Then I moved on to commit b333691cc. MYST3: Implement the new autosave system. Recompiled residualvm. Autosave not working

**Comment by aquadran** [comment]
so new auto save system doesn't work for you somehow

**Comment by ctoroman** [comment]
It turns out that yes ... (

**Comment by aquadran** [comment]
b333691 it was fix for #1633 . I'll try reproduce issue once more.
