### ISSUE TITLE
TLJ - CZ lang

### ISSUE THREAD

**Issue by Jurajov** [residualvm/residualvm#1709]
Can you add CZECH language? game is The longest yourney 1.61v Win10x64

The game in 'The Longest Journey\' seems to be an unknown game variant.

Please report the following data to the ResidualVM team at https://github.com/residualvm/residualvm/issues along with the name of the game you tried to add and its version, language, etc.:

Matched game IDs for the stark engine: tlj-win

  {"x.xarc", 0, "de8327850d7bba90b690b141eaa23f61", 3032},
  {"chapters.ini", 0, "547f0b9c04c00d330b60eed6e8d24732", 484},

**Comment by aquadran** [comment]
it is DVD, 2CD or 4CD release?

**Comment by aquadran** [comment]
delicate to #1700

**Comment by Jurajov** [comment]
4cd
