### ISSUE TITLE
MYST3: Game won't launch after last update of ResidualVM

### ISSUE THREAD

**Issue by ctoroman** [residualvm/residualvm#1710]
ResidualVM 0.4.0git1078-gfc0638a4d (Oct  3 2020 09:40:30)
OS: Windows 10 x64

ResidualVM closes after starting the game. There is nothing in the log file.

**Comment by aquadran** [comment]
Should be fixed now

**Comment by ctoroman** [comment]
The game has started, but there is no control. No response to mouse movements.
