### ISSUE TITLE
STARK: Could not find suitable engine plugin

### ISSUE THREAD

**Issue by ultrasuperpingu** [residualvm/residualvm#1713]
With the current daily build, I can add tlj-demo-win-fr without any problem but when I try to launch it, I get an error message: Could not find suitable engine plugin. Did I miss something ?

**Comment by aquadran** [comment]
looks like engine is disabled in daily. @Kirben can you check this?

**Comment by aquadran** [comment]
looks like GLEW is not detected on build process

**Comment by Kirben** [comment]
Fixed now, the GLEW test in configure was failing on MinGW, since the OpenGL library (-lopengl32) was missing.

**Comment by aquadran** [comment]
interesting I didn't have this issue on MinGW locally. however I'm using msys2

**Comment by ultrasuperpingu** [comment]
Ok, the game now runs. Thanks
