### ISSUE TITLE
GRIM:New Message flag in Manny's office missing post - Graphics Glitch

### ISSUE THREAD

**Issue by bradc6** [residualvm/residualvm#273]
Build: ed5242ff0c84db844191
OS: Ubuntu 10.04

New Message flag in Manny's office missing post

**Comment by vpelletier** [comment]
I can't reproduce this issue as of bd262446fafcac0bd866d7df0923c4f5a4c15013 .
![screenshot_20161106_110134](https://cloud.githubusercontent.com/assets/191204/20036719/726b1fe8-a410-11e6-9340-1caec21c823f.png)

**Comment by somaen** [comment]
What renderer did you try with? As far as I know this is a game data issue,
much like the colour of the hole puncher.

Den søndag 6. november 2016 skrev Vincent Pelletier <
notifications@github.com> følgende:

**Comment by vpelletier** [comment]
This was with opengl+shaders.

But I understand now the game data issue: there *is* a post in the Z-buffer sense (something obscuring many's model), but its texture comes from the background shelves.
Zooming in on my screenshot, there is a lighter grey area where the flag's circle is nearest to the flag pole, which does line up on a shelve's label - and is likely really a shelf label. Kind of an unintended trompe-l'oeil.
