### ISSUE TITLE
GRIM: The post-tube in Manny's office is drawn one pixel too high.

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#278]
If you walk Manny by the tubes (which will happen when you try to read the mail), you will see that one pixel of manny is rendered below the pipe on the right side, since the pipe is quite exactly one pixel too high on the screen.

http://www.pvv.org/~somaen/moregrim2/residual001.jpg

**Comment by vpelletier** [comment]
The one-pixel gap is also visible in remastered version.
