### ISSUE TITLE
Manny won't climb up chain

### ISSUE THREAD

**Issue by Larrin** [residualvm/residualvm#375]
In Year 3 when I try to climb up the chain on the conveyor belt to complete the puzzle, Manny goes straight ahead instead of up the chain, he goes on seemingly forever because I can back him all the way back. I just can't go up. This is on Windows 7 64-bit with the  September 27, 2011, 1:30 pm build.

**Comment by marespiaut** [comment]
Hello,

I'm experiencing the same bug with revision 0bda7cd00bb59992fdb992f2d101591aafd40603 on GNU/Linux x86_64 with the French release of Grim Fandango.
To be fairly honnest, this isn't the first glitch I've experienced. I was using revision cf63e5dba8f8793adbda87ce8d1bf210f62290b8 and I also had several animation glitch, but nothing too serious.

**Comment by somaen** [comment]
I assume that dists/gamedata is in your extras-path (so that our script
patches are applied). I'm not sure if this is automatic if you build your
own binary.

Do you remember any of the earlier glitches?

Den mandag 30. mai 2016 skrev Marc-Alexandre Espiaut <
notifications@github.com> følgende:

**Comment by marespiaut** [comment]
I did build my own binary, and my game is patched to the latest official update.

I don't precisely recall which animation were buggy, but I could redo the game if necessary.

**Comment by somaen** [comment]
A savegame at the chain might at least be useful.

**Comment by marespiaut** [comment]
You can download my [savegame here](https://bfs.u-bordeaux.fr/telecharge.php?choix=files/10a61cccdf16ffda92e1331161d9038c/grim08.gsv).
