### ISSUE TITLE
GRIM: Incorrect hole punch color with TinyGL

### ISSUE THREAD

**Issue by vpelletier** [residualvm/residualvm#58]
In original game, the hole punch is dark grey.
With opengl, it is lighter grey (maybe a difference in ambient light, or my gamma...).
With TinyGL, it is blue.

(yeah, this _is_ a super-ultra-minor glitch... :) )

**Comment by vpelletier** [comment]
Color in residual matches the one from remastered version. So I think the bug lies on the original renderer side, so I close it.

**Comment by somaen** [comment]
No, dont close it, this is a game data issue.

Den søndag 15. mars 2015 skrev Vincent Pelletier <notifications@github.com>
følgende:

**Comment by vpelletier** [comment]
Ok, reopening.
