### ISSUE TITLE
GRIM: Can't go back up conveyor belt

### ISSUE THREAD

**Issue by catkfr** [residualvm/residualvm#738]
Hi,

There seems to be a bug moving up the conveyor belt.
Here is the save game: http://catkfr.free.fr/grim06.gsv

I managed to go up and down many times up until this save game (once I have the chain that loops around the anchor). Now, I can't go back up.
I've also tried the latest daily build: no luck.

I have a macbook air running ResidualVM 0.1.1

How can I help in fixing this bug?

**Comment by raziel-** [comment]
One can only go UP the conveyer belt when the belt is moving DOWNWARDS.

Just happened to me aswell, sounds illogical, but Manny only starts swimming upwards when the belt movement is going DOWN.
