### ISSUE TITLE
EMI: Guybrush's jaw is invisible when stepping down from the ledge at the Scumm Bar

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#896]
Try to enter the Scumm Bar, then leaving, as Guybrush is stepping down from the ledge, his jaw will be invisible, only to be visible again when the animation is completed.

OpenGL Renderer, latest master (a563dff4ad61b2daa1637a6c72e2f96c841b5418), with a minor code change to fix a nullptr/NULL issue in actor.cpp:1271 (probably quite unrelated).

**Comment by somaen** [comment]
Guybrush actually fades out completely when stepping onto the ledge in the PS2-version. (And then comes back).

**Comment by chkr-private** [comment]
Fixed by commit 6d226501b5a96b2f02035f9f4d82d54261eb2749.
