### ISSUE TITLE
EMI: Some lines are not spoken.

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#899]
If after destroying the catapult, you walk into the mansion and examine the government contract that is placed on the table, the text for the line that Guybrush should say is shown, but no speech is played.

OS X, OpenGL, a563dff4ad61b2daa1637a6c72e2f96c841b5418 (with a minor s/nullptr/NULL in actor.cpp:1271, which should be unrelated).

**Comment by monkeymadness** [comment]
This problem happened throughout multiple portions of the game. Talking to Otis, the Voodoo Lady, the figurehead, Marco de Pollo, Miss Rivers, Grouchy Judge, Hippie Judge, and JoJo Jr. all had instances of lines unspoken.

**Comment by somaen** [comment]
Some of these MAY happen as an effect of copying the wrong VoiceAll.m4b from the CDs, IIRC, the one from CD1 is the correct one, while CD2 only has a subset.

**Comment by monkeymadness** [comment]
Hmmm, I just looked at the VoiceAll.m4b and it is the one from CD1. I did notice that the CDs I own are rather scratched from previous use. Not sure if that would affect it.

**Comment by somaen** [comment]
There should be a verification procedure on first run that checks whether you had the files correctly copied. (This can be rerun by starting the game, then pressing  ctrl-d and typing "check_gamedata")

**Comment by monkeymadness** [comment]
Just ran "check_gamedata" 
Response was:
All files are ok.
