### ISSUE TITLE
EMI: Letter from Grandpa Marley is placed behind lawyers

### ISSUE THREAD

**Issue by somaen** [residualvm/residualvm#903]
Reproduce by:
Go to lucre island, enter the law office, complete the dialogue. Then the lawyers will give guybrush a letter from Grandpa Marley. This letter is placed behind the chair of the leftmost (camera relative) lawyer, instead of on the table.

OpenGL, OS X, a563dff4ad61b2daa1637a6c72e2f96c841b5418 (with s/nullptr/NULL in actor.cpp:1273, should be unrelated)

**Comment by chkr-private** [comment]
I could reproduce the issue with a563dff4ad61b2daa1637a6c72e2f96c841b5418 (OpenGL, Linux).

However, It doesn't happen with the current master (56b2a370bd38023d2da83fd03932466005403290) anymore.
