### ISSUE TITLE
EMI: Lawyers are missing their eyes on Lucre

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#934]
As seen here
![residualvm 2014-06-12 13-31-27-46](https://cloud.githubusercontent.com/assets/757718/3306712/df594b5a-f663-11e3-8655-840595441e68.png)

Either the eyes are missing completely, or perhaps the eye animation is stuck in "closed" state?

Reproduction: jump to 150 and go to the law offices.

Tested on 07009b7da, Win7, OpenGL

**Comment by chkr-private** [comment]
Seems to be fixed some time ago. I can still reproduce the original issue with commit b60a13b2240f990a4b8ca78a7b10d2b51a54d7e7, but the issue is gone in 56b2a370bd38023d2da83fd03932466005403290 (tested with OpenGL and OpenGLS).
