### ISSUE TITLE
EMI: Guybrush is visible through the city hall door

### ISSUE THREAD

**Issue by Akz-** [residualvm/residualvm#946]
When entering the city hall on Melee island, Guybrush can be seen through the door.

![residualvm 2014-07-01 15-49-59-74](https://cloud.githubusercontent.com/assets/757718/3443156/b285a3d8-011e-11e4-8ffa-9d4add19e5f8.png)

7712eb6c, OpenGL renderer

**Comment by monkeymadness** [comment]
This one is still an issue

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitc5ccf4d

**Comment by mparnaudeau** [comment]
It is still there with version 0.4.0-git2cad855, confirmed on Linux with the 3 graphics engines.
The problem does not exist in the original version.
