### ISSUE TITLE
EMI: The diving judges signs show through the desk

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#989]
![screenshot 2014-08-02 23 23 35](https://cloud.githubusercontent.com/assets/240865/3789958/cfce5e7c-1ad6-11e4-80df-7c117b2f38c2.png)

**Comment by monkeymadness** [comment]
Still able to see the signs.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0gitae24374
