### ISSUE TITLE
EMI: No path found for guybrush when getting the boulders on monkey island

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#992]
To reproduce:
Jump to set pac
Target the boulders and press p
It should walk guybrush to the rocks. Instead it does nothing.

Caused by this commit 3ec234757f0cf365d86e40f485a68fcc5f6115dd

After reverting that commit it works fine.

**Comment by chkr-private** [comment]
Fixed by commit 39b0172f721c4307ed3bdd36ce0c54b654c1e0fc.
