### ISSUE TITLE
EMI: Monkey doesn't join monkey combat

### ISSUE THREAD

**Issue by klusark** [residualvm/residualvm#993]
![screenshot 2014-08-03 09 10 51](https://cloud.githubusercontent.com/assets/240865/3791113/214337da-1b29-11e4-9c4e-1c32d4c0070d.png)

I've played around 8 or so games, and this has happened once, so it might be hard to reproduce. It was after my third time of winning though, but it doesn't always happen.

Save: 
![126 gsv](https://cloud.githubusercontent.com/assets/240865/3791147/26246510-1b2b-11e4-9d2e-b2acd62dbfaf.png)

**Comment by monkeymadness** [comment]
I was unable to reproduce this with the current version.

Version of the game: English version from a jewelcase
OS: Windows 7 64bit
Graphics Card: Intel HD Graphics Driver
Renderer: OpenGL
Version of ResidualVM: 0.3.0git52010ff
